var fs=require("fs");
var c=fs.readFileSync("index.html","utf8");
var q=String.fromCharCode(39);
var bi=c.rfind ? c.lastIndexOf("</body>") : c.lastIndexOf("</body>");
var si=c.lastIndexOf("</script>");
var page="<div class=\"page\" id=\"page-relation\"><div style=\"max-width:800px;margin:0 auto;padding:3rem 1.5rem 6rem\"><div style=\"text-align:center;padding:2rem\"><h2 style=\"font-family:Italiana,serif;font-size:2.5rem;color:var(--gold)\">Evalue ta relation</h2><p style=\"color:var(--muted);margin-bottom:2rem\">Selectionne un mode.</p></div>";
page+="<div style=\"display:grid;grid-template-columns:1fr 1fr 1fr;gap:1rem;margin-bottom:2rem\">";
page+="<div class=\"cc\" style=\"padding:1.5rem;text-align:center\" onclick=\"selectRelMode("+q+"attraction"+q+",this)\"><div style=\"font-size:2rem\">&#x1F525;</div><div>Attraction</div></div>";
page+="<div class=\"cc\" style=\"padding:1.5rem;text-align:center\" onclick=\"selectRelMode("+q+"debut"+q+",this)\"><div style=\"font-size:2rem\">&#x1F331;</div><div>Debut</div></div>";
page+="<div class=\"cc\" style=\"padding:1.5rem;text-align:center\" onclick=\"selectRelMode("+q+"couple"+q+",this)\"><div style=\"font-size:2rem\">&#x1F48D;</div><div>En couple</div></div></div>";
page+="<div id=\"relForm\" style=\"display:none\"><div class=\"blk\"><div class=\"blk-hd\"><span class=\"blk-ico\">&#x1F6A6;</span><span class=\"blk-t\">Signaux observes</span></div>";
page+="<div class=\"fg\"><label class=\"fl\">Green flags</label><div class=\"cg c2\">";
page+="<div class=\"cc\" data-fid=\"rel_green\" data-val=\"coherent\" onclick=\"selC("+q+"rel_green"+q+","+q+"coherent"+q+",true,this)\"><span class=\"cc-ico\">&#x2705;</span><div class=\"cc-t\">Dit ce qu il fait</div></div>";
page+="<div class=\"cc\" data-fid=\"rel_green\" data-val=\"ecoute\" onclick=\"selC("+q+"rel_green"+q+","+q+"ecoute"+q+",true,this)\"><span class=\"cc-ico\">&#x1F442;</span><div class=\"cc-t\">Ecoute</div></div>";
page+="<div class=\"cc\" data-fid=\"rel_green\" data-val=\"confiance\" onclick=\"selC("+q+"rel_green"+q+","+q+"confiance"+q+",true,this)\"><span class=\"cc-ico\">&#x1F513;</span><div class=\"cc-t\">En confiance</div></div></div></div>";
page+="<div class=\"fg\" style=\"margin-top:1rem\"><label class=\"fl\">Red flags</label><div class=\"cg c2\">";
page+="<div class=\"cc\" data-fid=\"rel_red\" data-val=\"incoherent\" onclick=\"selC("+q+"rel_red"+q+","+q+"incoherent"+q+",true,this)\"><span class=\"cc-ico\">&#x26A0;</span><div class=\"cc-t\">Incoherent</div></div>";
page+="<div class=\"cc\" data-fid=\"rel_red\" data-val=\"chaud_froid\" onclick=\"selC("+q+"rel_red"+q+","+q+"chaud_froid"+q+",true,this)\"><span class=\"cc-ico\">&#x1F321;</span><div class=\"cc-t\">Chaud froid</div></div>";
page+="<div class=\"cc\" data-fid=\"rel_red\" data-val=\"controle\" onclick=\"selC("+q+"rel_red"+q+","+q+"controle"+q+",true,this)\"><span class=\"cc-ico\">&#x1F517;</span><div class=\"cc-t\">Controlant</div></div></div></div>";
page+="<button class=\"btn-next\" onclick=\"analyzeRelation()\" style=\"width:100%;margin-top:1rem\">Analyser</button></div><div id=\"relResult\" style=\"display:none\"></div></div></div>";
