// Recommandations affichées à la fin du test des blessures intérieures.
export const BLESSURE_RECO = {
  rejet: {
    primaryGuideId: "guerir-blessure-rejet",
    tome2GuideId: "approfondir-blessure-rejet",
    completePack: "pack-blessure-rejet-complet",
    label: "Rejet",
    title: "Avancer avec la blessure de rejet",
    intro: "Au fond, tu as souvent senti que tu étais « de trop ».",
    signs: [
      "tu te retires avant qu'on te rejette",
      "tu vises la perfection pour mériter ta place",
      "tu fuis l'intimité quand ça devient trop vrai",
    ],
    message: "La peur de ne pas être à sa place peut te pousser à te retirer ou à te suradapter. Ces ressources t'aident à reconstruire une estime solide et à oser prendre ta place.",
    guideIds: ["confiance-estime-de-soi", "syndrome-imposteur", "briser-isolement"],
    packId: "pack-blessures-interieures",
  },
  abandon: {
    primaryGuideId: "guerir-blessure-abandon",
    tome2GuideId: "approfondir-blessure-abandon",
    completePack: "pack-blessure-abandon-complet",
    label: "Abandon",
    title: "Apaiser la blessure d'abandon",
    intro: "La peur d'être quittée ou laissée seule t'accompagne.",
    signs: [
      "tu t'accroches ou cherches sans cesse à être rassurée",
      "la solitude t'angoisse",
      "un silence te fait imaginer le pire",
    ],
    message: "La peur d'être quitté·e peut nourrir dépendance affective et jalousie. Ces ressources t'aident à aimer sans te perdre et à te sentir en sécurité, à l'intérieur.",
    guideIds: ["sortir-dependance-affective", "gerer-la-jalousie", "surmonter-une-rupture"],
    packId: "pack-blessures-interieures",
  },
  humiliation: {
    primaryGuideId: "guerir-blessure-humiliation",
    tome2GuideId: "approfondir-blessure-humiliation",
    completePack: "pack-blessure-humiliation-complet",
    label: "Humiliation",
    title: "Te libérer de la blessure d'humiliation",
    intro: "Tu fais passer les autres avant toi, et tu as du mal à recevoir.",
    signs: [
      "tu te sacrifies et te rends indispensable",
      "tu as honte de tes besoins",
      "dire non te culpabilise",
    ],
    message: "La honte et la peur du jugement peuvent te faire douter de ta valeur et de ton corps. Ces ressources t'aident à te réconcilier avec toi et à t'affirmer sans te rabaisser.",
    guideIds: ["confiance-estime-de-soi", "honte-de-classe", "gerer-ses-emotions"],
    packId: "pack-blessures-interieures",
  },
  trahison: {
    primaryGuideId: "guerir-blessure-trahison",
    tome2GuideId: "approfondir-blessure-trahison",
    completePack: "pack-blessure-trahison-complet",
    label: "Trahison",
    title: "Te reconstruire après la blessure de trahison",
    intro: "Tu as appris à tout contrôler pour ne plus jamais être trahie.",
    signs: [
      "tu as du mal à faire confiance et à déléguer",
      "tu dois être forte et avoir raison",
      "tu restes sur tes gardes",
    ],
    message: "La difficulté à faire confiance vient souvent d'une confiance abîmée. Ces ressources t'aident à reconnaître l'emprise, te refaire confiance et te reconstruire.",
    guideIds: ["reconnaitre-controle-coercitif", "sortir-du-gaslighting", "se-reconstruire-apres-relation-toxique"],
    packId: "pack-blessures-interieures",
  },
  injustice: {
    primaryGuideId: "guerir-blessure-injustice",
    tome2GuideId: "approfondir-blessure-injustice",
    completePack: "pack-blessure-injustice-complet",
    label: "Injustice",
    title: "Adoucir la blessure d'injustice",
    intro: "Tu es exigeante, perfectionniste, dure avec toi-même.",
    signs: [
      "jamais « assez bien »",
      "tu te coupes de tes émotions",
      "tu supportes mal l'imperfection, la tienne comme celle des autres",
    ],
    message: "L'exigence et le contrôle peuvent t'épuiser et te couper de tes émotions. Ces ressources t'aident à relâcher la pression et à retrouver de la souplesse.",
    guideIds: ["gerer-ses-emotions", "anxiete-de-performance", "equilibre-pro-perso"],
    packId: "pack-blessures-interieures",
  },
} as const;
