// Packs (bundles) : plusieurs guides vendus ensemble, 1 seul paiement Stripe livrant TOUS les PDF.
// Upload dans lib/bundles.ts. Câblage via etape18.txt.
// IMPORTANT : un pack ne fonctionne que si TOUS ses guideIds sont déjà live dans GUIDES.
// guideIds FR = ids des guides FR ; guideIds EN = ids des guides EN.
export const BUNDLES = [
  // ---------------- FR ----------------
  { id: "pack-carriere-rebond", lang: "fr",
    title: "Pack Carrière & Rebond",
    blurb: "Changer de voie, rebondir, te rendre visible et tisser ton réseau — 4 guides pour piloter ta carrière. (4 guides · 49€ au lieu de 76€)",
    priceCents: 4900, compareAtCents: 7600, currency: "eur",
    guideIds: ["reussir-sa-reconversion","rebondir-apres-licenciement","soigner-son-personal-branding","developper-son-reseau"] },
  { id: "pack-confiance-au-travail", lang: "fr",
    title: "Pack Confiance au travail",
    blurb: "Apaiser l'anxiété, prendre la parole, demander une promotion, gérer ton temps — 4 guides pour t'affirmer au travail. (4 guides · 49€ au lieu de 76€)",
    priceCents: 4900, compareAtCents: 7600, currency: "eur",
    guideIds: ["anxiete-de-performance","prendre-la-parole-en-public","demander-une-promotion","gerer-son-temps-deleguer"] },
  { id: "pack-manager-leadership", lang: "fr",
    title: "Pack Manager & Leadership",
    blurb: "Soutenir, évaluer juste, accompagner un retour, prévenir les risques psychosociaux — 4 guides pour managers. (4 guides · 49€ au lieu de 76€)",
    priceCents: 4900, compareAtCents: 7600, currency: "eur",
    guideIds: ["soutenir-collaborateur-en-difficulte","entretiens-evaluation-equitables","manager-retour-apres-arret","prevenir-risques-psychosociaux"] },
  { id: "pack-couple-lien", lang: "fr",
    title: "Pack Couple & Lien",
    blurb: "Mieux communiquer, sortir de la dépendance affective, surmonter une rupture, gérer la jalousie — 4 guides pour le couple. (4 guides · 49€ au lieu de 76€)",
    priceCents: 4900, compareAtCents: 7600, currency: "eur",
    guideIds: ["communiquer-dans-le-couple","sortir-dependance-affective","surmonter-une-rupture","gerer-la-jalousie"] },
  { id: "pack-se-reconstruire", lang: "fr",
    title: "Pack Se reconstruire",
    blurb: "Reconnaître le contrôle coercitif, sortir du gaslighting, faire face au harcèlement moral, se reconstruire après une relation toxique — 4 guides. (4 guides · 49€ au lieu de 76€)",
    priceCents: 4900, compareAtCents: 7600, currency: "eur",
    guideIds: ["reconnaitre-controle-coercitif","sortir-du-gaslighting","harcelement-moral-au-travail","se-reconstruire-apres-relation-toxique"] },
  { id: "pack-intimite-sexualite", lang: "fr",
    title: "Pack Intimité & Sexualité (18+)",
    blurb: "Raviver le désir, parler de sexe sans tabou, dépasser la honte, gérer des désirs désaccordés — 4 guides pour l'intimité du couple. (4 guides · 49€ au lieu de 76€)",
    priceCents: 4900, compareAtCents: 7600, currency: "eur",
    guideIds: ["raviver-le-desir","parler-de-sexe-sans-tabou","depasser-honte-blocages-sexuels","desirs-desaccordes"] },
  { id: "pack-identite-resilience", lang: "fr",
    title: "Pack Identité & Résilience",
    blurb: "Te reconstruire, déconstruire l'intériorisé, préserver ta santé mentale et ta fierté. (4 guides · 49€ au lieu de 76€)",
    priceCents: 4900, compareAtCents: 7600, currency: "eur",
    guideIds: ["se-reconstruire-face-negrophobie","se-liberer-misogynoir","preserver-sante-mentale-racisme","charge-raciale","developper-resilience-emotionnelle","cultiver-auto-compassion","faire-face-microagressions","naviguer-identite-plurielle","faire-taire-critique-interieur","rebondir-apres-un-echec","croissance-post-traumatique"] },
  // ---------------- EN ----------------
  { id: "pack-career-comeback", lang: "en",
    title: "Career & Comeback Pack",
    blurb: "Change paths, bounce back, get visible and build your network — 4 guides to steer your career. (4 guides · €49 instead of €76)",
    priceCents: 4900, compareAtCents: 7600, currency: "eur",
    guideIds: ["making-a-career-change","bouncing-back-after-a-layoff","building-your-personal-brand","building-your-network"] },
  { id: "pack-confidence-at-work", lang: "en",
    title: "Confidence at Work Pack",
    blurb: "Ease anxiety, speak up, ask for a promotion, manage your time — 4 guides to assert yourself at work. (4 guides · €49 instead of €76)",
    priceCents: 4900, compareAtCents: 7600, currency: "eur",
    guideIds: ["taming-performance-anxiety","public-speaking-at-work","asking-for-a-promotion","managing-time-and-delegating"] },
  { id: "pack-manager-leadership-en", lang: "en",
    title: "Manager & Leadership Pack",
    blurb: "Support, evaluate fairly, manage a return, prevent psychosocial risks — 4 guides for managers. (4 guides · €49 instead of €76)",
    priceCents: 4900, compareAtCents: 7600, currency: "eur",
    guideIds: ["supporting-a-struggling-team-member","fair-performance-reviews","managing-a-return-to-work","preventing-psychosocial-risks"] },
  { id: "pack-couple-connection", lang: "en",
    title: "Couple & Connection Pack",
    blurb: "Communicate better, overcome emotional dependency, get over a breakup, manage jealousy — 4 guides for couples. (4 guides · €49 instead of €76)",
    priceCents: 4900, compareAtCents: 7600, currency: "eur",
    guideIds: ["communicating-in-your-relationship","overcoming-emotional-dependency","getting-over-a-breakup","managing-jealousy"] },
  { id: "pack-rebuild", lang: "en",
    title: "Rebuild Yourself Pack",
    blurb: "Recognize coercive control, recover from gaslighting, face workplace harassment, rebuild after a toxic relationship — 4 guides. (4 guides · €49 instead of €76)",
    priceCents: 4900, compareAtCents: 7600, currency: "eur",
    guideIds: ["recognizing-coercive-control","recovering-from-gaslighting","psychological-harassment-at-work","rebuilding-after-a-toxic-relationship"] },
  { id: "pack-intimacy-sexuality", lang: "en",
    title: "Intimacy & Sexuality Pack (18+)",
    blurb: "Rekindle desire, talk about sex without taboo, overcome shame, handle mismatched desire — 4 guides for couple intimacy. (4 guides · €49 instead of €76)",
    priceCents: 4900, compareAtCents: 7600, currency: "eur",
    guideIds: ["rekindling-desire-in-your-relationship","talking-about-sex-without-taboo","overcoming-shame-and-sexual-blocks","mismatched-desire-in-couples"] },
  { id: "pack-identity-resilience", lang: "en",
    title: "Identity & Resilience Pack",
    blurb: "Rebuild yourself, unlearn the internalized, protect your mental health and your pride. (4 guides · €49 instead of €76)",
    priceCents: 4900, compareAtCents: 7600, currency: "eur",
    guideIds: ["healing-from-anti-black-racism","freeing-yourself-from-misogynoir","protecting-your-mental-health-from-racism","racial-fatigue","building-emotional-resilience","cultivating-self-compassion","coping-with-microaggressions","navigating-a-plural-identity","silencing-your-inner-critic","bouncing-back-from-failure","post-traumatic-growth"] },
  { id: "pack-blessures-interieures", lang: "fr",
    title: "Pack Blessures — parcours complet",
    blurb: "Les 10 guides (Tome 1 + Tome 2) pour les 5 blessures : rejet, abandon, humiliation, trahison, injustice. (10 guides · 79€ au lieu de 190€)",
    priceCents: 7900, compareAtCents: 19000, currency: "eur",
    guideIds: ["guerir-blessure-rejet","guerir-blessure-abandon","guerir-blessure-humiliation","guerir-blessure-trahison","guerir-blessure-injustice","approfondir-blessure-rejet","approfondir-blessure-abandon","approfondir-blessure-humiliation","approfondir-blessure-trahison","approfondir-blessure-injustice"] },
  { id: "pack-inner-wounds", lang: "en",
    title: "Inner Wounds — Complete Journey",
    blurb: "All 10 guides (Vol. 1 + Vol. 2) for the 5 wounds: rejection, abandonment, humiliation, betrayal, injustice. (10 guides · €79 instead of €190)",
    priceCents: 7900, compareAtCents: 19000, currency: "eur",
    guideIds: ["healing-the-rejection-wound","healing-the-abandonment-wound","healing-the-humiliation-wound","healing-the-betrayal-wound","healing-the-injustice-wound","deepening-the-rejection-wound","deepening-the-abandonment-wound","deepening-the-humiliation-wound","deepening-the-betrayal-wound","deepening-the-injustice-wound"] },
  // Packs complets par blessure (Tome 1 + Tome 2)
  { id: "pack-blessure-rejet-complet", lang: "fr",
    title: "Pack Rejet complet",
    blurb: "Tome 1 + Tome 2 pour guérir la blessure de rejet : comprendre, puis reparenter et ancrer. (2 guides · 32€ au lieu de 38€)",
    priceCents: 3200, compareAtCents: 3800, currency: "eur",
    guideIds: ["guerir-blessure-rejet","approfondir-blessure-rejet"] },
  { id: "pack-blessure-abandon-complet", lang: "fr",
    title: "Pack Abandon complet",
    blurb: "Tome 1 + Tome 2 pour guérir la blessure d'abandon : comprendre, puis reparenter et ancrer. (2 guides · 32€ au lieu de 38€)",
    priceCents: 3200, compareAtCents: 3800, currency: "eur",
    guideIds: ["guerir-blessure-abandon","approfondir-blessure-abandon"] },
  { id: "pack-blessure-humiliation-complet", lang: "fr",
    title: "Pack Humiliation complet",
    blurb: "Tome 1 + Tome 2 pour guérir la blessure d'humiliation : comprendre, puis reparenter et ancrer. (2 guides · 32€ au lieu de 38€)",
    priceCents: 3200, compareAtCents: 3800, currency: "eur",
    guideIds: ["guerir-blessure-humiliation","approfondir-blessure-humiliation"] },
  { id: "pack-blessure-trahison-complet", lang: "fr",
    title: "Pack Trahison complet",
    blurb: "Tome 1 + Tome 2 pour guérir la blessure de trahison : comprendre, puis reparenter et ancrer. (2 guides · 32€ au lieu de 38€)",
    priceCents: 3200, compareAtCents: 3800, currency: "eur",
    guideIds: ["guerir-blessure-trahison","approfondir-blessure-trahison"] },
  { id: "pack-blessure-injustice-complet", lang: "fr",
    title: "Pack Injustice complet",
    blurb: "Tome 1 + Tome 2 pour guérir la blessure d'injustice : comprendre, puis reparenter et ancrer. (2 guides · 32€ au lieu de 38€)",
    priceCents: 3200, compareAtCents: 3800, currency: "eur",
    guideIds: ["guerir-blessure-injustice","approfondir-blessure-injustice"] },
  { id: "pack-rejection-wound-complete", lang: "en",
    title: "Rejection Wound Complete Pack",
    blurb: "Vol. 1 + Vol. 2 to heal the rejection wound: understand, then reparent and anchor. (2 guides · €32 instead of €38)",
    priceCents: 3200, compareAtCents: 3800, currency: "eur",
    guideIds: ["healing-the-rejection-wound","deepening-the-rejection-wound"] },
  { id: "pack-abandonment-wound-complete", lang: "en",
    title: "Abandonment Wound Complete Pack",
    blurb: "Vol. 1 + Vol. 2 to heal the abandonment wound: understand, then reparent and anchor. (2 guides · €32 instead of €38)",
    priceCents: 3200, compareAtCents: 3800, currency: "eur",
    guideIds: ["healing-the-abandonment-wound","deepening-the-abandonment-wound"] },
  { id: "pack-humiliation-wound-complete", lang: "en",
    title: "Humiliation Wound Complete Pack",
    blurb: "Vol. 1 + Vol. 2 to heal the humiliation wound: understand, then reparent and anchor. (2 guides · €32 instead of €38)",
    priceCents: 3200, compareAtCents: 3800, currency: "eur",
    guideIds: ["healing-the-humiliation-wound","deepening-the-humiliation-wound"] },
  { id: "pack-betrayal-wound-complete", lang: "en",
    title: "Betrayal Wound Complete Pack",
    blurb: "Vol. 1 + Vol. 2 to heal the betrayal wound: understand, then reparent and anchor. (2 guides · €32 instead of €38)",
    priceCents: 3200, compareAtCents: 3800, currency: "eur",
    guideIds: ["healing-the-betrayal-wound","deepening-the-betrayal-wound"] },
  { id: "pack-injustice-wound-complete", lang: "en",
    title: "Injustice Wound Complete Pack",
    blurb: "Vol. 1 + Vol. 2 to heal the injustice wound: understand, then reparent and anchor. (2 guides · €32 instead of €38)",
    priceCents: 3200, compareAtCents: 3800, currency: "eur",
    guideIds: ["healing-the-injustice-wound","deepening-the-injustice-wound"] },
  { id: "pack-relations-plurielles", lang: "fr",
    title: "Pack Relations plurielles — collection complète",
    blurb: "Les 13 guides de la collection : polygamie, co-épouses, partage, enfants, foi, belle-famille, communauté, indépendance. (13 guides · 89€ au lieu de 247€)",
    priceCents: 8900, compareAtCents: 24700, currency: "eur",
    guideIds: ["vivre-la-polygamie","coepouses-apaiser-rivalites","partager-lepoux","enfants-dans-la-polygamie","quand-lepoux-en-prefere-une-autre","te-sentir-desirable","inegalites-et-tensions","garder-lien-fort-mari","poids-belle-famille","etre-premiere-epouse","regard-communaute","polygamie-et-foi","dependance-economique-autonomie"] },
  { id: "pack-plural-relationships", lang: "en",
    title: "Plural Relationships — Complete Collection",
    blurb: "All 13 guides: polygamy, co-wives, sharing, children, faith, in-laws, community, independence. (13 guides · €89 instead of €247)",
    priceCents: 8900, compareAtCents: 24700, currency: "eur",
    guideIds: ["navigating-polygamy","co-wives-easing-rivalry","sharing-your-husband","children-in-polygamy","when-your-husband-prefers-another","feeling-desirable-again","inequalities-and-tensions","staying-close-to-your-husband","the-weight-of-in-laws","being-the-first-wife","facing-community-judgment","polygamy-and-faith","economic-dependence-and-autonomy"] },
] as const;
