// Packs (bundles) : plusieurs guides vendus ensemble, 1 seul paiement Stripe livrant TOUS les PDF.
// Upload dans lib/bundles.ts. Câblage via etape18.txt.
// IMPORTANT : un pack ne fonctionne que si TOUS ses guideIds sont déjà live dans GUIDES.
// guideIds FR = ids des guides FR ; guideIds EN = ids des guides EN.
export const BUNDLES = [
  // ---------------- FR ----------------
  { id: "pack-carriere-rebond", lang: "fr",
    title: "Pack Carrière & Rebond",
    blurb: "Changer de voie, rebondir, te rendre visible et tisser ton réseau — 4 guides pour piloter ta carrière. (4 guides · 49€ au lieu de 76€)",
    priceCents: 4900, compareAtCents: 7600, currency: "eur",
    guideIds: ["reussir-sa-reconversion","rebondir-apres-licenciement","soigner-son-personal-branding","developper-son-reseau"] },
  { id: "pack-confiance-au-travail", lang: "fr",
    title: "Pack Confiance au travail",
    blurb: "Apaiser l'anxiété, prendre la parole, demander une promotion, gérer ton temps — 4 guides pour t'affirmer au travail. (4 guides · 49€ au lieu de 76€)",
    priceCents: 4900, compareAtCents: 7600, currency: "eur",
    guideIds: ["anxiete-de-performance","prendre-la-parole-en-public","demander-une-promotion","gerer-son-temps-deleguer"] },
  { id: "pack-manager-leadership", lang: "fr",
    title: "Pack Manager & Leadership",
    blurb: "Soutenir, évaluer juste, accompagner un retour, prévenir les risques psychosociaux — 4 guides pour managers. (4 guides · 49€ au lieu de 76€)",
    priceCents: 4900, compareAtCents: 7600, currency: "eur",
    guideIds: ["soutenir-collaborateur-en-difficulte","entretiens-evaluation-equitables","manager-retour-apres-arret","prevenir-risques-psychosociaux"] },
  { id: "pack-couple-lien", lang: "fr",
    title: "Pack Couple & Lien",
    blurb: "Mieux communiquer, sortir de la dépendance affective, surmonter une rupture, gérer la jalousie — 4 guides pour le couple. (4 guides · 49€ au lieu de 76€)",
    priceCents: 4900, compareAtCents: 7600, currency: "eur",
    guideIds: ["communiquer-dans-le-couple","sortir-dependance-affective","surmonter-une-rupture","gerer-la-jalousie"] },
  { id: "pack-se-reconstruire", lang: "fr",
    title: "Pack Se reconstruire",
    blurb: "Reconnaître le contrôle coercitif, sortir du gaslighting, faire face au harcèlement moral, se reconstruire après une relation toxique — 4 guides. (4 guides · 49€ au lieu de 76€)",
    priceCents: 4900, compareAtCents: 7600, currency: "eur",
    guideIds: ["reconnaitre-controle-coercitif","sortir-du-gaslighting","harcelement-moral-au-travail","se-reconstruire-apres-relation-toxique"] },
  { id: "pack-intimite-sexualite", lang: "fr",
    title: "Pack Intimité & Sexualité — collection complète (18+)",
    blurb: "Les 18 guides : désir, fantasmes, échangisme, anal, fellation, plaisir féminin, solo, préliminaires, sextoys, cunnilingus, BDSM, vaginisme, ménopause, érection, éjaculation, tantrisme, après accouchement. (18 guides · 119€ au lieu de 342€)",
    priceCents: 11900, compareAtCents: 34200, currency: "eur",
    guideIds: ["communiquer-desirs-limites","raviver-le-desir","explorer-ses-fantasmes","echangisme-a-deux","plaisir-anal-en-confiance","fellation-sans-tabou","plaisir-feminin-orgasme","plaisir-solo-masturbation","preliminaires-et-lenteur","sextoys-oser-les-integrer","cunnilingus-sans-tabou","bdsm-jeux-de-pouvoir","comprendre-le-vaginisme","sexualite-apres-menopause","troubles-erection-partenaire","ejaculation-precoce-a-deux","decouvrir-le-tantrisme","sexualite-apres-accouchement"] },
  { id: "pack-dating-cas-particuliers", lang: "fr",
    title: "Pack — Cas particuliers & situations",
    blurb: "Les 7 cas : écart d'âge, aimer un homme plus jeune, dater avec des enfants, dating & traumas, premier baiser, premier rapport (18+), qui paie. (7 guides · 89€ au lieu de 133€)",
    priceCents: 8900, compareAtCents: 13300, currency: "eur",
    guideIds: ["relations-ecart-d-age","femme-cougar","dater-avec-des-enfants","dating-et-traumas","le-premier-baiser","le-premier-rapport-sexuel","qui-paie-au-rendez-vous"] },
  { id: "pack-ou-rencontrer", lang: "fr",
    title: "Pack — Où & comment rencontrer",
    blurb: "Les 8 contextes : hors des applis, sur les applis, réseaux sociaux, travail, speed dating, soirée, vacances, d'ami·e à amoureux·se. (8 guides · 99€ au lieu de 152€)",
    priceCents: 9900, compareAtCents: 15200, currency: "eur",
    guideIds: ["rencontrer-hors-des-applis","reussir-sur-les-applis","rencontrer-sur-les-reseaux-sociaux","amour-au-travail","le-speed-dating","rencontrer-en-soiree","amour-de-vacances","d-ami-a-amoureux"] },
  { id: "pack-parcours-dating", lang: "fr",
    title: "Parcours Dating — de la rencontre à l'engagement",
    blurb: "Les 6 étapes : savoir ce que tu cherches, oser te montrer, le premier RDV, créer du lien, décrypter les signaux, définir la relation. (6 guides · 89€ au lieu de 114€)",
    priceCents: 8900, compareAtCents: 11400, currency: "eur",
    guideIds: ["savoir-ce-que-tu-cherches","oser-te-montrer-rencontrer","le-premier-rendez-vous","creer-du-lien-sans-te-perdre","decrypter-les-signaux","definir-la-relation-engagement"] },
  { id: "pack-identite-resilience", lang: "fr",
    title: "Pack Identité & Résilience",
    blurb: "Te reconstruire, déconstruire l'intériorisé, préserver ta santé mentale et ta fierté. (4 guides · 49€ au lieu de 76€)",
    priceCents: 4900, compareAtCents: 7600, currency: "eur",
    guideIds: ["se-reconstruire-face-negrophobie","se-liberer-misogynoir","preserver-sante-mentale-racisme","charge-raciale","developper-resilience-emotionnelle","cultiver-auto-compassion","faire-face-microagressions","naviguer-identite-plurielle","faire-taire-critique-interieur","rebondir-apres-un-echec","croissance-post-traumatique"] },
  // ---------------- EN ----------------
  { id: "pack-career-comeback", lang: "en",
    title: "Career & Comeback Pack",
    blurb: "Change paths, bounce back, get visible and build your network — 4 guides to steer your career. (4 guides · €49 instead of €76)",
    priceCents: 4900, compareAtCents: 7600, currency: "eur",
    guideIds: ["making-a-career-change","bouncing-back-after-a-layoff","building-your-personal-brand","building-your-network"] },
  { id: "pack-confidence-at-work", lang: "en",
    title: "Confidence at Work Pack",
    blurb: "Ease anxiety, speak up, ask for a promotion, manage your time — 4 guides to assert yourself at work. (4 guides · €49 instead of €76)",
    priceCents: 4900, compareAtCents: 7600, currency: "eur",
    guideIds: ["taming-performance-anxiety","public-speaking-at-work","asking-for-a-promotion","managing-time-and-delegating"] },
  { id: "pack-manager-leadership-en", lang: "en",
    title: "Manager & Leadership Pack",
    blurb: "Support, evaluate fairly, manage a return, prevent psychosocial risks — 4 guides for managers. (4 guides · €49 instead of €76)",
    priceCents: 4900, compareAtCents: 7600, currency: "eur",
    guideIds: ["supporting-a-struggling-team-member","fair-performance-reviews","managing-a-return-to-work","preventing-psychosocial-risks"] },
  { id: "pack-couple-connection", lang: "en",
    title: "Couple & Connection Pack",
    blurb: "Communicate better, overcome emotional dependency, get over a breakup, manage jealousy — 4 guides for couples. (4 guides · €49 instead of €76)",
    priceCents: 4900, compareAtCents: 7600, currency: "eur",
    guideIds: ["communicating-in-your-relationship","overcoming-emotional-dependency","getting-over-a-breakup","managing-jealousy"] },
  { id: "pack-rebuild", lang: "en",
    title: "Rebuild Yourself Pack",
    blurb: "Recognize coercive control, recover from gaslighting, face workplace harassment, rebuild after a toxic relationship — 4 guides. (4 guides · €49 instead of €76)",
    priceCents: 4900, compareAtCents: 7600, currency: "eur",
    guideIds: ["recognizing-coercive-control","recovering-from-gaslighting","psychological-harassment-at-work","rebuilding-after-a-toxic-relationship"] },
  { id: "pack-intimacy-sexuality", lang: "en",
    title: "Intimacy & Sexuality — Complete Collection (18+)",
    blurb: "18 guides: desire, fantasies, swinging, anal, oral, female pleasure, solo, foreplay, sex toys, cunnilingus, BDSM, vaginismus, menopause, erection, ejaculation, tantra, after childbirth. (18 guides · €119 instead of €342)",
    priceCents: 11900, compareAtCents: 34200, currency: "eur",
    guideIds: ["communicating-desires-and-limits","reviving-desire-in-your-couple","exploring-your-fantasies","swinging-as-a-couple","anal-pleasure-with-confidence","fellatio-without-taboo","female-pleasure-and-orgasm","solo-pleasure-masturbation","foreplay-and-slowness","sex-toys-bringing-them-in","cunnilingus-without-taboo","bdsm-power-play-with-confidence","understanding-vaginismus","sexuality-after-menopause","partners-erection-difficulties","premature-ejaculation-together","discovering-tantra","sexuality-after-childbirth"] },
  { id: "pack-dating-special-cases", lang: "en",
    title: "Pack — Special Cases & Situations",
    blurb: "All 7 cases: age gap, dating a younger man, dating with children, dating & trauma, first kiss, first time (18+), who pays. (7 guides · €89 instead of €133)",
    priceCents: 8900, compareAtCents: 13300, currency: "eur",
    guideIds: ["age-gap-relationships","dating-a-younger-man","dating-with-children","dating-with-trauma","the-first-kiss","the-first-time","who-pays-on-a-date"] },
  { id: "pack-where-to-meet", lang: "en",
    title: "Pack — Where & How to Meet",
    blurb: "All 8 contexts: offline, dating apps, social media, at work, speed dating, at a party, holiday romance, from friend to lover. (8 guides · €99 instead of €152)",
    priceCents: 9900, compareAtCents: 15200, currency: "eur",
    guideIds: ["meeting-offline","succeeding-on-dating-apps","meeting-on-social-media","love-at-work","speed-dating","meeting-at-a-party","holiday-romance","from-friend-to-lover"] },
  { id: "pack-dating-journey", lang: "en",
    title: "Dating Journey — From First Encounter to Commitment",
    blurb: "All 6 steps: know what you want, put yourself out there, the first date, build connection, read the signals, define the relationship. (6 guides · €89 instead of €114)",
    priceCents: 8900, compareAtCents: 11400, currency: "eur",
    guideIds: ["know-what-you-truly-want","putting-yourself-out-there","the-first-date","building-connection-without-losing-yourself","reading-the-signals","defining-the-relationship"] },
  { id: "pack-identity-resilience", lang: "en",
    title: "Identity & Resilience Pack",
    blurb: "Rebuild yourself, unlearn the internalized, protect your mental health and your pride. (4 guides · €49 instead of €76)",
    priceCents: 4900, compareAtCents: 7600, currency: "eur",
    guideIds: ["healing-from-anti-black-racism","freeing-yourself-from-misogynoir","protecting-your-mental-health-from-racism","racial-fatigue","building-emotional-resilience","cultivating-self-compassion","coping-with-microaggressions","navigating-a-plural-identity","silencing-your-inner-critic","bouncing-back-from-failure","post-traumatic-growth"] },
  { id: "pack-blessures-interieures", lang: "fr",
    title: "Pack Blessures — parcours complet",
    blurb: "Les 10 guides (Tome 1 + Tome 2) pour les 5 blessures : rejet, abandon, humiliation, trahison, injustice. (10 guides · 79€ au lieu de 190€)",
    priceCents: 7900, compareAtCents: 19000, currency: "eur",
    guideIds: ["guerir-blessure-rejet","guerir-blessure-abandon","guerir-blessure-humiliation","guerir-blessure-trahison","guerir-blessure-injustice","approfondir-blessure-rejet","approfondir-blessure-abandon","approfondir-blessure-humiliation","approfondir-blessure-trahison","approfondir-blessure-injustice"] },
  { id: "pack-inner-wounds", lang: "en",
    title: "Inner Wounds — Complete Journey",
    blurb: "All 10 guides (Vol. 1 + Vol. 2) for the 5 wounds: rejection, abandonment, humiliation, betrayal, injustice. (10 guides · €79 instead of €190)",
    priceCents: 7900, compareAtCents: 19000, currency: "eur",
    guideIds: ["healing-the-rejection-wound","healing-the-abandonment-wound","healing-the-humiliation-wound","healing-the-betrayal-wound","healing-the-injustice-wound","deepening-the-rejection-wound","deepening-the-abandonment-wound","deepening-the-humiliation-wound","deepening-the-betrayal-wound","deepening-the-injustice-wound"] },
  // Packs complets par blessure (Tome 1 + Tome 2)
  { id: "pack-blessure-rejet-complet", lang: "fr",
    title: "Pack Rejet complet",
    blurb: "Tome 1 + Tome 2 pour guérir la blessure de rejet : comprendre, puis reparenter et ancrer. (2 guides · 32€ au lieu de 38€)",
    priceCents: 3200, compareAtCents: 3800, currency: "eur",
    guideIds: ["guerir-blessure-rejet","approfondir-blessure-rejet"] },
  { id: "pack-blessure-abandon-complet", lang: "fr",
    title: "Pack Abandon complet",
    blurb: "Tome 1 + Tome 2 pour guérir la blessure d'abandon : comprendre, puis reparenter et ancrer. (2 guides · 32€ au lieu de 38€)",
    priceCents: 3200, compareAtCents: 3800, currency: "eur",
    guideIds: ["guerir-blessure-abandon","approfondir-blessure-abandon"] },
  { id: "pack-blessure-humiliation-complet", lang: "fr",
    title: "Pack Humiliation complet",
    blurb: "Tome 1 + Tome 2 pour guérir la blessure d'humiliation : comprendre, puis reparenter et ancrer. (2 guides · 32€ au lieu de 38€)",
    priceCents: 3200, compareAtCents: 3800, currency: "eur",
    guideIds: ["guerir-blessure-humiliation","approfondir-blessure-humiliation"] },
  { id: "pack-blessure-trahison-complet", lang: "fr",
    title: "Pack Trahison complet",
    blurb: "Tome 1 + Tome 2 pour guérir la blessure de trahison : comprendre, puis reparenter et ancrer. (2 guides · 32€ au lieu de 38€)",
    priceCents: 3200, compareAtCents: 3800, currency: "eur",
    guideIds: ["guerir-blessure-trahison","approfondir-blessure-trahison"] },
  { id: "pack-blessure-injustice-complet", lang: "fr",
    title: "Pack Injustice complet",
    blurb: "Tome 1 + Tome 2 pour guérir la blessure d'injustice : comprendre, puis reparenter et ancrer. (2 guides · 32€ au lieu de 38€)",
    priceCents: 3200, compareAtCents: 3800, currency: "eur",
    guideIds: ["guerir-blessure-injustice","approfondir-blessure-injustice"] },
  { id: "pack-rejection-wound-complete", lang: "en",
    title: "Rejection Wound Complete Pack",
    blurb: "Vol. 1 + Vol. 2 to heal the rejection wound: understand, then reparent and anchor. (2 guides · €32 instead of €38)",
    priceCents: 3200, compareAtCents: 3800, currency: "eur",
    guideIds: ["healing-the-rejection-wound","deepening-the-rejection-wound"] },
  { id: "pack-abandonment-wound-complete", lang: "en",
    title: "Abandonment Wound Complete Pack",
    blurb: "Vol. 1 + Vol. 2 to heal the abandonment wound: understand, then reparent and anchor. (2 guides · €32 instead of €38)",
    priceCents: 3200, compareAtCents: 3800, currency: "eur",
    guideIds: ["healing-the-abandonment-wound","deepening-the-abandonment-wound"] },
  { id: "pack-humiliation-wound-complete", lang: "en",
    title: "Humiliation Wound Complete Pack",
    blurb: "Vol. 1 + Vol. 2 to heal the humiliation wound: understand, then reparent and anchor. (2 guides · €32 instead of €38)",
    priceCents: 3200, compareAtCents: 3800, currency: "eur",
    guideIds: ["healing-the-humiliation-wound","deepening-the-humiliation-wound"] },
  { id: "pack-betrayal-wound-complete", lang: "en",
    title: "Betrayal Wound Complete Pack",
    blurb: "Vol. 1 + Vol. 2 to heal the betrayal wound: understand, then reparent and anchor. (2 guides · €32 instead of €38)",
    priceCents: 3200, compareAtCents: 3800, currency: "eur",
    guideIds: ["healing-the-betrayal-wound","deepening-the-betrayal-wound"] },
  { id: "pack-injustice-wound-complete", lang: "en",
    title: "Injustice Wound Complete Pack",
    blurb: "Vol. 1 + Vol. 2 to heal the injustice wound: understand, then reparent and anchor. (2 guides · €32 instead of €38)",
    priceCents: 3200, compareAtCents: 3800, currency: "eur",
    guideIds: ["healing-the-injustice-wound","deepening-the-injustice-wound"] },
  { id: "pack-relations-plurielles", lang: "fr",
    title: "Pack Relations plurielles — collection complète",
    blurb: "Les 13 guides de la collection : polygamie, co-épouses, partage, enfants, foi, belle-famille, communauté, indépendance. (13 guides · 89€ au lieu de 247€)",
    priceCents: 8900, compareAtCents: 24700, currency: "eur",
    guideIds: ["vivre-la-polygamie","coepouses-apaiser-rivalites","partager-lepoux","enfants-dans-la-polygamie","quand-lepoux-en-prefere-une-autre","te-sentir-desirable","inegalites-et-tensions","garder-lien-fort-mari","poids-belle-famille","etre-premiere-epouse","regard-communaute","polygamie-et-foi","dependance-economique-autonomie"] },
  { id: "pack-plural-relationships", lang: "en",
    title: "Plural Relationships — Complete Collection",
    blurb: "All 13 guides: polygamy, co-wives, sharing, children, faith, in-laws, community, independence. (13 guides · €89 instead of €247)",
    priceCents: 8900, compareAtCents: 24700, currency: "eur",
    guideIds: ["navigating-polygamy","co-wives-easing-rivalry","sharing-your-husband","children-in-polygamy","when-your-husband-prefers-another","feeling-desirable-again","inequalities-and-tensions","staying-close-to-your-husband","the-weight-of-in-laws","being-the-first-wife","facing-community-judgment","polygamy-and-faith","economic-dependence-and-autonomy"] },
  { id: "pack-createur-influence", lang: "fr",
    title: "Pack — Créateur·rice & Influence",
    blurb: "Les 30 guides de la collection : démarrer & tenir, regard des autres, présence & identité, crises, rapport à soi & argent. (30 guides · 199 € au lieu de 570 €)",
    priceCents: 19900, compareAtCents: 57000, currency: "eur",
    guideIds: ["oser-te-montrer-camera","syndrome-imposteur-createur","trouver-ta-niche-voix","regularite-sans-tepuiser","burn-out-createur","solitude-du-createur","gerer-la-comparaison","encaisser-haters-critiques","exposition-et-vie-privee","jugement-de-tes-proches","garder-ta-liberte-creative","decalage-image-vraie-vie","charisme-face-camera","trouver-ton-personnage","raconter-ta-vie-sans-te-mettre-a-nu","couple-d-influenceurs","creer-en-famille-proteger-enfants","dire-non-sans-culpabiliser","survivre-au-bad-buzz","gerer-le-cyberharcelement","encaisser-un-flop","assumer-et-reparer-une-erreur","la-peur-du-succes","passer-un-palier","estime-qui-ne-depend-pas-des-likes","oser-monetiser-sans-culpabilite","de-la-passion-au-metier","addiction-a-ton-telephone","la-depression-du-createur","le-decalage-de-la-reussite"] },
  { id: "pack-creator-influence", lang: "en",
    title: "Pack — Creator & Influence",
    blurb: "All 30 guides: starting out, gaze of others, presence & identity, crises, self & money. (30 guides · €199 instead of €570)",
    priceCents: 19900, compareAtCents: 57000, currency: "eur",
    guideIds: ["daring-to-show-up-on-camera","creator-impostor-syndrome","finding-your-niche-and-voice","consistency-without-burning-out","content-creator-burnout","the-creator-loneliness","handling-comparison","handling-criticism-and-haters","exposure-and-privacy","loved-ones-judgment","keeping-your-creative-freedom","online-image-vs-real-life","charisma-on-camera","finding-your-persona","personal-storytelling-with-limits","influencer-couple","family-content-protecting-your-kids","saying-no-without-guilt","surviving-a-bad-buzz","handling-cyberbullying","handling-a-public-flop","owning-and-repairing-a-mistake","the-fear-of-success","reaching-a-new-level","self-esteem-beyond-likes","monetizing-without-guilt","from-passion-to-profession","phone-addiction","creator-depression","the-success-letdown"] },
  { id: "pack-heritage-transmission", lang: "fr",
    title: "Pack — Héritage & Transmission",
    blurb: "Les 8 guides de la collection : trauma transgénérationnel, épigénétique, secrets de famille, briser le cycle, mémoires, guérir l'héritage, esclavage & colonisation, pauvreté. (8 guides · 119 € au lieu de 152 €)",
    priceCents: 11900, compareAtCents: 15200, currency: "eur",
    guideIds: ["trauma-transgenerationnel","epigenetique-du-trauma","secrets-et-non-dits-de-famille","briser-le-cycle","memoires-traumatiques","guerir-l-heritage","trauma-esclavage-colonisation","cycle-de-pauvrete-transgenerationnel"] },
  { id: "pack-legacy-transmission", lang: "en",
    title: "Pack — Legacy & Transmission",
    blurb: "All 8 guides: transgenerational trauma, epigenetics, family secrets, breaking the cycle, traumatic memories, healing, slavery & colonization, poverty cycle. (8 guides · €119 instead of €152)",
    priceCents: 11900, compareAtCents: 15200, currency: "eur",
    guideIds: ["transgenerational-trauma","the-epigenetics-of-trauma","family-secrets-and-silences","breaking-the-cycle","traumatic-memories","healing-your-inheritance","slavery-and-colonial-trauma","breaking-the-poverty-cycle"] },
] as const;
