// Packs (bundles) : plusieurs guides vendus ensemble, 1 seul paiement Stripe livrant TOUS les PDF.
// Upload dans lib/bundles.ts. Câblage via etape18.txt.
// IMPORTANT : un pack ne fonctionne que si TOUS ses guideIds sont déjà live dans GUIDES.
// guideIds FR = ids des guides FR ; guideIds EN = ids des guides EN.
export const BUNDLES = [
  // ---------------- FR ----------------
  { id: "pack-carriere-rebond", lang: "fr",
    title: "Pack Carrière & Rebond",
    blurb: "Changer de voie, rebondir, te rendre visible et tisser ton réseau — 4 guides pour piloter ta carrière. (4 guides · 49€ au lieu de 76€)",
    priceCents: 4900, compareAtCents: 7600, currency: "eur",
    guideIds: ["reussir-sa-reconversion","rebondir-apres-licenciement","soigner-son-personal-branding","developper-son-reseau"] },
  { id: "pack-confiance-au-travail", lang: "fr",
    title: "Pack Confiance au travail",
    blurb: "Apaiser l'anxiété, prendre la parole, demander une promotion, gérer ton temps — 4 guides pour t'affirmer au travail. (4 guides · 49€ au lieu de 76€)",
    priceCents: 4900, compareAtCents: 7600, currency: "eur",
    guideIds: ["anxiete-de-performance","prendre-la-parole-en-public","demander-une-promotion","gerer-son-temps-deleguer"] },
  { id: "pack-manager-leadership", lang: "fr",
    title: "Pack Manager & Leadership",
    blurb: "Soutenir, évaluer juste, accompagner un retour, prévenir les risques psychosociaux — 4 guides pour managers. (4 guides · 49€ au lieu de 76€)",
    priceCents: 4900, compareAtCents: 7600, currency: "eur",
    guideIds: ["soutenir-collaborateur-en-difficulte","entretiens-evaluation-equitables","manager-retour-apres-arret","prevenir-risques-psychosociaux"] },
  { id: "pack-couple-lien", lang: "fr",
    title: "Pack Couple & Lien",
    blurb: "Mieux communiquer, sortir de la dépendance affective, surmonter une rupture, gérer la jalousie — 4 guides pour le couple. (4 guides · 49€ au lieu de 76€)",
    priceCents: 4900, compareAtCents: 7600, currency: "eur",
    guideIds: ["communiquer-dans-le-couple","sortir-dependance-affective","surmonter-une-rupture","gerer-la-jalousie"] },
  { id: "pack-se-reconstruire", lang: "fr",
    title: "Pack Se reconstruire",
    blurb: "Reconnaître le contrôle coercitif, sortir du gaslighting, faire face au harcèlement moral, se reconstruire après une relation toxique — 4 guides. (4 guides · 49€ au lieu de 76€)",
    priceCents: 4900, compareAtCents: 7600, currency: "eur",
    guideIds: ["reconnaitre-controle-coercitif","sortir-du-gaslighting","harcelement-moral-au-travail","se-reconstruire-apres-relation-toxique"] },
  { id: "pack-intimite-sexualite", lang: "fr",
    title: "Pack Intimité & Sexualité (18+)",
    blurb: "Raviver le désir, parler de sexe sans tabou, dépasser la honte, gérer des désirs désaccordés — 4 guides pour l'intimité du couple. (4 guides · 49€ au lieu de 76€)",
    priceCents: 4900, compareAtCents: 7600, currency: "eur",
    guideIds: ["raviver-le-desir","parler-de-sexe-sans-tabou","depasser-honte-blocages-sexuels","desirs-desaccordes"] },
  // ---------------- EN ----------------
  { id: "pack-career-comeback", lang: "en",
    title: "Career & Comeback Pack",
    blurb: "Change paths, bounce back, get visible and build your network — 4 guides to steer your career. (4 guides · €49 instead of €76)",
    priceCents: 4900, compareAtCents: 7600, currency: "eur",
    guideIds: ["making-a-career-change","bouncing-back-after-a-layoff","building-your-personal-brand","building-your-network"] },
  { id: "pack-confidence-at-work", lang: "en",
    title: "Confidence at Work Pack",
    blurb: "Ease anxiety, speak up, ask for a promotion, manage your time — 4 guides to assert yourself at work. (4 guides · €49 instead of €76)",
    priceCents: 4900, compareAtCents: 7600, currency: "eur",
    guideIds: ["taming-performance-anxiety","public-speaking-at-work","asking-for-a-promotion","managing-time-and-delegating"] },
  { id: "pack-manager-leadership-en", lang: "en",
    title: "Manager & Leadership Pack",
    blurb: "Support, evaluate fairly, manage a return, prevent psychosocial risks — 4 guides for managers. (4 guides · €49 instead of €76)",
    priceCents: 4900, compareAtCents: 7600, currency: "eur",
    guideIds: ["supporting-a-struggling-team-member","fair-performance-reviews","managing-a-return-to-work","preventing-psychosocial-risks"] },
  { id: "pack-couple-connection", lang: "en",
    title: "Couple & Connection Pack",
    blurb: "Communicate better, overcome emotional dependency, get over a breakup, manage jealousy — 4 guides for couples. (4 guides · €49 instead of €76)",
    priceCents: 4900, compareAtCents: 7600, currency: "eur",
    guideIds: ["communicating-in-your-relationship","overcoming-emotional-dependency","getting-over-a-breakup","managing-jealousy"] },
  { id: "pack-rebuild", lang: "en",
    title: "Rebuild Yourself Pack",
    blurb: "Recognize coercive control, recover from gaslighting, face workplace harassment, rebuild after a toxic relationship — 4 guides. (4 guides · €49 instead of €76)",
    priceCents: 4900, compareAtCents: 7600, currency: "eur",
    guideIds: ["recognizing-coercive-control","recovering-from-gaslighting","psychological-harassment-at-work","rebuilding-after-a-toxic-relationship"] },
  { id: "pack-intimacy-sexuality", lang: "en",
    title: "Intimacy & Sexuality Pack (18+)",
    blurb: "Rekindle desire, talk about sex without taboo, overcome shame, handle mismatched desire — 4 guides for couple intimacy. (4 guides · €49 instead of €76)",
    priceCents: 4900, compareAtCents: 7600, currency: "eur",
    guideIds: ["rekindling-desire-in-your-relationship","talking-about-sex-without-taboo","overcoming-shame-and-sexual-blocks","mismatched-desire-in-couples"] },
] as const;
