// AUTO-GENERATED — international guides (English + 2 new French). Upload to repo, then wire per Claude Code prompt.
export type IntlGuide = {
  id: string; lang: 'en' | 'fr'; title: string; blurb: string;
  theme: string; pdf: string; priceCents: number; currency: string; bullets: string[];
};
export const INTL_GUIDES: IntlGuide[] = [
  { id: "confidence-self-esteem", lang: "en", title: "Confidence & Self-Esteem", blurb: "Reclaim a steady self-worth, beyond performance.", theme: "Wellbeing", pdf: "/guides/confidence-self-esteem-4-approaches.pdf", priceCents: 999, currency: "eur", bullets: ["Four psychology lenses: psychodynamic, CBT, humanistic, systemic","Psychoeducation + guided written exercises","11-page printable workbook-guide (instant PDF)"] },
  { id: "attachment-styles", lang: "en", title: "Attachment Styles", blurb: "Understand how you love, move toward security.", theme: "Relationships", pdf: "/guides/attachment-styles-4-approaches.pdf", priceCents: 999, currency: "eur", bullets: ["Four psychology lenses: psychodynamic, CBT, humanistic, systemic","Psychoeducation + guided written exercises","11-page printable workbook-guide (instant PDF)"] },
  { id: "healing-from-a-breakup", lang: "en", title: "Healing from a Breakup", blurb: "Move through the grief, come back to yourself.", theme: "Relationships", pdf: "/guides/healing-from-a-breakup-4-approaches.pdf", priceCents: 999, currency: "eur", bullets: ["Four psychology lenses: psychodynamic, CBT, humanistic, systemic","Psychoeducation + guided written exercises","11-page printable workbook-guide (instant PDF)"] },
  { id: "anxiety-negative-thoughts", lang: "en", title: "Anxiety & Negative Thoughts", blurb: "Calm the spiral, soften your inner voice.", theme: "Wellbeing", pdf: "/guides/anxiety-negative-thoughts-4-approaches.pdf", priceCents: 999, currency: "eur", bullets: ["Four psychology lenses: psychodynamic, CBT, humanistic, systemic","Psychoeducation + guided written exercises","11-page printable workbook-guide (instant PDF)"] },
  { id: "thriving-single", lang: "en", title: "Thriving While Single", blurb: "Flourish, partnered or not.", theme: "Relationships", pdf: "/guides/thriving-single-4-approaches.pdf", priceCents: 999, currency: "eur", bullets: ["Four psychology lenses: psychodynamic, CBT, humanistic, systemic","Psychoeducation + guided written exercises","11-page printable workbook-guide (instant PDF)"] },
  { id: "coping-with-loneliness", lang: "en", title: "Coping with Loneliness", blurb: "Reconnect with yourself, then with others.", theme: "Wellbeing", pdf: "/guides/coping-with-loneliness-4-approaches.pdf", priceCents: 999, currency: "eur", bullets: ["Four psychology lenses: psychodynamic, CBT, humanistic, systemic","Psychoeducation + guided written exercises","11-page printable workbook-guide (instant PDF)"] },
  { id: "imposter-syndrome", lang: "en", title: "Imposter Syndrome", blurb: "Own your legitimacy, claim your place.", theme: "Wellbeing", pdf: "/guides/imposter-syndrome-4-approaches.pdf", priceCents: 999, currency: "eur", bullets: ["Four psychology lenses: psychodynamic, CBT, humanistic, systemic","Psychoeducation + guided written exercises","11-page printable workbook-guide (instant PDF)"] },
  { id: "mixed-race-identity", lang: "en", title: "Mixed-Race Identity", blurb: "Belonging to all of who you are.", theme: "Identity & Resilience", pdf: "/guides/mixed-race-identity-4-approaches.pdf", priceCents: 999, currency: "eur", bullets: ["Four psychology lenses: psychodynamic, CBT, humanistic, systemic","Psychoeducation + guided written exercises","11-page printable workbook-guide (instant PDF)"] },
  { id: "intercultural-couples", lang: "en", title: "Intercultural Couples", blurb: "Building unity across your differences.", theme: "Relationships", pdf: "/guides/intercultural-couples-4-approaches.pdf", priceCents: 999, currency: "eur", bullets: ["Four psychology lenses: psychodynamic, CBT, humanistic, systemic","Psychoeducation + guided written exercises","11-page printable workbook-guide (instant PDF)"] },
  { id: "black-couples", lang: "en", title: "Black Love & Resilience", blurb: "Nurturing your bond in a world that tests it.", theme: "Relationships", pdf: "/guides/black-couples-4-approaches.pdf", priceCents: 999, currency: "eur", bullets: ["Four psychology lenses: psychodynamic, CBT, humanistic, systemic","Psychoeducation + guided written exercises","11-page printable workbook-guide (instant PDF)"] },
  { id: "misogynoir", lang: "en", title: "Misogynoir", blurb: "Free yourself from the tropes, reclaim your full humanity.", theme: "Identity & Resilience", pdf: "/guides/misogynoir-4-approaches.pdf", priceCents: 999, currency: "eur", bullets: ["Four psychology lenses: psychodynamic, CBT, humanistic, systemic","Psychoeducation + guided written exercises","11-page printable workbook-guide (instant PDF)"] },
  { id: "racial-fatigue", lang: "en", title: "Racial Fatigue", blurb: "Easing the invisible weight you carry.", theme: "Identity & Resilience", pdf: "/guides/racial-fatigue-4-approaches.pdf", priceCents: 999, currency: "eur", bullets: ["Four psychology lenses: psychodynamic, CBT, humanistic, systemic","Psychoeducation + guided written exercises","11-page printable workbook-guide (instant PDF)"] },
  { id: "everyday-racism", lang: "en", title: "Everyday Racism", blurb: "Protect yourself, keep your dignity and your joy.", theme: "Identity & Resilience", pdf: "/guides/everyday-racism-4-approaches.pdf", priceCents: 999, currency: "eur", bullets: ["Four psychology lenses: psychodynamic, CBT, humanistic, systemic","Psychoeducation + guided written exercises","11-page printable workbook-guide (instant PDF)"] },
  { id: "colorism", lang: "en", title: "Colorism", blurb: "Beyond the hierarchy of shades, love yourself whole.", theme: "Identity & Resilience", pdf: "/guides/colorism-4-approaches.pdf", priceCents: 999, currency: "eur", bullets: ["Four psychology lenses: psychodynamic, CBT, humanistic, systemic","Psychoeducation + guided written exercises","11-page printable workbook-guide (instant PDF)"] },
  { id: "dating-as-a-black-woman", lang: "en", title: "Dating as a Black Woman", blurb: "Choose yourself first, settle for nothing less.", theme: "Relationships", pdf: "/guides/dating-as-a-black-woman-4-approaches.pdf", priceCents: 999, currency: "eur", bullets: ["Four psychology lenses: psychodynamic, CBT, humanistic, systemic","Psychoeducation + guided written exercises","11-page printable workbook-guide (instant PDF)"] },
  { id: "raising-black-children", lang: "en", title: "Raising Black Children", blurb: "Give your child roots, pride, and a village.", theme: "Identity & Resilience", pdf: "/guides/raising-black-children-4-approaches.pdf", priceCents: 999, currency: "eur", bullets: ["Four psychology lenses: psychodynamic, CBT, humanistic, systemic","Psychoeducation + guided written exercises","11-page printable workbook-guide (instant PDF)"] },
  { id: "faith-identity-wellbeing", lang: "en", title: "Faith, Identity & Wellbeing", blurb: "Live your faith and your fullness, without splitting yourself.", theme: "Identity & Resilience", pdf: "/guides/faith-identity-wellbeing-4-approaches.pdf", priceCents: 999, currency: "eur", bullets: ["Four psychology lenses: psychodynamic, CBT, humanistic, systemic","Psychoeducation + guided written exercises","11-page printable workbook-guide (instant PDF)"] },
  { id: "reclaiming-your-sexuality", lang: "en", title: "Reclaiming Your Sexuality", blurb: "Coming back to your desire, your body, your yes and your no.", theme: "Sexuality", pdf: "/guides/reclaiming-your-sexuality-4-approaches.pdf", priceCents: 999, currency: "eur", bullets: ["Four psychology lenses: psychodynamic, CBT, humanistic, systemic","Psychoeducation + guided written exercises","11-page printable workbook-guide (instant PDF)"] },
  { id: "desire-and-intimacy", lang: "en", title: "Desire & Intimacy", blurb: "Reviving connection, honoring your rhythms.", theme: "Sexuality", pdf: "/guides/desire-and-intimacy-4-approaches.pdf", priceCents: 999, currency: "eur", bullets: ["Four psychology lenses: psychodynamic, CBT, humanistic, systemic","Psychoeducation + guided written exercises","11-page printable workbook-guide (instant PDF)"] },
  { id: "sexuality-and-body-image", lang: "en", title: "Sexuality & Body Image", blurb: "Inhabit your body, free from the mirror's verdict.", theme: "Sexuality", pdf: "/guides/sexuality-and-body-image-4-approaches.pdf", priceCents: 999, currency: "eur", bullets: ["Four psychology lenses: psychodynamic, CBT, humanistic, systemic","Psychoeducation + guided written exercises","11-page printable workbook-guide (instant PDF)"] },
  { id: "sexuality-and-black-identity", lang: "en", title: "Sexuality & Black Identity", blurb: "Reclaim your desire, free from the racist gaze.", theme: "Sexuality", pdf: "/guides/sexuality-and-black-identity-4-approaches.pdf", priceCents: 999, currency: "eur", bullets: ["Four psychology lenses: psychodynamic, CBT, humanistic, systemic","Psychoeducation + guided written exercises","11-page printable workbook-guide (instant PDF)"] },
  { id: "black-tax", lang: "en", title: "Black Tax", blurb: "Supporting your people without losing yourself.", theme: "Money", pdf: "/guides/black-tax-4-approaches.pdf", priceCents: 999, currency: "eur", bullets: ["Four psychology lenses: psychodynamic, CBT, humanistic, systemic","Psychoeducation + guided written exercises","11-page printable workbook-guide (instant PDF)"] },
  { id: "money-beliefs", lang: "en", title: "Money Beliefs", blurb: "Rewriting your story with money.", theme: "Money", pdf: "/guides/money-beliefs-4-approaches.pdf", priceCents: 999, currency: "eur", bullets: ["Four psychology lenses: psychodynamic, CBT, humanistic, systemic","Psychoeducation + guided written exercises","11-page printable workbook-guide (instant PDF)"] },
  { id: "abundance-mindset", lang: "en", title: "Abundance Mindset", blurb: "From scarcity fear to openness — honestly.", theme: "Money", pdf: "/guides/abundance-mindset-4-approaches.pdf", priceCents: 999, currency: "eur", bullets: ["Four psychology lenses: psychodynamic, CBT, humanistic, systemic","Psychoeducation + guided written exercises","11-page printable workbook-guide (instant PDF)"] },
  { id: "class-shame", lang: "en", title: "Class Shame", blurb: "Making peace with where you come from.", theme: "Identity & Resilience", pdf: "/guides/class-shame-4-approaches.pdf", priceCents: 999, currency: "eur", bullets: ["Four psychology lenses: psychodynamic, CBT, humanistic, systemic","Psychoeducation + guided written exercises","11-page printable workbook-guide (instant PDF)"] },
  { id: "own-your-worth-and-rates", lang: "en", title: "Own Your Worth & Rates", blurb: "Charging what you're truly worth.", theme: "Money", pdf: "/guides/own-your-worth-and-rates-4-approaches.pdf", priceCents: 999, currency: "eur", bullets: ["Four psychology lenses: psychodynamic, CBT, humanistic, systemic","Psychoeducation + guided written exercises","11-page printable workbook-guide (instant PDF)"] },
  { id: "financial-anxiety", lang: "en", title: "Financial Anxiety", blurb: "Calming the money stress, taking back control.", theme: "Money", pdf: "/guides/financial-anxiety-4-approaches.pdf", priceCents: 999, currency: "eur", bullets: ["Four psychology lenses: psychodynamic, CBT, humanistic, systemic","Psychoeducation + guided written exercises","11-page printable workbook-guide (instant PDF)"] },
  { id: "money-in-relationships", lang: "en", title: "Money in Relationships", blurb: "Talking money as a team, without the fights.", theme: "Money", pdf: "/guides/money-in-relationships-4-approaches.pdf", priceCents: 999, currency: "eur", bullets: ["Four psychology lenses: psychodynamic, CBT, humanistic, systemic","Psychoeducation + guided written exercises","11-page printable workbook-guide (instant PDF)"] },
  { id: "financial-trauma-black-families", lang: "en", title: "Financial Trauma in Black Families", blurb: "Understanding the inheritance, breaking the cycle.", theme: "Money", pdf: "/guides/financial-trauma-black-families-4-approaches.pdf", priceCents: 999, currency: "eur", bullets: ["Four psychology lenses: psychodynamic, CBT, humanistic, systemic","Psychoeducation + guided written exercises","11-page printable workbook-guide (instant PDF)"] },
  { id: "toxic-parents", lang: "en", title: "Toxic Parents", blurb: "Protecting yourself, healing, reclaiming your life.", theme: "Wellbeing", pdf: "/guides/toxic-parents-4-approaches.pdf", priceCents: 999, currency: "eur", bullets: ["Four psychology lenses: psychodynamic, CBT, humanistic, systemic","Psychoeducation + guided written exercises","11-page printable workbook-guide (instant PDF)"] },
  { id: "trauma-financier-familles-noires", lang: "fr", title: "Trauma financier dans les familles noires", blurb: "Comprendre l'héritage, briser le cycle.", theme: "Argent", pdf: "/guides/trauma-financier-familles-noires-4-approches.pdf", priceCents: 999, currency: "eur", bullets: ["Quatre regards : psychodynamique, TCC, humaniste, systémique","Psychoéducation + exercices écrits guidés","Guide-cahier de 11 pages (PDF immédiat)"] },
  { id: "parent-toxique", lang: "fr", title: "Parent toxique", blurb: "Te protéger, guérir, reprendre ta place.", theme: "Résilience", pdf: "/guides/parent-toxique-4-approches.pdf", priceCents: 999, currency: "eur", bullets: ["Quatre regards : psychodynamique, TCC, humaniste, systémique","Psychoéducation + exercices écrits guidés","Guide-cahier de 11 pages (PDF immédiat)"] },
];
export const INTL_GUIDES_BY_ID: Record<string, IntlGuide> = Object.fromEntries(INTL_GUIDES.map(g => [g.id, g]));
