// Copie complète de la page d'accueil, bilingue FR + EN. Upload dans lib/homeCopy.ts.
export const HOME_COPY = {
  fr: {
    meta: {
      title: "PerfectMatch · Transforme tes blessures intérieures",
      description: "Des guides fondés sur la psychologie (TCC + 3 approches) pour transformer tes blessures intérieures — abandon, rejet, manque de confiance — apaiser l'anxiété et les pensées négatives, et avancer plus libre. Mini-guide gratuit.",
    },
    nav: { guides: "Guides", resilience: "Résilience", argent: "Argent", sexualite: "Sexualité", faq: "FAQ", toggle: "EN", toggleHref: "/en" },
    hero: {
      eyebrow: "PerfectMatch · par EvaTalk",
      h1: "Transforme tes blessures intérieures.",
      sub: "Abandon, rejet, sentiment de ne jamais être assez… Des guides fondés sur la psychologie — TCC + 3 approches — pour comprendre ces blessures, apaiser l'anxiété et les pensées négatives, et avancer plus libre. À ton rythme.",
      chips: ["Abandon", "Rejet", "Confiance", "Anxiété", "Relations", "Identité"],
      ctaPrimary: "Reçois le mini-guide gratuit",
      ctaPrimaryHref: "/mini-guide-blessures-interieures.pdf",
      ctaSecondary: "Explore les guides (19€)",
      ctaSecondaryHref: "/bibliotheque",
      trust: "Résultat immédiat · Paiement sécurisé · Psychoéducation & coaching — pas un substitut à une thérapie.",
    },
    themesEyebrow: "POUR QUI",
    themesTitle: "Ce sur quoi tu vas travailler",
    themes: [
      { title: "Anxiété & pensées négatives", desc: "Apaiser le mental, sortir des spirales." },
      { title: "Confiance & estime", desc: "Te réconcilier avec ta valeur." },
      { title: "Relations & attachement", desc: "Aimer sans te perdre." },
      { title: "Identité & résilience", desc: "Te sentir entier·ère, debout." },
      { title: "Argent & schémas", desc: "Déprogrammer la peur et la honte." },
      { title: "Sexualité & corps", desc: "Te réapproprier, en douceur." },
    ],
    howEyebrow: "LA MÉTHODE",
    howTitle: "Comment marchent les guides",
    howIntro: "Chaque guide travaille une blessure sous 4 angles complémentaires, avec des exercices concrets et un cahier de 11 pages à remplir.",
    steps: [
      { n: "1", title: "Choisis ton thème", desc: "Le guide qui résonne avec ta blessure." },
      { n: "2", title: "Lis & écris", desc: "Psychoéducation + exercices guidés." },
      { n: "3", title: "Avance", desc: "Un plan sur 4 semaines, à ton rythme." },
    ],
    approachesTitle: "4 approches de la psychologie",
    approaches: [
      { title: "Psychodynamique", desc: "Comprendre la racine." },
      { title: "TCC", desc: "Apaiser les pensées négatives." },
      { title: "Humaniste", desc: "Te réconcilier avec toi." },
      { title: "Systémique", desc: "Agir sur ton environnement." },
    ],
    ebook: {
      eyebrow: "COMMENCE ICI · GRATUIT",
      title: "Quelle est ta blessure dominante ?",
      body: "Télécharge le mini-guide gratuit : un test rapide pour identifier ta blessure dominante (abandon, rejet, pas-assez…) et savoir exactement par quel guide commencer.",
      cta: "Reçois le mini-guide gratuit",
      ctaHref: "/mini-guide-blessures-interieures.pdf",
      note: "Offert · 7 pages · sans engagement",
    },
    profile: {
      eyebrow: "UN AUTRE OUTIL",
      title: "Découvre ton profil relationnel",
      body: "Un éclairage sur ta façon d'aimer et de fonctionner, fondé sur l'attachement et le Big Five — avec une touche d'astrologie.",
      cta: "Découvrir mon profil",
      ctaHref: "/rapport",
    },
    credibility: {
      eyebrow: "LA PERSONNE DERRIÈRE",
      title: "Par EvaTalk",
      body: "EvaTalk, coach et étudiante en psychologie appliquée, met la psychologie au service de ton mieux-être — avec rigueur et douceur. Une approche fondée sur des cadres reconnus (attachement, TCC, Big Five), jamais sur des promesses magiques.",
    },
    coaching: {
      eyebrow: "ACCOMPAGNEMENT",
      title: "Besoin d'un soutien plus personnel ?",
      body: "Le coaching 1:1 avec EvaTalk t'accompagne en profondeur, à ton rythme.",
      cta: "Réserver un échange",
      ctaHref: "mailto:hawa.diallo1984@gmail.com?subject=Coaching%20avec%20EvaTalk",
    },
    closing: {
      title: "Tes blessures ne te définissent pas.",
      body: "Comprises, elles deviennent ta force. Commence par le mini-guide gratuit.",
      cta: "Reçois le mini-guide gratuit",
      ctaHref: "/mini-guide-blessures-interieures.pdf",
    },
    careNote: "PerfectMatch propose de la psychoéducation et du coaching — pas un substitut à une thérapie. Si tu traverses une période difficile, tu n'es pas seul·e : en Suisse 143 (La Main Tendue), en France 3114, en Belgique 0800 32 123.",
    footer: { tagline: "PerfectMatch · par EvaTalk — transformer tes blessures intérieures, avec la psychologie." },
  },
  en: {
    meta: {
      title: "PerfectMatch · Transform your inner wounds",
      description: "Psychology-based guides (CBT + 3 approaches) to transform your inner wounds — abandonment, rejection, low self-worth — ease anxiety and negative thinking, and move forward freer. Free starter guide.",
    },
    nav: { guides: "Guides", resilience: "Resilience", argent: "Money", sexualite: "Sexuality", faq: "FAQ", toggle: "FR", toggleHref: "/" },
    hero: {
      eyebrow: "PerfectMatch · by EvaTalk",
      h1: "Transform your inner wounds.",
      sub: "Abandonment, rejection, the feeling of never being enough… Psychology-based guides — CBT + 3 approaches — to understand these wounds, ease anxiety and negative thinking, and move forward freer. At your own pace.",
      chips: ["Abandonment", "Rejection", "Self-worth", "Anxiety", "Relationships", "Identity"],
      ctaPrimary: "Get the free starter guide",
      ctaPrimaryHref: "/inner-wounds-starter-guide.pdf",
      ctaSecondary: "Explore the guides (€19)",
      ctaSecondaryHref: "/en/guides",
      trust: "Instant access · Secure payment · Psychoeducation & coaching — not a substitute for therapy.",
    },
    themesEyebrow: "WHO IT'S FOR",
    themesTitle: "What you'll work on",
    themes: [
      { title: "Anxiety & negative thoughts", desc: "Quiet the mind, break the spirals." },
      { title: "Confidence & self-worth", desc: "Make peace with your value." },
      { title: "Relationships & attachment", desc: "Love without losing yourself." },
      { title: "Identity & resilience", desc: "Feel whole, standing tall." },
      { title: "Money & patterns", desc: "Unlearn the fear and the shame." },
      { title: "Sexuality & body", desc: "Reclaim yourself, gently." },
    ],
    howEyebrow: "THE METHOD",
    howTitle: "How the guides work",
    howIntro: "Each guide works a wound through 4 complementary lenses, with concrete exercises and an 11-page workbook to fill in.",
    steps: [
      { n: "1", title: "Choose your theme", desc: "The guide that speaks to your wound." },
      { n: "2", title: "Read & write", desc: "Psychoeducation + guided exercises." },
      { n: "3", title: "Move forward", desc: "A 4-week plan, at your own pace." },
    ],
    approachesTitle: "4 psychology approaches",
    approaches: [
      { title: "Psychodynamic", desc: "Understand the root." },
      { title: "CBT", desc: "Ease the negative thoughts." },
      { title: "Humanistic", desc: "Reconcile with yourself." },
      { title: "Systemic", desc: "Act on your environment." },
    ],
    ebook: {
      eyebrow: "START HERE · FREE",
      title: "What's your core wound?",
      body: "Download the free starter guide: a quick test to spot your core wound (abandonment, rejection, not-enough…) and know exactly which guide to start with.",
      cta: "Get the free starter guide",
      ctaHref: "/inner-wounds-starter-guide.pdf",
      note: "Free · 7 pages · no strings attached",
    },
    profile: {
      eyebrow: "ANOTHER TOOL",
      title: "Discover your relationship profile",
      body: "Insight into how you love and operate, grounded in attachment and the Big Five — with a touch of astrology.",
      cta: "Get my profile",
      ctaHref: "/rapport",
    },
    credibility: {
      eyebrow: "THE PERSON BEHIND IT",
      title: "By EvaTalk",
      body: "EvaTalk, a coach and applied-psychology student, puts psychology to work for your wellbeing — with rigor and warmth. An approach grounded in recognized frameworks (attachment, CBT, Big Five), never in magical promises.",
    },
    coaching: {
      eyebrow: "SUPPORT",
      title: "Want more personal support?",
      body: "1:1 coaching with EvaTalk supports you in depth, at your own pace.",
      cta: "Book a session",
      ctaHref: "mailto:hawa.diallo1984@gmail.com?subject=Coaching%20with%20EvaTalk",
    },
    closing: {
      title: "Your wounds don't define you.",
      body: "Understood, they become your strength. Start with the free starter guide.",
      cta: "Get the free starter guide",
      ctaHref: "/inner-wounds-starter-guide.pdf",
    },
    careNote: "PerfectMatch offers psychoeducation and coaching — not a substitute for therapy. If you're going through a hard time, you're not alone: please reach out to a professional or a crisis line in your country.",
    footer: { tagline: "PerfectMatch · by EvaTalk — transforming your inner wounds, with psychology." },
  },
} as const;
export type Lang = keyof typeof HOME_COPY;
