// 14 nouveaux guides (7 FR + 7 EN). Upload dans lib/newGuides.ts.
// Les PDF correspondants vont dans public/guides/.
export const NEW_GUIDES = [
  // ---- FR ----
  { id: "sortir-solitude-femmes-noires", lang: "fr", theme: "Identité & résilience",
    title: "Sortir de la solitude — pour les femmes noires",
    blurb: "Sortir de la solitude quand on est une femme noire : créer des liens où l'on est vue, entière. 4 approches + conseils & tips.",
    pdf: "sortir-solitude-femmes-noires-4-approches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Valide ton vécu spécifique", "Apaise les pensées qui isolent", "Tisse des liens où tu es vue"] },
  { id: "apprendre-a-dire-non", lang: "fr", theme: "Relations",
    title: "Apprendre à dire non",
    blurb: "Poser tes limites sans culpabiliser. 4 approches + conseils & tips.",
    pdf: "apprendre-a-dire-non-4-approches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Comprends ton mal à dire non", "Apaise la culpabilité", "Des phrases concrètes pour refuser"] },
  { id: "briser-isolement", lang: "fr", theme: "Bien-être",
    title: "Briser l'isolement",
    blurb: "Sortir du repli, un petit pas à la fois. 4 approches + conseils & tips.",
    pdf: "briser-isolement-4-approches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Comprends ton repli", "Teste les pensées qui enferment", "Reconstruis un réseau"] },
  { id: "communication-assertive", lang: "fr", theme: "Relations",
    title: "Communication assertive",
    blurb: "Te faire entendre, sans t'écraser ni écraser. 4 approches + conseils & tips.",
    pdf: "communication-assertive-4-approches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Repère ton style", "Le message en « je »", "Pose des demandes claires"] },
  { id: "habiletes-sociales", lang: "fr", theme: "Relations",
    title: "Habiletés sociales",
    blurb: "Créer du lien, ça s'apprend. 4 approches + conseils & tips.",
    pdf: "habiletes-sociales-4-approches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Apaise l'anxiété sociale", "Ose l'authenticité", "Des compétences concrètes"] },
  { id: "gerer-ses-emotions", lang: "fr", theme: "Bien-être",
    title: "Gérer ses émotions",
    blurb: "Tes émotions ne sont pas tes ennemies. 4 approches + conseils & tips.",
    pdf: "gerer-ses-emotions-4-approches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Comprends tes émotions", "Accueille sans juger", "Régule au quotidien"] },
  { id: "gerer-le-stress", lang: "fr", theme: "Bien-être",
    title: "Gérer le stress",
    blurb: "Reprendre la main quand tout s'accélère. 4 approches + conseils & tips.",
    pdf: "gerer-le-stress-4-approches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Apaise le mental qui s'emballe", "Le cercle de contrôle", "Des appuis concrets"] },
  // ---- EN ----
  { id: "overcoming-loneliness-black-women", lang: "en", theme: "Identity & Resilience",
    title: "Overcoming Loneliness — for Black Women",
    blurb: "Overcoming loneliness as a Black woman: building bonds where you're seen, whole. 4 approaches + tips.",
    pdf: "overcoming-loneliness-black-women-4-approaches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Validates your specific experience", "Eases the thoughts that isolate", "Build bonds where you're seen"] },
  { id: "learning-to-say-no", lang: "en", theme: "Relationships",
    title: "Learning to Say No",
    blurb: "Set your boundaries without guilt. 4 approaches + tips.",
    pdf: "learning-to-say-no-4-approaches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Understand your difficulty", "Ease the guilt", "Concrete phrases to refuse"] },
  { id: "breaking-isolation", lang: "en", theme: "Wellbeing",
    title: "Breaking Isolation",
    blurb: "Out of withdrawal, one small step at a time. 4 approaches + tips.",
    pdf: "breaking-isolation-4-approaches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Understand your withdrawal", "Test the thoughts that lock you in", "Rebuild a network"] },
  { id: "assertive-communication", lang: "en", theme: "Relationships",
    title: "Assertive Communication",
    blurb: "Be heard — without shrinking or steamrolling. 4 approaches + tips.",
    pdf: "assertive-communication-4-approaches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Spot your style", "The 'I' message", "Make clear requests"] },
  { id: "social-skills", lang: "en", theme: "Relationships",
    title: "Social Skills",
    blurb: "Connecting with others is a learnable skill. 4 approaches + tips.",
    pdf: "social-skills-4-approaches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Ease social anxiety", "Dare authenticity", "Concrete skills"] },
  { id: "managing-your-emotions", lang: "en", theme: "Wellbeing",
    title: "Managing Your Emotions",
    blurb: "Your emotions aren't your enemies. 4 approaches + tips.",
    pdf: "managing-your-emotions-4-approaches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Understand your emotions", "Welcome without judging", "Regulate day to day"] },
  { id: "managing-stress", lang: "en", theme: "Wellbeing",
    title: "Managing Stress",
    blurb: "Take back control when everything speeds up. 4 approaches + tips.",
    pdf: "managing-stress-4-approaches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Ease the racing mind", "The circle of control", "Concrete supports"] },
] as const;
