// Collection Dating - "Cas particuliers & situations". Upload dans lib/proGuides30.ts. PDF dans public/guides/.
export const PRO_GUIDES_30 = [
  // ---- FR ----
  { id: "relations-ecart-d-age", lang: "fr", theme: "Amour & Relations", collection: "dating", subcollection: "cas-particuliers",
    title: "Les relations avec un écart d'âge",
    blurb: "Quand l'amour ne compte pas les années (dans les deux sens) : les valeurs priment sur l'âge, gérer le jugement, l'égalité de respect entre adultes consentants, naviguer les vraies différences. 4 approches.",
    pdf: "relations-ecart-d-age-4-approches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Les valeurs avant l'âge", "Égalité de respect", "Veiller à l'équilibre du pouvoir"] },
  { id: "femme-cougar", lang: "fr", theme: "Amour & Relations", collection: "dating", subcollection: "cas-particuliers",
    title: "Aimer un homme plus jeune",
    blurb: "Assumer sans te justifier : sortir du cliché « cougar », recadrer le double standard, ta valeur et ton désir n'ont pas d'âge, lucidité et communication sur les étapes de vie. 4 approches.",
    pdf: "femme-cougar-4-approches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Au-delà du cliché", "Le double standard n'est pas ton fardeau", "Assume sans te justifier"] },
  { id: "dater-avec-des-enfants", lang: "fr", theme: "Amour & Relations", collection: "dating", subcollection: "cas-particuliers",
    title: "Dater avec des enfants",
    blurb: "Refaire ta vie sans bousculer la leur : des couches en plus pas un mur, lever la culpabilité, ton bonheur compte aussi, protéger les enfants et filtrer les partenaires. 4 approches.",
    pdf: "dater-avec-des-enfants-4-approches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Ton bonheur compte aussi", "Présenter tard et du stable", "Le filtre : tes enfants"] },
  { id: "dating-et-traumas", lang: "fr", theme: "Amour & Relations", collection: "dating", subcollection: "cas-particuliers",
    title: "Dating & traumas",
    blurb: "Aimer à nouveau quand le passé a laissé des traces : le trauma colore l'amour (pas un défaut), questionner ses croyances, tu es digne d'amour avec tes blessures, avancer à ton rythme et bien accompagné·e. 4 approches.",
    pdf: "dating-et-traumas-4-approches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Une blessure, pas un défaut", "Digne d'amour", "Le trauma se soigne (pro)"] },
  { id: "le-premier-baiser", lang: "fr", theme: "Amour & Relations", collection: "dating", subcollection: "cas-particuliers",
    title: "Le premier baiser",
    blurb: "Oser, lire le moment, et savourer : lire le moment pas la technique, recadrer la peur, ton trac est humain, repérer le feu vert et le consentement (un baiser se partage, jamais ne se vole). 4 approches.",
    pdf: "le-premier-baiser-4-approches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Le moment > la technique", "Le trac est humain", "Feu vert & consentement"] },
  { id: "le-premier-rapport-sexuel", lang: "fr", theme: "Amour & Relations", collection: "dating", subcollection: "cas-particuliers", adult: true,
    title: "Le premier rapport sexuel",
    blurb: "À ton rythme, en confiance et en sécurité : aucun calendrier, recadrer la pression, ton consentement et ton rythme mènent, confiance, communication, contraception et prévention IST. 4 approches. 18+",
    pdf: "le-premier-rapport-sexuel-4-approches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Aucun calendrier", "Ton consentement mène", "Confiance & sécurité"] },
  { id: "qui-paie-au-rendez-vous", lang: "fr", theme: "Amour & Relations", collection: "dating", subcollection: "cas-particuliers",
    title: "50/50 : qui paie au rendez-vous ?",
    blurb: "Argent et rencontres, sans malaise : pas de règle unique, l'argent n'est pas un test, tes valeurs (tradition ou égalité) sont valides, en parler tôt et aligner vos valeurs. 4 approches.",
    pdf: "qui-paie-au-rendez-vous-4-approches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Pas de règle unique", "L'argent n'est pas un test", "En parler tôt"] },
  // ---- EN ----
  { id: "age-gap-relationships", lang: "en", theme: "Love & Relationships", collection: "dating", subcollection: "special-cases",
    title: "Age-Gap Relationships",
    blurb: "When love doesn't count the years (both ways): values over age, handle judgment, equal respect between consenting adults, navigate the real differences. 4 approaches.",
    pdf: "age-gap-relationships-4-approaches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Values before age", "Equal respect", "Watch the balance of power"] },
  { id: "dating-a-younger-man", lang: "en", theme: "Love & Relationships", collection: "dating", subcollection: "special-cases",
    title: "Dating a Younger Man",
    blurb: "Own it without justifying: get past the 'cougar' cliché, reframe the double standard, your worth and desire have no age, clarity and communication on life stages. 4 approaches.",
    pdf: "dating-a-younger-man-4-approaches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Beyond the cliché", "The double standard isn't your burden", "Own it"] },
  { id: "dating-with-children", lang: "en", theme: "Love & Relationships", collection: "dating", subcollection: "special-cases",
    title: "Dating with Children",
    blurb: "Rebuild your life without unsettling theirs: extra layers not a wall, lift the guilt, your happiness matters too, protect the kids and screen partners. 4 approaches.",
    pdf: "dating-with-children-4-approaches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Your happiness matters too", "Introduce late and stable", "The filter: your kids"] },
  { id: "dating-with-trauma", lang: "en", theme: "Love & Relationships", collection: "dating", subcollection: "special-cases",
    title: "Dating & Trauma",
    blurb: "Loving again when the past left marks: trauma colors love (not a flaw), question your beliefs, you're worthy of love with your wounds, move at your pace and well supported. 4 approaches.",
    pdf: "dating-with-trauma-4-approaches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["A wound, not a flaw", "Worthy of love", "Trauma is treatable (pro)"] },
  { id: "the-first-kiss", lang: "en", theme: "Love & Relationships", collection: "dating", subcollection: "special-cases",
    title: "The First Kiss",
    blurb: "Daring, reading the moment, and savoring it: read the moment not the technique, reframe the fear, your nerves are human, spot the green light and consent (a kiss is shared, never stolen). 4 approaches.",
    pdf: "the-first-kiss-4-approaches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["The moment > technique", "Nerves are human", "Green light & consent"] },
  { id: "the-first-time", lang: "en", theme: "Love & Relationships", collection: "dating", subcollection: "special-cases", adult: true,
    title: "The First Time",
    blurb: "At your pace, in confidence and safety: no timeline, reframe the pressure, your consent and pace lead, confidence, communication, contraception and STI prevention. 4 approaches. 18+",
    pdf: "the-first-time-4-approaches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["No timeline", "Your consent leads", "Confidence & safety"] },
  { id: "who-pays-on-a-date", lang: "en", theme: "Love & Relationships", collection: "dating", subcollection: "special-cases",
    title: "50/50: Who Pays on a Date?",
    blurb: "Money and dating, without awkwardness: no single rule, money isn't a test, your values (tradition or equality) are valid, talk early and align your values. 4 approaches.",
    pdf: "who-pays-on-a-date-4-approaches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["No single rule", "Money isn't a test", "Talk early"] },
] as const;
