// Lot travail C "B2B / dirigeants" (4 FR + 4 EN), thème Travail / Career.
// Upload dans lib/proGuides11.ts. PDF dans public/guides/.
// AFFICHAGE FR : section codée en dur SECTIONS -> clé "travail". AFFICHAGE EN : thème "Career".
export const PRO_GUIDES_11 = [
  // ---- FR : thème Travail ----
  { id: "soutenir-collaborateur-en-difficulte", lang: "fr", theme: "Travail",
    title: "Soutenir un·e collaborateur·rice en difficulté",
    blurb: "Accompagner sans surjouer ni fuir : la juste posture du manager — écouter, ajuster, orienter vers les bons relais. 4 approches + repères.",
    pdf: "soutenir-collaborateur-en-difficulte-4-approches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["La juste posture", "Écouter sans diagnostiquer", "Orienter vers les bons relais"] },
  { id: "entretiens-evaluation-equitables", lang: "fr", theme: "Travail",
    title: "Mener des entretiens d'évaluation équitables",
    blurb: "Évaluer juste, motiver, sans biais : déjouer halo et récence, remettre l'évaluation au service de la personne, une méthode équitable. 4 approches + conseils & tips.",
    pdf: "entretiens-evaluation-equitables-4-approches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Déjoue tes biais", "Au service de la personne", "Une méthode équitable"] },
  { id: "manager-retour-apres-arret", lang: "fr", theme: "Travail",
    title: "Manager le retour après un arrêt",
    blurb: "Accueillir un retour (burn-out, maladie) en douceur et en sécurité : posture humaine, reprise progressive, prévenir la rechute. 4 approches + repères.",
    pdf: "manager-retour-apres-arret-4-approches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Une posture humaine", "Reprise progressive", "Prévenir la rechute"] },
  { id: "prevenir-risques-psychosociaux", lang: "fr", theme: "Travail",
    title: "Prévenir les risques psychosociaux dans son équipe",
    blurb: "Protéger la santé de ton équipe au quotidien : repérer les signaux, une culture qui protège, des leviers organisationnels concrets. 4 approches + repères.",
    pdf: "prevenir-risques-psychosociaux-4-approches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Repère les signaux", "Une culture qui protège", "Des leviers organisationnels"] },
  // ---- EN : theme Career ----
  { id: "supporting-a-struggling-team-member", lang: "en", theme: "Career",
    title: "Supporting a Struggling Team Member",
    blurb: "Help without overplaying or fleeing: the right manager stance — listen, adjust, direct toward the right channels. 4 approaches + guidance.",
    pdf: "supporting-a-struggling-team-member-4-approaches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["The right stance", "Listen without diagnosing", "Direct to the right channels"] },
  { id: "fair-performance-reviews", lang: "en", theme: "Career",
    title: "Running Fair Performance Reviews",
    blurb: "Evaluate fairly, motivate, without bias: defeat halo and recency, put the review in service of the person, a fair method. 4 approaches + tips.",
    pdf: "fair-performance-reviews-4-approaches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Defeat your biases", "Serving the person", "A fair method"] },
  { id: "managing-a-return-to-work", lang: "en", theme: "Career",
    title: "Managing a Return to Work",
    blurb: "Welcome a return (burnout, illness) gently and safely: a human stance, a gradual restart, prevent relapse. 4 approaches + guidance.",
    pdf: "managing-a-return-to-work-4-approaches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["A human stance", "Gradual restart", "Prevent relapse"] },
  { id: "preventing-psychosocial-risks", lang: "en", theme: "Career",
    title: "Preventing Psychosocial Risks in Your Team",
    blurb: "Protect your team's health every day: spot the signals, a protective culture, concrete organizational levers. 4 approaches + guidance.",
    pdf: "preventing-psychosocial-risks-4-approaches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Spot the signals", "A protective culture", "Organizational levers"] },
] as const;
