// Lot travail 3 (4 FR + 4 EN), thème Travail / Career.
// Upload dans lib/proGuides8.ts. PDF dans public/guides/.
// AFFICHAGE FR : section codée en dur SECTIONS -> clé "travail". AFFICHAGE EN : thème "Career".
export const PRO_GUIDES_8 = [
  // ---- FR : thème Travail ----
  { id: "reussir-sa-prise-de-poste", lang: "fr", theme: "Travail",
    title: "Réussir sa prise de poste",
    blurb: "Bien démarrer tes premiers mois : apaiser la pression des débuts, trouver ta place, piloter ta prise de poste avec un plan 30/60/90. 4 approches + conseils & tips.",
    pdf: "reussir-sa-prise-de-poste-4-approches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Apaise la pression des débuts", "Trouve ta place", "Un plan 30/60/90"] },
  { id: "donner-recevoir-feedback", lang: "fr", theme: "Travail",
    title: "Donner et recevoir du feedback",
    blurb: "Des retours qui font grandir, pas qui blessent : formuler un feedback factuel, accueillir une critique sans s'effondrer. 4 approches + conseils & tips.",
    pdf: "donner-recevoir-feedback-4-approches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Feedback factuel (S-C-I)", "Recevoir sans s'effondrer", "Au service de la relation"] },
  { id: "equilibre-pro-perso", lang: "fr", theme: "Travail",
    title: "Équilibre pro-perso & charge mentale",
    blurb: "Poser des limites et alléger la charge mentale : te réautoriser à exister hors du travail, des limites concrètes et durables. 4 approches + conseils & tips.",
    pdf: "equilibre-pro-perso-4-approches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Comprends ce qui t'empêche de lâcher", "Pose des limites", "Allège la charge mentale"] },
  { id: "repondre-aux-microagressions", lang: "fr", theme: "Travail",
    title: "Répondre aux microagressions au travail",
    blurb: "Réagir aux petites phrases qui blessent, à ta façon : valider ton ressenti, protéger ton énergie, un répertoire de réponses. 4 approches + ressources.",
    pdf: "repondre-aux-microagressions-4-approches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Ton ressenti est légitime", "Choisis tes combats", "Un répertoire de réponses"] },
  // ---- EN : theme Career ----
  { id: "succeeding-in-a-new-role", lang: "en", theme: "Career",
    title: "Succeeding in a New Role",
    blurb: "Start your first months well: ease the early-days pressure, find your place, steer your start with a 30/60/90 plan. 4 approaches + tips.",
    pdf: "succeeding-in-a-new-role-4-approaches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Ease the early-days pressure", "Find your place", "A 30/60/90 plan"] },
  { id: "giving-and-receiving-feedback", lang: "en", theme: "Career",
    title: "Giving and Receiving Feedback",
    blurb: "Feedback that grows people, not wounds them: deliver factual feedback, take criticism without falling apart. 4 approaches + tips.",
    pdf: "giving-and-receiving-feedback-4-approaches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Factual feedback (S-B-I)", "Receive without falling apart", "Serving the relationship"] },
  { id: "work-life-balance-and-mental-load", lang: "en", theme: "Career",
    title: "Work-Life Balance & Mental Load",
    blurb: "Set limits and ease the mental load: allow yourself to exist beyond work, concrete and lasting limits. 4 approaches + tips.",
    pdf: "work-life-balance-and-mental-load-4-approaches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Understand what stops you letting go", "Set limits", "Ease the mental load"] },
  { id: "responding-to-microaggressions-at-work", lang: "en", theme: "Career",
    title: "Responding to Microaggressions at Work",
    blurb: "React to the small wounding remarks, in your own way: validate your feeling, protect your energy, a repertoire of responses. 4 approaches + resources.",
    pdf: "responding-to-microaggressions-at-work-4-approaches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Your feeling is legitimate", "Choose your battles", "A repertoire of responses"] },
] as const;
