// Collection "Créateur·rice & Influence" — LOT 1/5 (Démarrer & tenir). Upload dans lib/proGuides32.ts. PDF dans public/guides/.
export const PRO_GUIDES_32 = [
  // ---- FR ----
  { id: "oser-te-montrer-camera", lang: "fr", theme: "Créateur·rice & Influence", collection: "creator",
    title: "Oser te montrer face caméra",
    blurb: "Vaincre la peur du jugement : la peur du regard est normale, recadrer « tout le monde va me juger », t'autoriser à prendre ta place, l'exposition progressive. 4 approches.",
    pdf: "oser-te-montrer-camera-4-approches.pdf", priceCents: 999, currency: "eur",
    bullets: ["La peur du regard est normale", "Ton message > ton trac", "Exposition progressive"] },
  { id: "syndrome-imposteur-createur", lang: "fr", theme: "Créateur·rice & Influence", collection: "creator",
    title: "Le syndrome de l'imposteur du créateur",
    blurb: "« Qui suis-je pour parler de ça ? » : un sentiment quasi universel, recadrer « on va me démasquer », ta voix a de la valeur, enseigner depuis là où tu es. 4 approches.",
    pdf: "syndrome-imposteur-createur-4-approches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Aider qui te suit d'un pas", "Ta voix a de la valeur", "Enseigner depuis où tu es"] },
  { id: "trouver-ta-niche-voix", lang: "fr", theme: "Créateur·rice & Influence", collection: "creator",
    title: "Trouver ta niche et ta voix authentique",
    blurb: "Arrête de copier, deviens reconnaissable : niche + authenticité = visibilité, recadrer « tout a déjà été fait », assumer ta singularité, définir ton angle et tes codes. 4 approches.",
    pdf: "trouver-ta-niche-voix-4-approches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Niche + authenticité", "Ta singularité = ton atout", "Angle & codes clairs"] },
  { id: "regularite-sans-tepuiser", lang: "fr", theme: "Créateur·rice & Influence", collection: "creator",
    title: "La régularité sans t'épuiser",
    blurb: "Discipline, motivation, fin de la procrastination : miser sur les systèmes pas la motivation, recadrer « pas d'inspiration », douceur pas fouet, bâtir ton système de création. 4 approches.",
    pdf: "regularite-sans-tepuiser-4-approches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Systèmes > motivation", "Agir sans inspiration", "Régularité > perfection"] },
  { id: "burn-out-createur", lang: "fr", theme: "Créateur·rice & Influence", collection: "creator",
    title: "Le burn-out du créateur de contenu",
    blurb: "L'« always-on » et la fatigue : repérer les signes, recadrer « si je m'arrête je disparais », ta santé avant l'algorithme, poser des limites pour durer. 4 approches.",
    pdf: "burn-out-createur-4-approches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Repérer les signes tôt", "Ta santé > l'algorithme", "Limites pour durer"] },
  { id: "solitude-du-createur", lang: "fr", theme: "Créateur·rice & Influence", collection: "creator",
    title: "La solitude du créateur",
    blurb: "Visible par des milliers, seul·e derrière l'écran : le paradoxe parasocial, recadrer « personne ne comprend », tes vrais liens comptent, recréer du lien réel. 4 approches.",
    pdf: "solitude-du-createur-4-approches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Le paradoxe parasocial", "Ta solitude est légitime", "Recréer du lien réel"] },
  // ---- EN ----
  { id: "daring-to-show-up-on-camera", lang: "en", theme: "Creator & Influence", collection: "creator",
    title: "Daring to Show Up on Camera",
    blurb: "Beat the fear of judgment: fear of being seen is normal, reframe 'everyone will judge me', allow yourself to take your place, gradual exposure. 4 approaches.",
    pdf: "daring-to-show-up-on-camera-4-approaches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Fear of being seen is normal", "Your message > your nerves", "Gradual exposure"] },
  { id: "creator-impostor-syndrome", lang: "en", theme: "Creator & Influence", collection: "creator",
    title: "The Creator's Impostor Syndrome",
    blurb: "'Who am I to talk about this?': a near-universal feeling, reframe 'they'll expose me', your voice has value, teach from where you are. 4 approaches.",
    pdf: "creator-impostor-syndrome-4-approaches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Help whoever follows you", "Your voice has value", "Teach from where you are"] },
  { id: "finding-your-niche-and-voice", lang: "en", theme: "Creator & Influence", collection: "creator",
    title: "Finding Your Niche and Authentic Voice",
    blurb: "Stop copying, become recognizable: niche + authenticity = visibility, reframe 'it's all been done', own your uniqueness, define your angle and codes. 4 approaches.",
    pdf: "finding-your-niche-and-voice-4-approaches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Niche + authenticity", "Your uniqueness = your asset", "Clear angle & codes"] },
  { id: "consistency-without-burning-out", lang: "en", theme: "Creator & Influence", collection: "creator",
    title: "Consistency Without Burning Out",
    blurb: "Discipline, motivation, end of procrastination: bet on systems not motivation, reframe 'no inspiration', gentleness not the whip, build your creation system. 4 approaches.",
    pdf: "consistency-without-burning-out-4-approaches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Systems > motivation", "Act without inspiration", "Consistency > perfection"] },
  { id: "content-creator-burnout", lang: "en", theme: "Creator & Influence", collection: "creator",
    title: "Content Creator Burnout",
    blurb: "The 'always-on' and the fatigue: spot the signs, reframe 'if I stop I disappear', your health before the algorithm, set limits to last. 4 approaches.",
    pdf: "content-creator-burnout-4-approaches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Spot the signs early", "Your health > the algorithm", "Limits to last"] },
  { id: "the-creator-loneliness", lang: "en", theme: "Creator & Influence", collection: "creator",
    title: "The Creator's Loneliness",
    blurb: "Seen by thousands, alone behind the screen: the parasocial paradox, reframe 'no one understands', your real bonds matter, rebuild real connection. 4 approaches.",
    pdf: "the-creator-loneliness-4-approaches.pdf", priceCents: 999, currency: "eur",
    bullets: ["The parasocial paradox", "Your loneliness is legitimate", "Rebuild real connection"] },
] as const;
