// Collection "Créateur·rice & Influence" — LOT 5/5 (Rapport à soi & argent). Upload dans lib/proGuides36.ts. PDF dans public/guides/.
export const PRO_GUIDES_36 = [
  // ---- FR ----
  { id: "estime-qui-ne-depend-pas-des-likes", lang: "fr", theme: "Créateur·rice & Influence", collection: "creator",
    title: "Une estime de soi qui ne dépend pas des likes",
    blurb: "Le socle, sous tout le reste : le piège de la validation (dopamine), recadrer « peu de vues = je ne vaux rien », ta valeur est intrinsèque, des sources d'estime hors réseaux. 4 approches.",
    pdf: "estime-qui-ne-depend-pas-des-likes-4-approches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Le piège de la validation", "Ta valeur est intrinsèque", "Sources hors réseaux"] },
  { id: "oser-monetiser-sans-culpabilite", lang: "fr", theme: "Créateur·rice & Influence", collection: "creator",
    title: "Oser monétiser sans culpabilité",
    blurb: "Vendre, fixer tes prix, en parler : monétiser est légitime, recadrer « me vendre c'est mal », ton travail mérite paiement, premières offres à prix juste. 4 approches.",
    pdf: "oser-monetiser-sans-culpabilite-4-approches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Monétiser est légitime", "Ton travail mérite paiement", "Offre alignée, prix juste"] },
  { id: "de-la-passion-au-metier", lang: "fr", theme: "Créateur·rice & Influence", collection: "creator",
    title: "De la passion au métier : le mindset entrepreneurial",
    blurb: "Transformer le contenu en revenu durable : du loisir à l'activité, recadrer « ce n'est pas un vrai métier », t'autoriser à en vivre, diversifier et structurer. 4 approches.",
    pdf: "de-la-passion-au-metier-4-approches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Un vrai métier", "T'autoriser à en vivre", "Diversifier & structurer"] },
  { id: "addiction-a-ton-telephone", lang: "fr", theme: "Créateur·rice & Influence", collection: "creator",
    title: "L'addiction à ton propre téléphone",
    blurb: "Le créateur happé par ce qu'il crée : la boucle dopamine, recadrer « je dois être là 24/7 », ta vie hors écran compte, hygiène numérique. 4 approches.",
    pdf: "addiction-a-ton-telephone-4-approches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["La boucle dopamine", "Pas disponible 24/7", "Hygiène numérique"] },
  { id: "la-depression-du-createur", lang: "fr", theme: "Créateur·rice & Influence", collection: "creator",
    title: "La dépression du créateur",
    blurb: "Quand ça dépasse le coup de mou : distinguer déprime et dépression (une maladie qui se soigne), recadrer « je devrais être heureux·se », ta valeur ≠ ta productivité, consulter et ne pas rester seul·e. 4 approches.",
    pdf: "la-depression-du-createur-4-approches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Une maladie qui se soigne", "Pas une faiblesse", "Consulter un·e pro"] },
  { id: "le-decalage-de-la-reussite", lang: "fr", theme: "Créateur·rice & Influence", collection: "creator",
    title: "Le décalage de la grande réussite",
    blurb: "Quand le succès ne ressemble pas à ce que tu imaginais : l'illusion de l'arrivée, recadrer « j'ai tout, pourquoi ce vide ? », t'autoriser à ressentir ça, retrouver du sens au-delà des chiffres. 4 approches.",
    pdf: "le-decalage-de-la-reussite-4-approches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["L'illusion de l'arrivée", "Réussite ≠ bonheur", "Du sens au-delà des chiffres"] },
  // ---- EN ----
  { id: "self-esteem-beyond-likes", lang: "en", theme: "Creator & Influence", collection: "creator",
    title: "Self-Esteem That Doesn't Depend on Likes",
    blurb: "The foundation, beneath everything: the validation trap (dopamine), reframe 'few views = I'm worthless', your worth is intrinsic, sources of esteem off social media. 4 approaches.",
    pdf: "self-esteem-beyond-likes-4-approaches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["The validation trap", "Your worth is intrinsic", "Off-social sources"] },
  { id: "monetizing-without-guilt", lang: "en", theme: "Creator & Influence", collection: "creator",
    title: "Monetizing Without Guilt",
    blurb: "Selling, setting prices, talking about it: monetizing is legitimate, reframe 'selling is bad', your work deserves payment, first offers at a fair price. 4 approaches.",
    pdf: "monetizing-without-guilt-4-approaches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Monetizing is legitimate", "Your work deserves payment", "Aligned offer, fair price"] },
  { id: "from-passion-to-profession", lang: "en", theme: "Creator & Influence", collection: "creator",
    title: "From Passion to Profession: The Entrepreneurial Mindset",
    blurb: "Turning content into sustainable income: from hobby to activity, reframe 'it's not a real job', allow yourself to live from it, diversify and structure. 4 approaches.",
    pdf: "from-passion-to-profession-4-approaches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["A real job", "Allow yourself to live from it", "Diversify & structure"] },
  { id: "phone-addiction", lang: "en", theme: "Creator & Influence", collection: "creator",
    title: "Addiction to Your Own Phone",
    blurb: "The creator swallowed by what they create: the dopamine loop, reframe 'I must be there 24/7', your life off-screen matters, digital hygiene. 4 approaches.",
    pdf: "phone-addiction-4-approaches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["The dopamine loop", "Not available 24/7", "Digital hygiene"] },
  { id: "creator-depression", lang: "en", theme: "Creator & Influence", collection: "creator",
    title: "Creator Depression",
    blurb: "When it goes beyond a rough patch: tell low mood from depression (a treatable illness), reframe 'I should be happy', your worth ≠ your productivity, get help and don't stay alone. 4 approaches.",
    pdf: "creator-depression-4-approaches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["A treatable illness", "Not a weakness", "Consult a professional"] },
  { id: "the-success-letdown", lang: "en", theme: "Creator & Influence", collection: "creator",
    title: "The Letdown of Great Success",
    blurb: "When success doesn't feel like you imagined: the arrival fallacy, reframe 'I have it all, why this emptiness?', allow yourself to feel it, find meaning beyond the numbers. 4 approaches.",
    pdf: "the-success-letdown-4-approaches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["The arrival fallacy", "Success ≠ happiness", "Meaning beyond numbers"] },
] as const;
