// Collection "Héritage & Transmission" — AJOUT 2 (honte, loyauté invisible, transfuge). Upload dans lib/proGuides39.ts. PDF dans public/guides/.
export const PRO_GUIDES_39 = [
  // ---- FR ----
  { id: "honte-transmise", lang: "fr", theme: "Héritage & Transmission", collection: "transmission",
    title: "La honte transmise",
    blurb: "Quand tu portes une honte qui n'est pas la tienne : culpabilité vs honte, recadrer « il y a quelque chose de mauvais en moi », tu n'es pas la honte que tu portes, sortir la honte du silence. 4 approches.",
    pdf: "honte-transmise-4-approches.pdf", priceCents: 999, currency: "eur",
    bullets: ["La honte ment", "Pas la honte que tu portes", "La sortir du silence"] },
  { id: "loyaute-familiale-invisible", lang: "fr", theme: "Héritage & Transmission", collection: "transmission",
    title: "La loyauté familiale invisible",
    blurb: "Ces fidélités inconscientes qui dirigent ta vie : appartenir même à un prix, recadrer « si je vais bien je les trahis », aimer ET vivre ta vie, te donner la permission d'avancer. 4 approches.",
    pdf: "loyaute-familiale-invisible-4-approches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Une fidélité inconsciente", "Aller bien ≠ trahir", "Te donner la permission"] },
  { id: "reussir-transfuge-de-classe", lang: "fr", theme: "Héritage & Transmission", collection: "transmission",
    title: "Réussir quand personne ne l'a fait avant toi",
    blurb: "Le vertige du transfuge : avancer sans carte, recadrer « je ne suis pas à ma place », honorer tes origines ET ta nouvelle place, tracer ta carte et t'entourer de pairs. 4 approches.",
    pdf: "reussir-transfuge-de-classe-4-approches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Avancer sans carte", "Tu as gagné ta place", "Un pont entre deux mondes"] },
  // ---- EN ----
  { id: "inherited-shame", lang: "en", theme: "Legacy & Transmission", collection: "transmission",
    title: "Inherited Shame",
    blurb: "When you carry a shame that isn't yours: guilt vs shame, reframe 'there's something bad in me', you aren't the shame you carry, bring shame out of silence. 4 approaches.",
    pdf: "inherited-shame-4-approaches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Shame lies", "Not the shame you carry", "Out of silence"] },
  { id: "invisible-family-loyalty", lang: "en", theme: "Legacy & Transmission", collection: "transmission",
    title: "Invisible Family Loyalty",
    blurb: "The unconscious fidelities that run your life: belonging even at a price, reframe 'if I'm okay I betray them', love AND live your life, give yourself permission to move forward. 4 approaches.",
    pdf: "invisible-family-loyalty-4-approaches.pdf", priceCents: 999, currency: "eur",
    bullets: ["An unconscious fidelity", "Being okay ≠ betraying", "Give yourself permission"] },
  { id: "first-in-your-family-to-succeed", lang: "en", theme: "Legacy & Transmission", collection: "transmission",
    title: "Succeeding When No One Did It Before You",
    blurb: "The first-gen vertigo: moving without a map, reframe 'I don't belong here', honor your origins AND your new place, draw your map and surround yourself with peers. 4 approaches.",
    pdf: "first-in-your-family-to-succeed-4-approaches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Moving without a map", "You earned your place", "A bridge between two worlds"] },
] as const;
