// Collection "Relations plurielles / Polygamie" — lot 2 (contexte africain, dynamiques de couple). Upload dans lib/proGuides24.ts.
export const PRO_GUIDES_24 = [
  // ---- FR ----
  { id: "garder-lien-fort-mari", lang: "fr", theme: "Bien-être & soi", collection: "polygamie",
    title: "Garder un lien fort avec ton mari",
    blurb: "Entretenir VOTRE complicité malgré le partage : protéger ce qui est unique à votre couple, soigner la qualité de vos moments, cultiver un rituel, exprimer tes besoins. 4 approches.",
    pdf: "garder-lien-fort-mari-4-approches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Votre lien est unique", "Qualité, pas quantité", "Rituels & besoins"] },
  { id: "poids-belle-famille", lang: "fr", theme: "Bien-être & soi", collection: "polygamie",
    title: "Le poids de la belle-famille",
    blurb: "Poser des limites face aux attentes et ingérences : comprendre le système, sortir des pensées qui t'enferment, respecter la tradition sans t'effacer, mobiliser ton mari comme tampon. 4 approches.",
    pdf: "poids-belle-famille-4-approches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Un système, pas du personnel", "Respecter sans t'effacer", "Le mari, tampon"] },
  { id: "etre-premiere-epouse", lang: "fr", theme: "Bien-être & soi", collection: "polygamie",
    title: "Être la première épouse (awo)",
    blurb: "Porter ton statut d'aînée sans te perdre : accueillir le choc sans le nier, recadrer « son choix = mon échec », séparer ton rang de ta valeur, donner un ton digne sans tout porter. 4 approches.",
    pdf: "etre-premiere-epouse-4-approches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Statut & choc", "Ton rang ≠ ta valeur", "Donner le ton, sans subir"] },
  { id: "regard-communaute", lang: "fr", theme: "Bien-être & soi", collection: "polygamie",
    title: "Le regard de la communauté",
    blurb: "T'honorer toi, au-delà des apparences : comprendre la machine du qu'en-dira-t-on, cesser de vivre pour un public, t'aligner sur tes valeurs, choisir tes confidents. 4 approches.",
    pdf: "regard-communaute-4-approches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["La machine du qu'en-dira-t-on", "Tes valeurs avant les apparences", "Tes vrais alliés"] },
  { id: "polygamie-et-foi", lang: "fr", theme: "Bien-être & soi", collection: "polygamie",
    title: "Polygamie et foi",
    blurb: "Concilier ta réalité émotionnelle et ta spiritualité, dans le respect de ta foi : l'équité comme devoir, ressentir n'est pas trahir, ta foi comme ressource, ta dignité aussi est sacrée. 4 approches.",
    pdf: "polygamie-et-foi-4-approches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["L'équité, un devoir", "Ressentir n'est pas trahir", "Ta dignité est sacrée"] },
  { id: "dependance-economique-autonomie", lang: "fr", theme: "Bien-être & soi", collection: "polygamie",
    title: "Dépendance économique & autonomie",
    blurb: "Bâtir ton indépendance et ta dignité : voir ce que la dépendance te coûte, recadrer « c'est impossible », valoriser tes savoir-faire, des pas concrets vers un revenu et un réseau de femmes. 4 approches.",
    pdf: "dependance-economique-autonomie-4-approches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Dépendance vs liberté", "Tes savoir-faire", "Pas concrets & tontines"] },
  // ---- EN ----
  { id: "staying-close-to-your-husband", lang: "en", theme: "Wellbeing & Self", collection: "polygamy",
    title: "Staying Close to Your Husband",
    blurb: "Nurture YOUR bond despite the sharing: protect what's unique to your couple, tend to the quality of your moments, build a ritual, express your needs. 4 approaches.",
    pdf: "staying-close-to-your-husband-4-approaches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Your bond is unique", "Quality, not quantity", "Rituals & needs"] },
  { id: "the-weight-of-in-laws", lang: "en", theme: "Wellbeing & Self", collection: "polygamy",
    title: "The Weight of In-Laws",
    blurb: "Set limits with expectations and interference: understand the system, leave the thoughts that trap you, respect tradition without erasing yourself, enlist your husband as buffer. 4 approaches.",
    pdf: "the-weight-of-in-laws-4-approaches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["A system, not personal", "Respect without erasing", "The husband as buffer"] },
  { id: "being-the-first-wife", lang: "en", theme: "Wellbeing & Self", collection: "polygamy",
    title: "Being the First Wife",
    blurb: "Carry your senior status without losing yourself: welcome the shock without denying it, reframe 'his choice = my failure', separate rank from worth, set a dignified tone. 4 approaches.",
    pdf: "being-the-first-wife-4-approaches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Status & shock", "Rank ≠ worth", "Set the tone, don't endure"] },
  { id: "facing-community-judgment", lang: "en", theme: "Wellbeing & Self", collection: "polygamy",
    title: "Facing the Community's Judgment",
    blurb: "Honor yourself beyond appearances: understand the gossip machine, stop living for an audience, align with your values, choose your confidants. 4 approaches.",
    pdf: "facing-community-judgment-4-approaches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["The gossip machine", "Values over appearances", "Your real allies"] },
  { id: "polygamy-and-faith", lang: "en", theme: "Wellbeing & Self", collection: "polygamy",
    title: "Polygamy and Faith",
    blurb: "Reconcile your emotional reality and spirituality, respectful of your faith: fairness as duty, feeling isn't betraying, faith as a resource, your dignity is sacred too. 4 approaches.",
    pdf: "polygamy-and-faith-4-approaches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Fairness, a duty", "Feeling isn't betraying", "Your dignity is sacred"] },
  { id: "economic-dependence-and-autonomy", lang: "en", theme: "Wellbeing & Self", collection: "polygamy",
    title: "Economic Dependence & Autonomy",
    blurb: "Build your independence and dignity: see what dependence costs you, reframe 'it's impossible', value your skills, concrete steps toward income and a women's network. 4 approaches.",
    pdf: "economic-dependence-and-autonomy-4-approaches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Dependence vs freedom", "Your skills", "Concrete steps & savings groups"] },
] as const;
