// Collection "Créateur·rice & Influence" — LOT 2/5 (Le regard des autres). Upload dans lib/proGuides33.ts. PDF dans public/guides/.
export const PRO_GUIDES_33 = [
  // ---- FR ----
  { id: "gerer-la-comparaison", lang: "fr", theme: "Créateur·rice & Influence", collection: "creator",
    title: "Gérer la comparaison",
    blurb: "Le scroll qui démoralise : un jeu truqué (tes coulisses vs leur vitrine), recadrer « les autres réussissent pas moi », courir TA course, hygiène de feed. 4 approches.",
    pdf: "gerer-la-comparaison-4-approches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Coulisses vs vitrine", "Toi d'hier vs toi d'aujourd'hui", "Hygiène de feed"] },
  { id: "encaisser-haters-critiques", lang: "fr", theme: "Créateur·rice & Influence", collection: "creator",
    title: "Encaisser les critiques et les haters",
    blurb: "Ne pas intérioriser la haine : un hater parle de lui, recadrer « ils ont peut-être raison », ta valeur ≠ leurs mots, filtrer/modérer/ne pas nourrir. 4 approches.",
    pdf: "encaisser-haters-critiques-4-approches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Ça parle d'eux", "Ta valeur ≠ leurs mots", "Filtrer & ne pas nourrir"] },
  { id: "exposition-et-vie-privee", lang: "fr", theme: "Créateur·rice & Influence", collection: "creator",
    title: "Exposition & vie privée",
    blurb: "Poser des limites, gérer le parasocial : le lien parasocial crée des attentes, recadrer « je dois tout partager », ton droit à un jardin secret, tracer ta ligne de vie privée. 4 approches.",
    pdf: "exposition-et-vie-privee-4-approches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Tu ne dois pas tout montrer", "Ton jardin secret", "Trace ta ligne"] },
  { id: "jugement-de-tes-proches", lang: "fr", theme: "Créateur·rice & Influence", collection: "creator",
    title: "Gérer le jugement de tes proches",
    blurb: "« C'est pas un vrai métier » : pourquoi les proches jugent (peur, incompréhension), recadrer « s'ils ont honte j'ai tort », ta voie t'appartient, poser des limites. 4 approches.",
    pdf: "jugement-de-tes-proches-4-approches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Ça parle de leur cadre", "Pas besoin de leur aval", "Poser des limites"] },
  { id: "garder-ta-liberte-creative", lang: "fr", theme: "Créateur·rice & Influence", collection: "creator",
    title: "Garder ta liberté créative",
    blurb: "Évoluer sans « trahir » ta communauté : tu as le droit d'évoluer, recadrer « ils vont me détester si je change », ton droit de ne pas être figé·e, amener ton audience avec toi. 4 approches.",
    pdf: "garder-ta-liberte-creative-4-approches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Tu as le droit d'évoluer", "Pas otage de ton image", "Amener les alignés"] },
  { id: "decalage-image-vraie-vie", lang: "fr", theme: "Créateur·rice & Influence", collection: "creator",
    title: "Le décalage image en ligne / vraie vie",
    blurb: "Quand tu te sens « faux » : un écart normal jusqu'à un point, recadrer « je suis un imposteur », réconcilier tes deux faces, réduire le fossé là où il pèse. 4 approches.",
    pdf: "decalage-image-vraie-vie-4-approches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Curation ≠ mensonge", "Réel et imparfait", "Réduire le fossé"] },
  // ---- EN ----
  { id: "handling-comparison", lang: "en", theme: "Creator & Influence", collection: "creator",
    title: "Handling Comparison",
    blurb: "The scroll that demoralizes: a rigged game (your backstage vs their reel), reframe 'others succeed not me', run YOUR race, feed hygiene. 4 approaches.",
    pdf: "handling-comparison-4-approaches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Backstage vs reel", "Yesterday's you vs today's", "Feed hygiene"] },
  { id: "handling-criticism-and-haters", lang: "en", theme: "Creator & Influence", collection: "creator",
    title: "Handling Criticism and Haters",
    blurb: "Not internalizing the hate: a hater speaks about themselves, reframe 'maybe they're right', your worth ≠ their words, filter/moderate/don't feed. 4 approaches.",
    pdf: "handling-criticism-and-haters-4-approaches.pdf", priceCents: 999, currency: "eur",
    bullets: ["It's about them", "Your worth ≠ their words", "Filter & don't feed"] },
  { id: "exposure-and-privacy", lang: "en", theme: "Creator & Influence", collection: "creator",
    title: "Exposure & Privacy",
    blurb: "Setting limits, managing the parasocial: the parasocial bond creates expectations, reframe 'I must share everything', your right to a private garden, draw your privacy line. 4 approaches.",
    pdf: "exposure-and-privacy-4-approaches.pdf", priceCents: 999, currency: "eur",
    bullets: ["You needn't show everything", "Your private garden", "Draw your line"] },
  { id: "loved-ones-judgment", lang: "en", theme: "Creator & Influence", collection: "creator",
    title: "Handling Your Loved Ones' Judgment",
    blurb: "'It's not a real job': why loved ones judge (fear, misunderstanding), reframe 'if they're ashamed I'm wrong', your path is yours, set limits. 4 approaches.",
    pdf: "loved-ones-judgment-4-approaches.pdf", priceCents: 999, currency: "eur",
    bullets: ["It's about their frame", "No need for their approval", "Set limits"] },
  { id: "keeping-your-creative-freedom", lang: "en", theme: "Creator & Influence", collection: "creator",
    title: "Keeping Your Creative Freedom",
    blurb: "Evolving without 'betraying' your community: you have the right to evolve, reframe 'they'll hate me if I change', your right not to be frozen, bring your audience with you. 4 approaches.",
    pdf: "keeping-your-creative-freedom-4-approaches.pdf", priceCents: 999, currency: "eur",
    bullets: ["You have the right to evolve", "Not a hostage of your image", "Bring the aligned"] },
  { id: "online-image-vs-real-life", lang: "en", theme: "Creator & Influence", collection: "creator",
    title: "Online Image vs Real Life",
    blurb: "When you feel 'fake': a normal gap up to a point, reframe 'I'm an impostor', reconcile your two sides, narrow the gap where it weighs. 4 approaches.",
    pdf: "online-image-vs-real-life-4-approaches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Curation ≠ lying", "Real and imperfect", "Narrow the gap"] },
] as const;
