// Lot "Résilience 2" (Identité & Résilience). Upload dans lib/proGuides19.ts. PDF dans public/guides/.
export const PRO_GUIDES_19 = [
  // ---- FR ----
  { id: "faire-taire-critique-interieur", lang: "fr", theme: "Identité & Résilience",
    title: "Faire taire son critique intérieur",
    blurb: "Désarmer la voix qui te dévalorise : comprendre son origine, démasquer ses distorsions, et cultiver à la place un allié intérieur qui te soutient. 4 approches.",
    pdf: "faire-taire-critique-interieur-4-approches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["D'où vient ta voix critique", "Démasquer les distorsions", "Du critique à l'allié"] },
  { id: "rebondir-apres-un-echec", lang: "fr", theme: "Identité & Résilience",
    title: "Rebondir après un échec",
    blurb: "Transformer l'échec en tremplin sans te briser : séparer l'échec de ton identité, recadrer les pensées qui aggravent, en tirer une leçon, et te remettre en route. 4 approches.",
    pdf: "rebondir-apres-un-echec-4-approches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["L'échec n'est pas ton identité", "À sa juste taille", "Apprendre & se relever"] },
  { id: "croissance-post-traumatique", lang: "fr", theme: "Identité & Résilience",
    title: "La croissance post-traumatique",
    blurb: "Comment on peut grandir, à son rythme, après l'épreuve — sans positivité toxique ni obligation. Psychoéducation fondée sur la recherche, avec soin et orientation thérapie. 4 approches.",
    pdf: "croissance-post-traumatique-4-approches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Souffrir ET grandir", "Refuser la positivité toxique", "À ton rythme, accompagné·e"] },
  // ---- EN ----
  { id: "silencing-your-inner-critic", lang: "en", theme: "Identity & Resilience",
    title: "Silencing Your Inner Critic",
    blurb: "Disarm the voice that puts you down: understand its origin, unmask its distortions, and grow instead an inner ally that supports you. 4 approaches.",
    pdf: "silencing-your-inner-critic-4-approaches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Where the voice comes from", "Unmask the distortions", "From critic to ally"] },
  { id: "bouncing-back-from-failure", lang: "en", theme: "Identity & Resilience",
    title: "Bouncing Back From Failure",
    blurb: "Turn failure into a stepping stone without breaking: separate failure from your identity, reframe worsening thoughts, draw a lesson, and get moving again. 4 approaches.",
    pdf: "bouncing-back-from-failure-4-approaches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Failure isn't your identity", "Right size", "Learn & rise"] },
  { id: "post-traumatic-growth", lang: "en", theme: "Identity & Resilience",
    title: "Post-Traumatic Growth",
    blurb: "How one can grow, at one's pace, after hardship — without toxic positivity or obligation. Research-based psychoeducation, with care and therapy referral. 4 approaches.",
    pdf: "post-traumatic-growth-4-approaches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Suffer AND grow", "Refuse toxic positivity", "At your pace, supported"] },
] as const;
