// Lot 2 "monde pro" (4 FR + 4 EN). Upload dans lib/proGuides2.ts. PDF dans public/guides/.
export const PRO_GUIDES_2 = [
  // ---- FR : thème Travail ----
  { id: "negocier-son-salaire", lang: "fr", theme: "Travail",
    title: "Négocier son salaire",
    blurb: "Demander ce que tu vaux, sans trembler : dépasser la gêne, préparer et mener ta négo. 4 approches + conseils & tips.",
    pdf: "negocier-son-salaire-4-approches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Dépasse ce qui te bloque", "Prépare ta demande chiffrée", "Mène la négo avec méthode"] },
  { id: "prevenir-burnout", lang: "fr", theme: "Travail",
    title: "Prévenir & guérir du burnout",
    blurb: "Reconnaître les signaux, comprendre, et te relever du burnout — entouré·e. 4 approches + conseils & tips.",
    pdf: "prevenir-burnout-4-approches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Repère les signaux tôt", "Pose des limites", "Te reconstruire, entouré·e"] },
  { id: "le-code-switching", lang: "fr", theme: "Travail",
    title: "Le code-switching",
    blurb: "Le coût caché de t'adapter en permanence — et comment reprendre du choix. 4 approches + conseils & tips.",
    pdf: "le-code-switching-4-approches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Valide ce que tu vis", "Mesure ce que ça te coûte", "Reprends du choix"] },
  { id: "manager-equipe-inclusive", lang: "fr", theme: "Travail",
    title: "Manager une équipe inclusive",
    blurb: "Créer une équipe où chacun·e peut donner le meilleur : sécurité psychologique + pratiques concrètes. 4 approches + conseils & tips.",
    pdf: "manager-equipe-inclusive-4-approches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Repère tes angles morts", "Crée la sécurité psychologique", "Des pratiques concrètes"] },
  // ---- EN : theme Career ----
  { id: "negotiating-your-salary", lang: "en", theme: "Career",
    title: "Negotiating Your Salary",
    blurb: "Ask for what you're worth, without trembling: move past the discomfort, prepare and run your negotiation. 4 approaches + tips.",
    pdf: "negotiating-your-salary-4-approaches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Move past what blocks you", "Prepare a quantified ask", "Run the negotiation with method"] },
  { id: "preventing-burnout", lang: "en", theme: "Career",
    title: "Preventing & Recovering from Burnout",
    blurb: "Recognize the signals, understand, and recover from burnout — supported. 4 approaches + tips.",
    pdf: "preventing-burnout-4-approaches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Spot the signals early", "Set limits", "Rebuild, supported"] },
  { id: "code-switching", lang: "en", theme: "Career",
    title: "Code-Switching",
    blurb: "The hidden cost of adapting all the time — and how to reclaim choice. 4 approaches + tips.",
    pdf: "code-switching-4-approaches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Validates what you live", "Measure what it costs you", "Reclaim choice"] },
  { id: "managing-an-inclusive-team", lang: "en", theme: "Career",
    title: "Managing an Inclusive Team",
    blurb: "Build a team where everyone gives their best: psychological safety + concrete practices. 4 approaches + tips.",
    pdf: "managing-an-inclusive-team-4-approaches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Spot your blind spots", "Create psychological safety", "Concrete practices"] },
] as const;
