// Collection "Relations plurielles / Polygamie" — lot 1. Upload dans lib/proGuides23.ts. PDF dans public/guides/.
export const PRO_GUIDES_23 = [
  // ---- FR ----
  { id: "coepouses-apaiser-rivalites", lang: "fr", theme: "Bien-être & soi", collection: "polygamie",
    title: "Coépouses : apaiser les rivalités",
    blurb: "Sortir de la guerre entre coépouses et protéger ta paix : comprendre comment le système fabrique la rivalité, sortir de la comparaison, refuser la triangulation, poser un cadre. 4 approches.",
    pdf: "coepouses-apaiser-rivalites-4-approches.pdf", priceCents: 999, currency: "eur",
    bullets: ["La rivalité fabriquée", "Protéger ta paix", "Refuser la triangulation"] },
  { id: "partager-lepoux", lang: "fr", theme: "Bien-être & soi", collection: "polygamie",
    title: "Partager l'époux",
    blurb: "Faire la paix avec le partage — ou clarifier ce que tu veux : nommer le deuil de l'exclusivité, recadrer les jours sans lui, remplir TES jours, exprimer tes besoins et limites. 4 approches.",
    pdf: "partager-lepoux-4-approches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Le deuil de l'exclusivité", "Tes jours à toi", "Besoins & limites"] },
  { id: "enfants-dans-la-polygamie", lang: "fr", theme: "Bien-être & soi", collection: "polygamie",
    title: "Les enfants dans la polygamie",
    blurb: "Protéger tes enfants — et toi — dans une famille plurielle : les tenir à l'écart des conflits d'adultes, transformer l'inquiétude en action, défendre leurs besoins essentiels. 4 approches.",
    pdf: "enfants-dans-la-polygamie-4-approches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Les préserver des conflits", "De l'inquiétude à l'action", "Défendre leurs besoins"] },
  { id: "quand-lepoux-en-prefere-une-autre", lang: "fr", theme: "Bien-être & soi", collection: "polygamie",
    title: "Quand l'époux en préfère une autre",
    blurb: "Quand tu te sens mise de côté : préserver ta valeur. Nommer ta peine sans te juger, séparer son comportement de ta valeur, reconstruire ton estime, distinguer peine/injustice/négligence. 4 approches.",
    pdf: "quand-lepoux-en-prefere-une-autre-4-approches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Sa préférence ≠ ta valeur", "Reconstruire ton estime", "Peine, injustice ou négligence ?"] },
  { id: "te-sentir-desirable", lang: "fr", theme: "Bien-être & soi", collection: "polygamie",
    title: "Te sentir désirable et vivante",
    blurb: "Te réapproprier ton corps, ton désir et ta lumière — pour toi, pas pour son regard : sortir du concours de désirabilité, recadrer ce qui t'éteint, te reconnecter à ce qui te fait vibrer. 4 approches.",
    pdf: "te-sentir-desirable-4-approches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Pas un concours", "Te reconnecter à ton corps", "Nourrir ta vie"] },
  { id: "inegalites-et-tensions", lang: "fr", theme: "Bien-être & soi", collection: "polygamie",
    title: "Inégalités et tensions : poser un cadre juste",
    blurb: "Repérer ce qui est juste, désamorcer les tensions : distinguer friction et injustice, revenir aux faits, te tenir debout sur ton droit au respect, poser un cadre et repérer les lignes rouges. 4 approches.",
    pdf: "inegalites-et-tensions-4-approches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Friction ou injustice ?", "Ton droit au respect", "Cadre & lignes rouges"] },
  // ---- EN ----
  { id: "co-wives-easing-rivalry", lang: "en", theme: "Wellbeing & Self", collection: "polygamy",
    title: "Co-Wives: Easing Rivalry",
    blurb: "Step out of the war between co-wives and protect your peace: see how the system builds rivalry, leave comparison, refuse triangulation, set a frame. 4 approaches.",
    pdf: "co-wives-easing-rivalry-4-approaches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Manufactured rivalry", "Protect your peace", "Refuse triangulation"] },
  { id: "sharing-your-husband", lang: "en", theme: "Wellbeing & Self", collection: "polygamy",
    title: "Sharing Your Husband",
    blurb: "Make peace with sharing — or clarify what you want: name the grief of exclusivity, reframe nights without him, fill YOUR days, express your needs and limits. 4 approaches.",
    pdf: "sharing-your-husband-4-approaches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Grieving exclusivity", "Your own days", "Needs & limits"] },
  { id: "children-in-polygamy", lang: "en", theme: "Wellbeing & Self", collection: "polygamy",
    title: "Children in Polygamy",
    blurb: "Protect your children — and yourself — in a plural family: keep them out of adult conflicts, turn worry into action, defend their essential needs. 4 approaches.",
    pdf: "children-in-polygamy-4-approaches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Shield them from conflict", "Worry into action", "Defend their needs"] },
  { id: "when-your-husband-prefers-another", lang: "en", theme: "Wellbeing & Self", collection: "polygamy",
    title: "When Your Husband Prefers Another",
    blurb: "When you feel set aside: protect your worth. Name your pain without judging yourself, separate his behavior from your worth, rebuild your esteem, tell hurt/injustice/neglect apart. 4 approaches.",
    pdf: "when-your-husband-prefers-another-4-approaches.pdf", priceCents: 999, currency: "eur",
    bullets: ["His preference ≠ your worth", "Rebuild your esteem", "Hurt, injustice or neglect?"] },
  { id: "feeling-desirable-again", lang: "en", theme: "Wellbeing & Self", collection: "polygamy",
    title: "Feeling Desirable Again",
    blurb: "Reclaim your body, your desire and your light — for you, not his gaze: leave the desirability contest, reframe what dims you, reconnect to what lights you up. 4 approaches.",
    pdf: "feeling-desirable-again-4-approaches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Not a contest", "Reconnect to your body", "Nourish your life"] },
  { id: "inequalities-and-tensions", lang: "en", theme: "Wellbeing & Self", collection: "polygamy",
    title: "Inequalities and Tensions: Setting a Fair Frame",
    blurb: "Spot what's fair, defuse tensions: tell friction from injustice, return to facts, stand tall on your right to respect, set a frame and spot the red lines. 4 approaches.",
    pdf: "inequalities-and-tensions-4-approaches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Friction or injustice?", "Your right to respect", "Frame & red lines"] },
] as const;
