// 6 guides "monde professionnel" (3 FR + 3 EN). Upload dans lib/proGuides.ts.
// Thème : "Travail" (FR) / "Career" (EN). PDF dans public/guides/.
export const PRO_GUIDES = [
  // ---- FR : thème Travail ----
  { id: "confiance-au-travail", lang: "fr", theme: "Travail",
    title: "Confiance au travail",
    blurb: "Oser prendre ta place au travail : transformer le doute, t'affirmer, te rendre visible. 4 approches + conseils & tips.",
    pdf: "confiance-au-travail-4-approches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Comprends l'origine de ton doute", "Recadre les pensées qui freinent", "Pose des actes de confiance"] },
  { id: "etre-la-seule-au-travail", lang: "fr", theme: "Travail",
    title: "Être « la seule » au travail",
    blurb: "Quand tu es la seule femme noire dans la pièce : alléger la charge, te protéger, trouver des appuis. 4 approches + conseils & tips.",
    pdf: "etre-la-seule-au-travail-4-approches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Valide la charge d'être l'exception", "Dépose ce qui n'est pas à toi", "Trouve réseaux & sponsors"] },
  { id: "etre-allie-au-travail", lang: "fr", theme: "Travail",
    title: "Être un·e allié·e au travail",
    blurb: "Passer de l'intention à l'action : devenir un·e allié·e utile au travail. 4 approches + conseils & tips.",
    pdf: "etre-allie-au-travail-4-approches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Repère tes angles morts", "Dépasse la défensive", "Des actes d'allié·e concrets"] },
  // ---- EN : theme Career ----
  { id: "confidence-at-work", lang: "en", theme: "Career",
    title: "Confidence at Work",
    blurb: "Dare to take your place at work: transform doubt, assert yourself, become visible. 4 approaches + tips.",
    pdf: "confidence-at-work-4-approaches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Understand the root of your doubt", "Reframe the thoughts that hold you back", "Take acts of confidence"] },
  { id: "being-the-only-one-at-work", lang: "en", theme: "Career",
    title: "Being the Only One at Work",
    blurb: "When you're the only Black woman in the room: lighten the load, protect yourself, find support. 4 approaches + tips.",
    pdf: "being-the-only-one-at-work-4-approaches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Validates the load of being the exception", "Set down what isn't yours", "Find networks & sponsors"] },
  { id: "being-an-ally-at-work", lang: "en", theme: "Career",
    title: "Being an Ally at Work",
    blurb: "From intention to action: becoming a useful ally at work. 4 approaches + tips.",
    pdf: "being-an-ally-at-work-4-approaches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Spot your blind spots", "Move past defensiveness", "Concrete acts of allyship"] },
] as const;
