// Lot travail B (4 FR + 4 EN), thème Travail / Career.
// Upload dans lib/proGuides10.ts. PDF dans public/guides/.
// AFFICHAGE FR : section codée en dur SECTIONS -> clé "travail". AFFICHAGE EN : thème "Career".
export const PRO_GUIDES_10 = [
  // ---- FR : thème Travail ----
  { id: "anxiete-de-performance", lang: "fr", theme: "Travail",
    title: "Apprivoiser l'anxiété de performance",
    blurb: "Donner le meilleur sans que la peur te paralyse : comprendre la peur d'échouer, détacher ta valeur du résultat, apprivoiser concrètement. 4 approches + conseils & tips.",
    pdf: "anxiete-de-performance-4-approches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Comprends la peur d'échouer", "Détache valeur & résultat", "Apprivoise le stress"] },
  { id: "gerer-son-temps-deleguer", lang: "fr", theme: "Travail",
    title: "Gérer son temps & déléguer",
    blurb: "Faire l'essentiel sans tout porter : comprendre ce qui t'empêche de déléguer, choisir tes priorités, t'outiller. 4 approches + conseils & tips.",
    pdf: "gerer-son-temps-deleguer-4-approches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Comprends ce qui te surcharge", "Choisis l'essentiel", "Délègue & priorise"] },
  { id: "cheveux-apparence-au-travail", lang: "fr", theme: "Travail",
    title: "Cheveux & apparence au travail",
    blurb: "T'affirmer telle que tu es sans te lisser : la charge de se conformer, t'affirmer, stratégies & droits. 4 approches + ressources.",
    pdf: "cheveux-apparence-au-travail-4-approches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Ce que tu vis est réel", "Affirme-toi telle que tu es", "Stratégies & droits"] },
  { id: "entreprendre-femme-noire", lang: "fr", theme: "Travail",
    title: "Entreprendre en tant que femme noire",
    blurb: "Lancer ton projet malgré les obstacles en plus : dépasser le doute, ta singularité comme force, avancer entourée. 4 approches + ressources.",
    pdf: "entreprendre-femme-noire-4-approches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Dépasse le doute", "Ta singularité, ta force", "Avance entourée"] },
  // ---- EN : theme Career ----
  { id: "taming-performance-anxiety", lang: "en", theme: "Career",
    title: "Taming Performance Anxiety",
    blurb: "Give your best without fear paralyzing you: understand the fear of failing, detach your worth from the outcome, tame it concretely. 4 approaches + tips.",
    pdf: "taming-performance-anxiety-4-approaches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Understand the fear of failing", "Detach worth & outcome", "Tame the stress"] },
  { id: "managing-time-and-delegating", lang: "en", theme: "Career",
    title: "Managing Your Time & Delegating",
    blurb: "Do the essential without carrying it all: understand what stops you delegating, choose your priorities, tool yourself. 4 approaches + tips.",
    pdf: "managing-time-and-delegating-4-approaches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Understand what overloads you", "Choose the essential", "Delegate & prioritize"] },
  { id: "hair-and-appearance-at-work", lang: "en", theme: "Career",
    title: "Hair & Appearance at Work",
    blurb: "Assert yourself as you are without smoothing yourself over: the burden of conforming, assert yourself, strategies & rights. 4 approaches + resources.",
    pdf: "hair-and-appearance-at-work-4-approaches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["What you live is real", "Assert yourself as you are", "Strategies & rights"] },
  { id: "entrepreneurship-as-a-black-woman", lang: "en", theme: "Career",
    title: "Entrepreneurship as a Black Woman",
    blurb: "Launch your project despite the extra obstacles: move past the doubt, your uniqueness as a strength, move forward surrounded. 4 approaches + resources.",
    pdf: "entrepreneurship-as-a-black-woman-4-approaches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Move past the doubt", "Your uniqueness, your strength", "Move forward surrounded"] },
] as const;
