// Lot "Blessures — Tome 2 (Aller plus loin)". Upload dans lib/proGuides21.ts. PDF dans public/guides/.
// Suite/approfondissement de chaque guide de blessure : enfant intérieur, déclencheurs, nouveaux schémas, 30 jours.
export const PRO_GUIDES_21 = [
  // ---- FR ----
  { id: "approfondir-blessure-rejet", lang: "fr", theme: "Bien-être & soi", wound: "rejet", tome: 2,
    title: "Blessure de rejet — Aller plus loin",
    blurb: "Le Tome 2 pour guérir en profondeur : rencontrer et reparenter ton enfant intérieur, désamorcer tes déclencheurs, ancrer de nouveaux schémas, sur un programme de 30 jours.",
    pdf: "approfondir-blessure-rejet-4-approches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Enfant intérieur & reparentage", "Tes déclencheurs", "Programme 30 jours"] },
  { id: "approfondir-blessure-abandon", lang: "fr", theme: "Bien-être & soi", wound: "abandon", tome: 2,
    title: "Blessure d'abandon — Aller plus loin",
    blurb: "Le Tome 2 pour guérir en profondeur : reparenter l'enfant qui a eu peur d'être laissé, t'auto-sécuriser face aux déclencheurs, ancrer de nouveaux schémas, sur 30 jours.",
    pdf: "approfondir-blessure-abandon-4-approches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Enfant intérieur & reparentage", "T'auto-sécuriser", "Programme 30 jours"] },
  { id: "approfondir-blessure-humiliation", lang: "fr", theme: "Bien-être & soi", wound: "humiliation", tome: 2,
    title: "Blessure d'humiliation — Aller plus loin",
    blurb: "Le Tome 2 pour guérir en profondeur : reparenter l'enfant qu'on a couvert de honte, rendre la honte qui n'est pas la tienne, oser tes besoins, sur un programme de 30 jours.",
    pdf: "approfondir-blessure-humiliation-4-approches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Enfant intérieur & reparentage", "Rendre la honte", "Programme 30 jours"] },
  { id: "approfondir-blessure-trahison", lang: "fr", theme: "Bien-être & soi", wound: "trahison", tome: 2,
    title: "Blessure de trahison — Aller plus loin",
    blurb: "Le Tome 2 pour guérir en profondeur : reparenter l'enfant dont la confiance a été brisée, désamorcer le besoin de contrôle, oser de petits paris de confiance, sur 30 jours.",
    pdf: "approfondir-blessure-trahison-4-approches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Enfant intérieur & reparentage", "Désamorcer le contrôle", "Programme 30 jours"] },
  { id: "approfondir-blessure-injustice", lang: "fr", theme: "Bien-être & soi", wound: "injustice", tome: 2,
    title: "Blessure d'injustice — Aller plus loin",
    blurb: "Le Tome 2 pour guérir en profondeur : reparenter l'enfant qui devait être parfait, assouplir ta rigidité, te réautoriser à ressentir, sur un programme de 30 jours.",
    pdf: "approfondir-blessure-injustice-4-approches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Enfant intérieur & reparentage", "Assouplir la rigidité", "Programme 30 jours"] },
  // ---- EN ----
  { id: "deepening-the-rejection-wound", lang: "en", theme: "Wellbeing & Self", wound: "rejet", tome: 2,
    title: "The Rejection Wound — Going Deeper",
    blurb: "Volume 2 to heal deeply: meet and reparent your inner child, defuse your triggers, anchor new patterns, over a 30-day program.",
    pdf: "deepening-the-rejection-wound-4-approaches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Inner child & reparenting", "Your triggers", "30-day program"] },
  { id: "deepening-the-abandonment-wound", lang: "en", theme: "Wellbeing & Self", wound: "abandon", tome: 2,
    title: "The Abandonment Wound — Going Deeper",
    blurb: "Volume 2 to heal deeply: reparent the child who feared being left, self-soothe in the face of triggers, anchor new patterns, over 30 days.",
    pdf: "deepening-the-abandonment-wound-4-approaches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Inner child & reparenting", "Self-soothing", "30-day program"] },
  { id: "deepening-the-humiliation-wound", lang: "en", theme: "Wellbeing & Self", wound: "humiliation", tome: 2,
    title: "The Humiliation Wound — Going Deeper",
    blurb: "Volume 2 to heal deeply: reparent the child who was shamed, return shame that isn't yours, dare your needs, over a 30-day program.",
    pdf: "deepening-the-humiliation-wound-4-approaches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Inner child & reparenting", "Return the shame", "30-day program"] },
  { id: "deepening-the-betrayal-wound", lang: "en", theme: "Wellbeing & Self", wound: "trahison", tome: 2,
    title: "The Betrayal Wound — Going Deeper",
    blurb: "Volume 2 to heal deeply: reparent the child whose trust was broken, defuse the need for control, dare small bets of trust, over 30 days.",
    pdf: "deepening-the-betrayal-wound-4-approaches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Inner child & reparenting", "Defuse control", "30-day program"] },
  { id: "deepening-the-injustice-wound", lang: "en", theme: "Wellbeing & Self", wound: "injustice", tome: 2,
    title: "The Injustice Wound — Going Deeper",
    blurb: "Volume 2 to heal deeply: reparent the child who had to be perfect, soften your rigidity, let yourself feel again, over a 30-day program.",
    pdf: "deepening-the-injustice-wound-4-approaches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Inner child & reparenting", "Soften rigidity", "30-day program"] },
] as const;
