// Collection "Héritage & Transmission" (trauma transgénérationnel). Upload dans lib/proGuides37.ts. PDF dans public/guides/.
export const PRO_GUIDES_37 = [
  // ---- FR ----
  { id: "trauma-transgenerationnel", lang: "fr", theme: "Héritage & Transmission", collection: "transmission",
    title: "Le trauma transgénérationnel",
    blurb: "Ce qui se transmet vraiment : la voie relationnelle (la mieux établie), recadrer « je suis condamné·e à répéter », honorer ta lignée et écrire ta page, voir les schémas familiaux. 4 approches.",
    pdf: "trauma-transgenerationnel-4-approches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["La voie relationnelle", "Un héritage n'est pas un destin", "Voir les schémas familiaux"] },
  { id: "epigenetique-du-trauma", lang: "fr", theme: "Héritage & Transmission", collection: "transmission",
    title: "L'épigénétique du trauma",
    blurb: "Quand le vécu marque l'expression des gènes : ce que dit (et ne dit pas) la science, recadrer « mes gènes me condamnent », tu n'es pas réductible à ta biologie, l'environnement a son mot à dire. 4 approches.",
    pdf: "epigenetique-du-trauma-4-approches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Prometteur, pas prouvé", "Pas un verrou définitif", "L'environnement compte"] },
  { id: "secrets-et-non-dits-de-famille", lang: "fr", theme: "Héritage & Transmission", collection: "transmission",
    title: "Les secrets et non-dits de famille",
    blurb: "Ce qui pèse en silence : le poids des non-dits, recadrer « je dois protéger le secret », ton droit à ta propre vérité, briser le silence avec tact. 4 approches.",
    pdf: "secrets-et-non-dits-de-famille-4-approches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Le silence pèse", "Ton droit à ta vérité", "Briser le silence avec tact"] },
  { id: "briser-le-cycle", lang: "fr", theme: "Héritage & Transmission", collection: "transmission",
    title: "Briser le cycle",
    blurb: "Ne pas transmettre à tes enfants : le « briseur de cycle », recadrer « je vais forcément reproduire », tu peux être celui/celle qui change, conscience + réparation + nouveaux gestes. 4 approches.",
    pdf: "briser-le-cycle-4-approches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Conscient = choix", "Pas de fatalité", "Réparer, pas parfaire"] },
  { id: "memoires-traumatiques", lang: "fr", theme: "Héritage & Transmission", collection: "transmission",
    title: "Les mémoires traumatiques",
    blurb: "Comment le corps et l'esprit gardent la trace : c'est de la survie pas de la faiblesse, recadrer « je suis brisé·e à jamais », compassion pas jugement, réguler et se faire accompagner. 4 approches.",
    pdf: "memoires-traumatiques-4-approches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Le corps garde la trace", "Le cerveau peut se réorganiser", "Réguler & être accompagné·e"] },
  { id: "guerir-l-heritage", lang: "fr", theme: "Héritage & Transmission", collection: "transmission",
    title: "Guérir l'héritage",
    blurb: "Te réapproprier ton histoire : donner du sens pas effacer, questionner les croyances héritées, devenir l'auteur·e de ton récit, rituels/paroles/accompagnement. 4 approches.",
    pdf: "guerir-l-heritage-4-approches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Intégrer, pas effacer", "Choisir tes croyances", "Garder le précieux, déposer le poids"] },
  // ---- EN ----
  { id: "transgenerational-trauma", lang: "en", theme: "Legacy & Transmission", collection: "transmission",
    title: "Transgenerational Trauma",
    blurb: "What truly passes down: the relational route (best established), reframe 'I'm doomed to repeat', honor your lineage and write your page, see the family patterns. 4 approaches.",
    pdf: "transgenerational-trauma-4-approaches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["The relational route", "A legacy isn't a fate", "See the family patterns"] },
  { id: "the-epigenetics-of-trauma", lang: "en", theme: "Legacy & Transmission", collection: "transmission",
    title: "The Epigenetics of Trauma",
    blurb: "When experience marks gene expression: what science says (and doesn't), reframe 'my genes condemn me', you aren't reducible to your biology, the environment has a say. 4 approaches.",
    pdf: "the-epigenetics-of-trauma-4-approaches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Promising, not proven", "Not a permanent lock", "Environment matters"] },
  { id: "family-secrets-and-silences", lang: "en", theme: "Legacy & Transmission", collection: "transmission",
    title: "Family Secrets and Silences",
    blurb: "What weighs in silence: the weight of the unspoken, reframe 'I must protect the secret', your right to your own truth, break the silence with tact. 4 approaches.",
    pdf: "family-secrets-and-silences-4-approaches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["The silence weighs", "Your right to your truth", "Break the silence with tact"] },
  { id: "breaking-the-cycle", lang: "en", theme: "Legacy & Transmission", collection: "transmission",
    title: "Breaking the Cycle",
    blurb: "Not passing it to your children: the 'cycle breaker', reframe 'I'll inevitably repeat', you can be the one who changes, awareness + repair + new gestures. 4 approaches.",
    pdf: "breaking-the-cycle-4-approaches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Aware = choice", "Not a fate", "Repair, not perfect"] },
  { id: "traumatic-memories", lang: "en", theme: "Legacy & Transmission", collection: "transmission",
    title: "Traumatic Memories",
    blurb: "How the body and mind keep the trace: it's survival not weakness, reframe 'I'm broken forever', compassion not judgment, regulate and get support. 4 approaches.",
    pdf: "traumatic-memories-4-approaches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["The body keeps the trace", "The brain can reorganize", "Regulate & get support"] },
  { id: "healing-your-inheritance", lang: "en", theme: "Legacy & Transmission", collection: "transmission",
    title: "Healing Your Inheritance",
    blurb: "Reclaiming your story: give meaning not erase, question inherited beliefs, become the author of your story, rituals/words/support. 4 approaches.",
    pdf: "healing-your-inheritance-4-approaches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Integrate, not erase", "Choose your beliefs", "Keep the precious, set down the weight"] },
] as const;
