// Collection "Créateur·rice & Influence" — LOT 4/5 (Crises). Upload dans lib/proGuides35.ts. PDF dans public/guides/.
export const PRO_GUIDES_35 = [
  // ---- FR ----
  { id: "survivre-au-bad-buzz", lang: "fr", theme: "Créateur·rice & Influence", collection: "creator",
    title: "Survivre à un bad buzz",
    blurb: "La crise virale : la mécanique de l'emballement, recadrer « ma vie est finie », protéger ta santé mentale d'abord, réagir à froid (ou pas) puis se reconstruire. 4 approches.",
    pdf: "survivre-au-bad-buzz-4-approches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["La vague finit par passer", "Ta santé mentale d'abord", "Jamais à chaud"] },
  { id: "gerer-le-cyberharcelement", lang: "fr", theme: "Créateur·rice & Influence", collection: "creator",
    title: "Gérer le cyberharcèlement",
    blurb: "Le harcèlement ciblé (≠ haters) : le reconnaître, recadrer « je dois encaisser », ce n'est jamais ta faute, documenter/signaler/demander de l'aide (recours en cas de menaces). 4 approches.",
    pdf: "gerer-le-cyberharcelement-4-approches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["C'est grave, pas « le jeu »", "Ce n'est pas ta faute", "Documenter, signaler, agir"] },
  { id: "encaisser-un-flop", lang: "fr", theme: "Créateur·rice & Influence", collection: "creator",
    title: "Encaisser un flop ou un échec public",
    blurb: "La vidéo qui fait un bide : l'algorithme n'est pas un verdict, recadrer « tout le monde a vu mon échec », un échec ≠ ta valeur, analyser/itérer/repartir. 4 approches.",
    pdf: "encaisser-un-flop-4-approches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Un flop est une donnée", "Un échec ≠ ta valeur", "Analyser & repartir"] },
  { id: "assumer-et-reparer-une-erreur", lang: "fr", theme: "Créateur·rice & Influence", collection: "creator",
    title: "Assumer et réparer une vraie erreur",
    blurb: "Quand tu as réellement merdé : l'erreur fait partie du jeu, recadrer « je suis irrécupérable », une erreur ne te définit pas, excuses sincères + réparation puis avancer. 4 approches.",
    pdf: "assumer-et-reparer-une-erreur-4-approches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Une erreur se répare", "Assume sans t'auto-détruire", "Reconnaître + réparer"] },
  { id: "la-peur-du-succes", lang: "fr", theme: "Créateur·rice & Influence", collection: "creator",
    title: "La peur du succès (et de la chute)",
    blurb: "Le vertige quand ça décolle : la peur du succès est réelle, recadrer « je ne mérite pas ça », t'autoriser à réussir, gérer la croissance sans paniquer. 4 approches.",
    pdf: "la-peur-du-succes-4-approches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Repérer l'auto-sabotage", "T'autoriser à réussir", "Systèmes + soutien"] },
  { id: "passer-un-palier", lang: "fr", theme: "Créateur·rice & Influence", collection: "creator",
    title: "Passer un palier (10k, 100k, 1M…)",
    blurb: "Chaque seuil rebat les cartes : comprendre ce qui change, recadrer « je ne mérite pas d'être ici », grandir avec ton succès, adapter tes systèmes et garder ton pourquoi. 4 approches.",
    pdf: "passer-un-palier-4-approches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Une transition à traverser", "Tu y as ta place", "Adapter, garder ton pourquoi"] },
  // ---- EN ----
  { id: "surviving-a-bad-buzz", lang: "en", theme: "Creator & Influence", collection: "creator",
    title: "Surviving a Bad Buzz",
    blurb: "The viral crisis: the mechanics of the pile-on, reframe 'my life is over', protect your mental health first, react calmly (or not) then rebuild. 4 approaches.",
    pdf: "surviving-a-bad-buzz-4-approaches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["The wave eventually passes", "Your mental health first", "Never in the heat"] },
  { id: "handling-cyberbullying", lang: "en", theme: "Creator & Influence", collection: "creator",
    title: "Handling Cyberbullying",
    blurb: "Targeted harassment (≠ haters): recognize it, reframe 'I must take it', it's never your fault, document/report/seek help (recourse if threats). 4 approaches.",
    pdf: "handling-cyberbullying-4-approaches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Serious, not 'the game'", "It's not your fault", "Document, report, act"] },
  { id: "handling-a-public-flop", lang: "en", theme: "Creator & Influence", collection: "creator",
    title: "Handling a Public Flop",
    blurb: "The video that bombs: the algorithm isn't a verdict, reframe 'everyone saw I failed', a failure ≠ your worth, analyze/iterate/restart. 4 approaches.",
    pdf: "handling-a-public-flop-4-approaches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["A flop is data", "A failure ≠ your worth", "Analyze & restart"] },
  { id: "owning-and-repairing-a-mistake", lang: "en", theme: "Creator & Influence", collection: "creator",
    title: "Owning and Repairing a Real Mistake",
    blurb: "When you actually messed up: mistakes are part of the game, reframe 'I'm beyond saving', a mistake doesn't define you, sincere apology + repair then move on. 4 approaches.",
    pdf: "owning-and-repairing-a-mistake-4-approaches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["A mistake can be repaired", "Own it without self-destructing", "Acknowledge + repair"] },
  { id: "the-fear-of-success", lang: "en", theme: "Creator & Influence", collection: "creator",
    title: "The Fear of Success (and of Falling)",
    blurb: "The dizziness when it takes off: fear of success is real, reframe 'I don't deserve this', allow yourself to succeed, manage growth without panicking. 4 approaches.",
    pdf: "the-fear-of-success-4-approaches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Spot the self-sabotage", "Allow yourself to succeed", "Systems + support"] },
  { id: "reaching-a-new-level", lang: "en", theme: "Creator & Influence", collection: "creator",
    title: "Reaching a New Level (10k, 100k, 1M…)",
    blurb: "Each threshold reshuffles the deck: understand what changes, reframe 'I don't deserve to be here', grow with your success, adapt your systems and keep your why. 4 approaches.",
    pdf: "reaching-a-new-level-4-approaches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["A transition to cross", "You belong here", "Adapt, keep your why"] },
] as const;
