// Parcours "Dating" (Amour & Relations), mixte hommes/femmes, recherche -> engagement.
// Upload dans lib/proGuides28.ts. PDF dans public/guides/.
export const PRO_GUIDES_28 = [
  // ---- FR ---- (ordre du parcours : 1 -> 6)
  { id: "savoir-ce-que-tu-cherches", lang: "fr", theme: "Amour & Relations", collection: "dating", order: 1,
    title: "Savoir ce que tu cherches vraiment",
    blurb: "Étape 1 du parcours dating — La clarté avant la rencontre : tes valeurs et besoins, recadrer ce qui te fait brader, repérer ton schéma, distinguer non-négociables et préférences. 4 approches.",
    pdf: "savoir-ce-que-tu-cherches-4-approches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["La clarté = ta boussole", "Repérer ton schéma", "Non-négociables vs préférences"] },
  { id: "oser-te-montrer-rencontrer", lang: "fr", theme: "Amour & Relations", collection: "dating", order: 2,
    title: "Oser te montrer et rencontrer",
    blurb: "Étape 2 — Sortir de l'ombre sans te trahir : la visibilité comme passage obligé, vaincre la peur du rejet, te montrer vrai (pas parfait), choisir des terrains qui te ressemblent. 4 approches.",
    pdf: "oser-te-montrer-rencontrer-4-approches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["La visibilité, passage obligé", "Rejet ≠ valeur", "Authentique, pas parfait"] },
  { id: "le-premier-rendez-vous", lang: "fr", theme: "Amour & Relations", collection: "dating", order: 3,
    title: "Le premier rendez-vous",
    blurb: "Étape 3 — Être toi et bien lire l'autre : une évaluation mutuelle pas un examen, gérer le trac, miser sur la présence, lire les drapeaux verts/rouges et rester en sécurité. 4 approches.",
    pdf: "le-premier-rendez-vous-4-approches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Évaluation mutuelle", "Présence > performance", "Drapeaux & sécurité"] },
  { id: "creer-du-lien-sans-te-perdre", lang: "fr", theme: "Amour & Relations", collection: "dating", order: 4,
    title: "Créer du lien sans te perdre",
    blurb: "Étape 4 — Doser l'élan, garder ton équilibre : laisser le lien grandir sans l'inventer, ne pas sur-investir, garder ta vie, doser la vulnérabilité et vérifier la réciprocité. 4 approches.",
    pdf: "creer-du-lien-sans-te-perdre-4-approches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Observer, pas projeter", "Garder ta vie", "La réciprocité, ton indicateur"] },
  { id: "decrypter-les-signaux", lang: "fr", theme: "Amour & Relations", collection: "dating", order: 5,
    title: "Décrypter les signaux et éviter les pièges",
    blurb: "Étape 5 — Ghosting, jeux, anxieux/évitant : nommer les pièges pour reprendre le pouvoir, sortir de l'auto-accusation, choisir ta paix plutôt que la chasse, juger la cohérence. 4 approches.",
    pdf: "decrypter-les-signaux-4-approches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Les jeux parlent d'eux", "Ne pas chasser l'ambivalence", "Juger la cohérence"] },
  { id: "definir-la-relation-engagement", lang: "fr", theme: "Amour & Relations", collection: "dating", order: 6,
    title: "Définir la relation et avancer vers l'engagement",
    blurb: "Étape 6 — Du « on est quoi ? » à un vrai projet : sortir du flou, vaincre la peur de « faire fuir », assumer ton désir d'engagement, oser la conversation et poser des pas concrets. 4 approches.",
    pdf: "definir-la-relation-engagement-4-approches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Définir, pas subir le flou", "La clarté filtre", "Construire à deux"] },
  // ---- EN ----
  { id: "know-what-you-truly-want", lang: "en", theme: "Love & Relationships", collection: "dating", order: 1,
    title: "Knowing What You Truly Want",
    blurb: "Step 1 of the dating journey — Clarity before the encounter: your values and needs, reframe what makes you settle, spot your pattern, tell non-negotiables from preferences. 4 approaches.",
    pdf: "know-what-you-truly-want-4-approaches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Clarity = your compass", "Spot your pattern", "Non-negotiables vs preferences"] },
  { id: "putting-yourself-out-there", lang: "en", theme: "Love & Relationships", collection: "dating", order: 2,
    title: "Putting Yourself Out There",
    blurb: "Step 2 — Stepping into the light without betraying yourself: visibility as the necessary passage, beating the fear of rejection, showing up real (not perfect), choosing grounds that fit you. 4 approaches.",
    pdf: "putting-yourself-out-there-4-approaches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Visibility, the passage", "Rejection ≠ worth", "Authentic, not perfect"] },
  { id: "the-first-date", lang: "en", theme: "Love & Relationships", collection: "dating", order: 3,
    title: "The First Date",
    blurb: "Step 3 — Being yourself and reading the other: a mutual evaluation not an exam, handling nerves, betting on presence, reading green/red flags and staying safe. 4 approaches.",
    pdf: "the-first-date-4-approaches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Mutual evaluation", "Presence > performance", "Flags & safety"] },
  { id: "building-connection-without-losing-yourself", lang: "en", theme: "Love & Relationships", collection: "dating", order: 4,
    title: "Building Connection Without Losing Yourself",
    blurb: "Step 4 — Pacing the rush, keeping your balance: let connection grow without inventing it, don't over-invest, keep your life, pace vulnerability and check reciprocity. 4 approaches.",
    pdf: "building-connection-without-losing-yourself-4-approaches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Observe, don't project", "Keep your life", "Reciprocity is the indicator"] },
  { id: "reading-the-signals", lang: "en", theme: "Love & Relationships", collection: "dating", order: 5,
    title: "Reading the Signals and Avoiding the Traps",
    blurb: "Step 5 — Ghosting, games, anxious/avoidant: name the traps to reclaim your power, leave self-accusation, choose your peace over the chase, judge consistency. 4 approaches.",
    pdf: "reading-the-signals-4-approaches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Games are about them", "Don't chase ambivalence", "Judge consistency"] },
  { id: "defining-the-relationship", lang: "en", theme: "Love & Relationships", collection: "dating", order: 6,
    title: "Defining the Relationship and Moving Toward Commitment",
    blurb: "Step 6 — From 'what are we?' to a real project: leave the vagueness, beat the fear of scaring them off, own your desire for commitment, dare the conversation and take concrete steps. 4 approaches.",
    pdf: "defining-the-relationship-4-approaches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Define, don't endure vagueness", "Clarity filters", "Build together"] },
] as const;
