// Lot "Bien-être sexuel 2" (Intimité & Sexualité, 18+). Upload dans lib/proGuides26.ts. PDF dans public/guides/.
export const PRO_GUIDES_26 = [
  // ---- FR ----
  { id: "plaisir-feminin-orgasme", lang: "fr", theme: "Intimité & Sexualité", adult: true,
    title: "Le plaisir féminin & l'orgasme",
    blurb: "Comprendre ton corps et t'autoriser le plaisir : le rôle central du clitoris, sortir des pensées qui coupent le plaisir, t'autoriser à ressentir, guider et déculpabiliser l'orgasme. 4 approches. 18+",
    pdf: "plaisir-feminin-orgasme-4-approches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Le clitoris est central", "Pas une performance", "Guider & déculpabiliser"] },
  { id: "plaisir-solo-masturbation", lang: "fr", theme: "Intimité & Sexualité", adult: true,
    title: "Le plaisir solo",
    blurb: "Te connaître pour mieux jouir : la masturbation est saine et utile, lever la honte, un territoire à toi, un complément (pas un concurrent) de ta vie de couple. 4 approches. 18+",
    pdf: "plaisir-solo-masturbation-4-approches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Sain & utile", "Un territoire à toi", "Complément, pas concurrent"] },
  { id: "preliminaires-et-lenteur", lang: "fr", theme: "Intimité & Sexualité", adult: true,
    title: "Les préliminaires & la lenteur",
    blurb: "Le désir aime le temps : l'excitation a besoin de monter, lever l'urgence, revenir à la présence et à tout le corps, communiquer ton rythme et cultiver l'anticipation. 4 approches. 18+",
    pdf: "preliminaires-et-lenteur-4-approches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["La lenteur EST le plaisir", "Tout le corps", "Rythme & anticipation"] },
  { id: "sextoys-oser-les-integrer", lang: "fr", theme: "Intimité & Sexualité", adult: true,
    title: "Sextoys : oser les intégrer",
    blurb: "Un plus pour ton plaisir, solo ou à deux : un outil pas un remplaçant, lever la gêne, légitimer ta curiosité, les introduire avec communication, consentement et hygiène. 4 approches. 18+",
    pdf: "sextoys-oser-les-integrer-4-approches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Un plus, pas un manque", "Ta curiosité est légitime", "Solo ou à deux, en sécurité"] },
  { id: "cunnilingus-sans-tabou", lang: "fr", theme: "Intimité & Sexualité", adult: true,
    title: "Le cunnilingus, sans tabou",
    blurb: "Recevoir du plaisir, sans gêne ni pression : ton corps est normal, lever la honte de recevoir, tu mérites de recevoir autant que de donner, détente, guidage doux et réciprocité. 4 approches. 18+",
    pdf: "cunnilingus-sans-tabou-4-approches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Ton corps est normal", "Tu mérites de recevoir", "Détente & réciprocité"] },
  { id: "bdsm-jeux-de-pouvoir", lang: "fr", theme: "Intimité & Sexualité", adult: true,
    title: "BDSM & jeux de pouvoir, en confiance",
    blurb: "Explorer domination et soumission en sécurité : du jeu consenti pas de la violence, lever la honte, légitimer tes désirs de jeu, les piliers — consentement, safe-word, after-care. 4 approches. 18+",
    pdf: "bdsm-jeux-de-pouvoir-4-approches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Jeu consenti, pas violence", "Tes désirs sont valides", "Safe-word & after-care"] },
  // ---- EN ----
  { id: "female-pleasure-and-orgasm", lang: "en", theme: "Intimacy & Sexuality", adult: true,
    title: "Female Pleasure & Orgasm",
    blurb: "Understand your body and allow yourself pleasure: the clitoris's central role, leave the thoughts that cut pleasure, allow yourself to feel, guide and de-guilt orgasm. 4 approaches. 18+",
    pdf: "female-pleasure-and-orgasm-4-approaches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["The clitoris is central", "Not a performance", "Guide & de-guilt"] },
  { id: "solo-pleasure-masturbation", lang: "en", theme: "Intimacy & Sexuality", adult: true,
    title: "Solo Pleasure",
    blurb: "Know yourself to enjoy more: masturbation is healthy and useful, lift the shame, a territory of your own, a complement (not a competitor) to your couple life. 4 approaches. 18+",
    pdf: "solo-pleasure-masturbation-4-approaches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Healthy & useful", "A territory of your own", "Complement, not competitor"] },
  { id: "foreplay-and-slowness", lang: "en", theme: "Intimacy & Sexuality", adult: true,
    title: "Foreplay & Slowness",
    blurb: "Desire loves time: arousal needs to build, lift the urgency, return to presence and the whole body, communicate your rhythm and cultivate anticipation. 4 approaches. 18+",
    pdf: "foreplay-and-slowness-4-approaches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Slowness IS pleasure", "The whole body", "Rhythm & anticipation"] },
  { id: "sex-toys-bringing-them-in", lang: "en", theme: "Intimacy & Sexuality", adult: true,
    title: "Sex Toys: Bringing Them In",
    blurb: "A plus for your pleasure, solo or together: a tool not a replacement, lift the awkwardness, legitimize your curiosity, bring them in with communication, consent and hygiene. 4 approaches. 18+",
    pdf: "sex-toys-bringing-them-in-4-approaches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["A plus, not a lack", "Your curiosity is legitimate", "Solo or together, safely"] },
  { id: "cunnilingus-without-taboo", lang: "en", theme: "Intimacy & Sexuality", adult: true,
    title: "Cunnilingus, Without Taboo",
    blurb: "Receive pleasure, without awkwardness or pressure: your body is normal, lift the shame of receiving, you deserve to receive as much as to give, relaxation, gentle guiding and reciprocity. 4 approaches. 18+",
    pdf: "cunnilingus-without-taboo-4-approaches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Your body is normal", "You deserve to receive", "Relaxation & reciprocity"] },
  { id: "bdsm-power-play-with-confidence", lang: "en", theme: "Intimacy & Sexuality", adult: true,
    title: "BDSM & Power Play, With Confidence",
    blurb: "Explore domination and submission safely: consensual play not violence, lift the shame, legitimize your play desires, the pillars — consent, safe-word, aftercare. 4 approaches. 18+",
    pdf: "bdsm-power-play-with-confidence-4-approaches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Consensual play, not violence", "Your desires are valid", "Safe-word & aftercare"] },
] as const;
