// Lot travail A "Carrière + rebond" (4 FR + 4 EN), thème Travail / Career.
// Upload dans lib/proGuides9.ts. PDF dans public/guides/.
// AFFICHAGE FR : section codée en dur SECTIONS -> clé "travail". AFFICHAGE EN : thème "Career".
export const PRO_GUIDES_9 = [
  // ---- FR : thème Travail ----
  { id: "reussir-sa-reconversion", lang: "fr", theme: "Travail",
    title: "Réussir une reconversion professionnelle",
    blurb: "Changer de voie avec méthode et courage : démêler ce qui te pousse, clarifier ce qui a du sens, construire ton projet par étapes. 4 approches + conseils & tips.",
    pdf: "reussir-sa-reconversion-4-approches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Démêle envies & peurs", "Clarifie ta boussole", "Construis par étapes"] },
  { id: "rebondir-apres-licenciement", lang: "fr", theme: "Travail",
    title: "Rebondir après un licenciement",
    blurb: "Encaisser puis te relever : traverser le choc, te rappeler ta valeur, repartir posé·e et stratégique. 4 approches + ressources.",
    pdf: "rebondir-apres-licenciement-4-approches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Traverse le choc", "Rappelle-toi ta valeur", "Relève-toi concrètement"] },
  { id: "soigner-son-personal-branding", lang: "fr", theme: "Travail",
    title: "Soigner son personal branding",
    blurb: "Rendre ta valeur visible sans te trahir : dépasser ce qui te freine, une image alignée avec toi, construire ta visibilité. 4 approches + conseils & tips.",
    pdf: "soigner-son-personal-branding-4-approches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Dépasse ce qui te freine", "Une image alignée", "Construis ta visibilité"] },
  { id: "developper-son-reseau", lang: "fr", theme: "Travail",
    title: "Développer son réseau",
    blurb: "Tisser des liens utiles sans faire semblant : dépasser tes blocages, le réseau comme relations sincères, tisser même introverti·e. 4 approches + conseils & tips.",
    pdf: "developper-son-reseau-4-approches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Dépasse tes blocages", "Des relations sincères", "Tisse même introverti·e"] },
  // ---- EN : theme Career ----
  { id: "making-a-career-change", lang: "en", theme: "Career",
    title: "Making a Career Change",
    blurb: "Change paths with method and courage: untangle what pushes you, clarify what matters, build your project step by step. 4 approaches + tips.",
    pdf: "making-a-career-change-4-approaches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Untangle wishes & fears", "Clarify your compass", "Build step by step"] },
  { id: "bouncing-back-after-a-layoff", lang: "en", theme: "Career",
    title: "Bouncing Back After a Layoff",
    blurb: "Take the blow then get back up: move through the shock, remember your worth, restart calm and strategic. 4 approaches + resources.",
    pdf: "bouncing-back-after-a-layoff-4-approaches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Move through the shock", "Remember your worth", "Get back up concretely"] },
  { id: "building-your-personal-brand", lang: "en", theme: "Career",
    title: "Building Your Personal Brand",
    blurb: "Make your value visible without betraying yourself: move past what holds you back, an image aligned with you, build your visibility. 4 approaches + tips.",
    pdf: "building-your-personal-brand-4-approaches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Move past what holds you back", "An aligned image", "Build your visibility"] },
  { id: "building-your-network", lang: "en", theme: "Career",
    title: "Building Your Network",
    blurb: "Weave useful bonds without pretending: move past your blocks, networking as sincere relationships, weave even as an introvert. 4 approaches + tips.",
    pdf: "building-your-network-4-approaches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Move past your blocks", "Sincere relationships", "Weave even as an introvert"] },
] as const;
