// Lot "Résilience" (Identité & Résilience). Upload dans lib/proGuides18.ts. PDF dans public/guides/.
// AFFICHAGE FR : section "identité/résilience" (hardcodée). EN : thème "Identity & Resilience".
export const PRO_GUIDES_18 = [
  // ---- FR : Identité & Résilience ----
  { id: "developper-resilience-emotionnelle", lang: "fr", theme: "Identité & Résilience",
    title: "Développer sa résilience émotionnelle",
    blurb: "Rebondir après l'épreuve : comprendre ta résilience, recadrer les pensées catastrophes, mobiliser tes ressources internes et ton soutien. Le guide pilier de la rubrique. 4 approches.",
    pdf: "developper-resilience-emotionnelle-4-approches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Ce qu'est vraiment la résilience", "Optimisme réaliste", "Tes ressources & ton soutien"] },
  { id: "cultiver-auto-compassion", lang: "fr", theme: "Identité & Résilience",
    title: "Cultiver l'auto-compassion",
    blurb: "Te traiter avec la bienveillance que tu offres aux autres : désarmer ton autocritique, te parler comme à un·e ami·e, et ancrer une voix intérieure plus douce. 4 approches.",
    pdf: "cultiver-auto-compassion-4-approches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Les 3 piliers (Neff)", "Désarmer l'autocritique", "La pause d'auto-compassion"] },
  { id: "faire-face-microagressions", lang: "fr", theme: "Identité & Résilience",
    title: "Faire face aux microagressions",
    blurb: "Comprendre ces petites blessures répétées, ne pas les internaliser, choisir si et comment répondre, et te préserver. Validant et concret. 4 approches.",
    pdf: "faire-face-microagressions-4-approches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Ce n'est pas être « trop sensible »", "Répondre ou pas", "Te préserver & t'entourer"] },
  { id: "naviguer-identite-plurielle", lang: "fr", theme: "Identité & Résilience",
    title: "Naviguer une identité plurielle",
    blurb: "« Ni d'ici, ni de là-bas » : apaiser le sentiment d'entre-deux, recadrer le doute d'appartenance, et faire de ta pluralité une force. 4 approches.",
    pdf: "naviguer-identite-plurielle-4-approches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Le sentiment d'entre-deux", "Ta pluralité comme richesse", "Ton appartenance choisie"] },
  // ---- EN : Identity & Resilience ----
  { id: "building-emotional-resilience", lang: "en", theme: "Identity & Resilience",
    title: "Building Emotional Resilience",
    blurb: "Bounce back from hardship: understand your resilience, reframe catastrophic thoughts, mobilize your inner resources and support. The pillar guide of the section. 4 approaches.",
    pdf: "building-emotional-resilience-4-approaches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["What resilience really is", "Realistic optimism", "Your resources & support"] },
  { id: "cultivating-self-compassion", lang: "en", theme: "Identity & Resilience",
    title: "Cultivating Self-Compassion",
    blurb: "Treat yourself with the kindness you give others: disarm your inner critic, speak to yourself like a friend, and anchor a gentler inner voice. 4 approaches.",
    pdf: "cultivating-self-compassion-4-approaches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["The 3 pillars (Neff)", "Disarm the inner critic", "The self-compassion break"] },
  { id: "coping-with-microaggressions", lang: "en", theme: "Identity & Resilience",
    title: "Coping With Microaggressions",
    blurb: "Understand these small repeated wounds, don't internalize them, choose if and how to respond, and protect yourself. Validating and concrete. 4 approaches.",
    pdf: "coping-with-microaggressions-4-approaches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["It's not being 'too sensitive'", "Respond or not", "Protect & surround yourself"] },
  { id: "navigating-a-plural-identity", lang: "en", theme: "Identity & Resilience",
    title: "Navigating a Plural Identity",
    blurb: "'Not from here, not from there': ease the in-between feeling, reframe the doubt of belonging, and turn your plurality into strength. 4 approaches.",
    pdf: "navigating-a-plural-identity-4-approaches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["The in-between feeling", "Your plurality as richness", "Your chosen belonging"] },
] as const;
