// Collection Dating - "Ou & comment rencontrer" (contextes). Upload dans lib/proGuides29.ts. PDF dans public/guides/.
export const PRO_GUIDES_29 = [
  // ---- FR ----
  { id: "rencontrer-hors-des-applis", lang: "fr", theme: "Amour & Relations", collection: "dating", subcollection: "contextes",
    title: "Rencontrer hors des applis",
    blurb: "L'art de la rencontre dans la vraie vie : les occasions sont partout, lire l'ouverture, vaincre « je vais déranger », ta présence vaut tous les scripts, provoquer la chance en respectant le non. 4 approches.",
    pdf: "rencontrer-hors-des-applis-4-approches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Les occasions sont partout", "Présence > scripts", "Respecter le non"] },
  { id: "reussir-sur-les-applis", lang: "fr", theme: "Amour & Relations", collection: "dating", subcollection: "contextes",
    title: "Réussir sur les applis de rencontre",
    blurb: "Sortir du lot sans t'épuiser : comprendre la mécanique, ton taux de match ≠ ta valeur, un profil vraiment toi qui filtre, des conversations qui mènent vite à une vraie rencontre. 4 approches.",
    pdf: "reussir-sur-les-applis-4-approches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Viser la vraie rencontre", "Profil authentique = filtre", "Éviter le burn-out"] },
  { id: "rencontrer-sur-les-reseaux-sociaux", lang: "fr", theme: "Amour & Relations", collection: "dating", subcollection: "contextes",
    title: "Rencontrer via les réseaux sociaux",
    blurb: "Du DM à la vraie connexion : l'écart image/réalité, oser un DM sincère, aborder par un intérêt vrai (pas une parade), passer au réel en sécurité (anti-catfishing). 4 approches.",
    pdf: "rencontrer-sur-les-reseaux-sociaux-4-approches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Image ≠ personne", "Un DM sincère est normal", "Passer au réel, en sécurité"] },
  { id: "amour-au-travail", lang: "fr", theme: "Amour & Relations", collection: "dating", subcollection: "contextes",
    title: "L'amour au travail",
    blurb: "Quand l'attirance croise le professionnel : les risques spécifiques, JAMAIS de rapport de pouvoir, n'agir que sur un intérêt clair et mutuel, respect absolu du non, discrétion et plan pour l'après. 4 approches.",
    pdf: "amour-au-travail-4-approches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Jamais de rapport de pouvoir", "Intérêt clair et mutuel", "Respect & discrétion"] },
  { id: "le-speed-dating", lang: "fr", theme: "Amour & Relations", collection: "dating", subcollection: "contextes",
    title: "Réussir le speed dating",
    blurb: "Quelques minutes pour sentir une étincelle : une étincelle pas un verdict, la simplicité marque plus que la performance, curiosité sincère, préparer ses questions et relancer vite. 4 approches.",
    pdf: "le-speed-dating-4-approches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Une étincelle, pas un verdict", "Simplicité > performance", "Préparer & relancer"] },
  { id: "rencontrer-en-soiree", lang: "fr", theme: "Amour & Relations", collection: "dating", subcollection: "contextes",
    title: "Rencontrer en soirée",
    blurb: "Entre l'ambiance et la vraie connexion : distinguer la vibe du lien, dompter l'anxiété sociale, le vrai lien naît souvent en marge, alcool et consentement clair, le vrai test c'est le lendemain. 4 approches.",
    pdf: "rencontrer-en-soiree-4-approches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Vibe ≠ vraie connexion", "Consentement clair et lucide", "Le test : le lendemain"] },
  { id: "amour-de-vacances", lang: "fr", theme: "Amour & Relations", collection: "dating", subcollection: "contextes",
    title: "L'amour de vacances",
    blurb: "La bulle, et ce qu'on en fait après : l'effet bulle, savourer sans tout miser sur quelques jours, profiter du présent, garder la grande décision pour le retour (la distance est le vrai test). 4 approches.",
    pdf: "amour-de-vacances-4-approches.pdf", priceCents: 999, currency: "eur",
    bullets: ["L'effet bulle", "Profiter du présent", "La distance, le vrai test"] },
  { id: "d-ami-a-amoureux", lang: "fr", theme: "Amour & Relations", collection: "dating", subcollection: "contextes",
    title: "D'ami·e à amoureux·se",
    blurb: "Oser franchir le pas sans tout perdre : une base solide et un vrai risque, recadrer « je vais tout gâcher », honorer tes sentiments, te déclarer sans pression et gérer l'issue avec dignité. 4 approches.",
    pdf: "d-ami-a-amoureux-4-approches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Base solide + vrai risque", "Honorer tes sentiments", "Oser sans pression"] },
  // ---- EN ----
  { id: "meeting-offline", lang: "en", theme: "Love & Relationships", collection: "dating", subcollection: "contexts",
    title: "Meeting Offline",
    blurb: "The art of meeting in real life: opportunities everywhere, read openness, beat 'I'll be bothering them', your presence beats scripts, make your luck while respecting the no. 4 approaches.",
    pdf: "meeting-offline-4-approaches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Opportunities everywhere", "Presence > scripts", "Respect the no"] },
  { id: "succeeding-on-dating-apps", lang: "en", theme: "Love & Relationships", collection: "dating", subcollection: "contexts",
    title: "Succeeding on Dating Apps",
    blurb: "Stand out without burning out: understand the mechanics, your match rate ≠ your worth, a profile that's truly you and filters, conversations that lead quickly to a real meeting. 4 approaches.",
    pdf: "succeeding-on-dating-apps-4-approaches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Aim for the real meeting", "Authentic profile = filter", "Avoid burnout"] },
  { id: "meeting-on-social-media", lang: "en", theme: "Love & Relationships", collection: "dating", subcollection: "contexts",
    title: "Meeting on Social Media",
    blurb: "From the DM to a real connection: the image/reality gap, dare a sincere DM, approach through real interest (not a display), move to real safely (anti-catfishing). 4 approaches.",
    pdf: "meeting-on-social-media-4-approaches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Image ≠ person", "A sincere DM is normal", "Move to real, safely"] },
  { id: "love-at-work", lang: "en", theme: "Love & Relationships", collection: "dating", subcollection: "contexts",
    title: "Love at Work",
    blurb: "When attraction meets the professional: the specific risks, NEVER a power dynamic, act only on clear mutual interest, absolute respect for the no, discretion and a plan for the after. 4 approaches.",
    pdf: "love-at-work-4-approaches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Never a power dynamic", "Clear, mutual interest", "Respect & discretion"] },
  { id: "speed-dating", lang: "en", theme: "Love & Relationships", collection: "dating", subcollection: "contexts",
    title: "Succeeding at Speed Dating",
    blurb: "A few minutes to feel a spark: a spark not a verdict, simplicity impresses more than performance, sincere curiosity, prepare your questions and follow up fast. 4 approaches.",
    pdf: "speed-dating-4-approaches.pdf", priceCents: 999, currency: "eur",
    bullets: ["A spark, not a verdict", "Simplicity > performance", "Prepare & follow up"] },
  { id: "meeting-at-a-party", lang: "en", theme: "Love & Relationships", collection: "dating", subcollection: "contexts",
    title: "Meeting at a Party",
    blurb: "Between the vibe and real connection: tell the vibe from the bond, tame social anxiety, real bond often grows on the side, alcohol and clear consent, the real test is the next day. 4 approaches.",
    pdf: "meeting-at-a-party-4-approaches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Vibe ≠ real connection", "Clear, lucid consent", "The test: the next day"] },
  { id: "holiday-romance", lang: "en", theme: "Love & Relationships", collection: "dating", subcollection: "contexts",
    title: "Holiday Romance",
    blurb: "The bubble, and what you make of it after: the bubble effect, savor without betting everything on a few days, enjoy the present, keep the big decision for the return (distance is the real test). 4 approaches.",
    pdf: "holiday-romance-4-approaches.pdf", priceCents: 999, currency: "eur",
    bullets: ["The bubble effect", "Enjoy the present", "Distance, the real test"] },
  { id: "from-friend-to-lover", lang: "en", theme: "Love & Relationships", collection: "dating", subcollection: "contexts",
    title: "From Friend to Lover",
    blurb: "Dare to cross the line without losing it all: a solid base and a real risk, reframe 'I'll ruin everything', honor your feelings, confess without pressure and handle the outcome with dignity. 4 approaches.",
    pdf: "from-friend-to-lover-4-approaches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Solid base + real risk", "Honor your feelings", "Dare without pressure"] },
] as const;
