// Lot Sexualité ciblé femmes/hommes (7 FR + 7 EN), rubrique existante "Intimité & Sexualité" (18+).
// Upload dans lib/proGuides15.ts. PDF dans public/guides/.
// AFFICHAGE FR : section codée en dur "intimite-sexualite". EN : thème "Intimacy & Sexuality" (déjà dans EN_THEME_ORDER).
export const PRO_GUIDES_15 = [
  // ---- FR : Intimité & Sexualité ----
  { id: "retrouver-sa-libido-femme", lang: "fr", theme: "Intimité & Sexualité",
    title: "Retrouver sa libido (femmes)",
    blurb: "Quand le désir s'éteint : comprendre ce qui l'éteint (charge mentale, fatigue, hormones), renouer avec ce qui t'allume, le réveiller sans pression. 4 approches. (18+)",
    pdf: "retrouver-sa-libido-femme-4-approches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Comprendre ce qui éteint le désir", "Désir responsif", "Réveiller sans pression"] },
  { id: "se-reapproprier-son-plaisir", lang: "fr", theme: "Intimité & Sexualité",
    title: "Se réapproprier son plaisir (femmes)",
    blurb: "Lever les blocages psychologiques (honte, pression) pour renouer avec ton plaisir, sortir de la « course à l'orgasme », te connaître et communiquer. 4 approches. (18+)",
    pdf: "se-reapproprier-son-plaisir-4-approches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Lève les blocages", "Sors de la performance", "Ton plaisir est légitime"] },
  { id: "sexualite-apres-une-naissance", lang: "fr", theme: "Intimité & Sexualité",
    title: "Sexualité après une naissance",
    blurb: "Retrouver l'intimité à deux après bébé : comprendre ce qui change, te réapproprier ton corps, reconstruire en douceur et en communiquant. 4 approches. (18+)",
    pdf: "sexualite-apres-une-naissance-4-approches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Ce qui change après bébé", "Douceur & patience", "Reconstruire à deux"] },
  { id: "anxiete-performance-sexuelle-homme", lang: "fr", theme: "Intimité & Sexualité",
    title: "Dépasser l'anxiété de performance (hommes)",
    blurb: "Sortir de la pression et du cercle vicieux de l'anxiété, revenir aux sensations, communiquer, retrouver une sexualité sereine. 4 approches. (18+)",
    pdf: "anxiete-performance-sexuelle-homme-4-approches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Casse le cercle vicieux", "Reviens aux sensations", "Le sexe n'est pas un examen"] },
  { id: "dimension-psy-erection", lang: "fr", theme: "Intimité & Sexualité",
    title: "La dimension psy de l'érection (hommes)",
    blurb: "Comprendre le rôle du mental (stress, anxiété), apaiser le cercle anxiété-érection, te déculpabiliser — et savoir quand consulter un·e médecin. 4 approches. (18+)",
    pdf: "dimension-psy-erection-4-approches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Le rôle du mental", "Apaiser le cercle", "Quand consulter"] },
  { id: "depasser-injonctions-virilite", lang: "fr", theme: "Intimité & Sexualité",
    title: "Sortir de la pression de performance (hommes)",
    blurb: "Te libérer des injonctions de « vraie » virilité, t'autoriser la vulnérabilité, sortir de la comparaison, pour une sexualité plus libre et plus vraie. 4 approches. (18+)",
    pdf: "depasser-injonctions-virilite-4-approches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Déconstruis les injonctions", "Droit à la vulnérabilité", "Plus libre, plus vrai"] },
  { id: "rapport-sain-pornographie", lang: "fr", theme: "Intimité & Sexualité",
    title: "Un rapport sain à la pornographie",
    blurb: "Comprendre son influence (attentes irréalistes, comparaison), repérer un usage qui pèse, te reconnecter à ta sexualité réelle et garder l'équilibre. 4 approches. (18+)",
    pdf: "rapport-sain-pornographie-4-approches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Comprendre son influence", "Repérer un usage qui pèse", "Garder l'équilibre"] },
  // ---- EN : Intimacy & Sexuality ----
  { id: "rekindling-your-libido-women", lang: "en", theme: "Intimacy & Sexuality",
    title: "Rekindling Your Libido (women)",
    blurb: "When desire fades: understand what dims it (mental load, fatigue, hormones), reconnect with what turns you on, reawaken it without pressure. 4 approaches. (18+)",
    pdf: "rekindling-your-libido-women-4-approaches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Understand what dims desire", "Responsive desire", "Reawaken without pressure"] },
  { id: "reclaiming-your-pleasure-women", lang: "en", theme: "Intimacy & Sexuality",
    title: "Reclaiming Your Pleasure (women)",
    blurb: "Lift psychological blocks (shame, pressure) to reconnect with your pleasure, leave the 'race to orgasm', know yourself and communicate. 4 approaches. (18+)",
    pdf: "reclaiming-your-pleasure-women-4-approaches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Lift the blocks", "Leave performance", "Your pleasure is legitimate"] },
  { id: "sex-after-having-a-baby", lang: "en", theme: "Intimacy & Sexuality",
    title: "Sex After Having a Baby",
    blurb: "Rediscover intimacy together after baby: understand what changes, reclaim your body, rebuild gently and through communication. 4 approaches. (18+)",
    pdf: "sex-after-having-a-baby-4-approaches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["What changes after baby", "Gentleness & patience", "Rebuild together"] },
  { id: "overcoming-sexual-performance-anxiety-men", lang: "en", theme: "Intimacy & Sexuality",
    title: "Overcoming Sexual Performance Anxiety (men)",
    blurb: "Let go of pressure and the vicious circle of anxiety, return to sensation, communicate, find an easeful sexuality again. 4 approaches. (18+)",
    pdf: "overcoming-sexual-performance-anxiety-men-4-approaches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Break the vicious circle", "Return to sensation", "Sex isn't an exam"] },
  { id: "the-mind-and-erections-men", lang: "en", theme: "Intimacy & Sexuality",
    title: "The Mind and Erections (men)",
    blurb: "Understand the mental role (stress, anxiety), ease the anxiety-erection circle, let go of guilt — and know when to see a doctor. 4 approaches. (18+)",
    pdf: "the-mind-and-erections-men-4-approaches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["The mental role", "Ease the circle", "When to consult"] },
  { id: "letting-go-of-performance-pressure-men", lang: "en", theme: "Intimacy & Sexuality",
    title: "Letting Go of Performance Pressure (men)",
    blurb: "Free yourself from the demands of 'real' masculinity, allow vulnerability, leave comparison, for a freer and truer sexuality. 4 approaches. (18+)",
    pdf: "letting-go-of-performance-pressure-men-4-approaches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Deconstruct the demands", "Right to vulnerability", "Freer, truer"] },
  { id: "a-healthy-relationship-with-porn", lang: "en", theme: "Intimacy & Sexuality",
    title: "A Healthy Relationship With Porn",
    blurb: "Understand its influence (unrealistic expectations, comparison), spot use that weighs on you, reconnect with your real sexuality and keep balance. 4 approaches. (18+)",
    pdf: "a-healthy-relationship-with-porn-4-approaches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Understand its influence", "Spot use that weighs", "Keep balance"] },
] as const;
