// Lot 4 "monde pro" (4 FR + 4 EN). Upload dans lib/proGuides4.ts. PDF dans public/guides/.
export const PRO_GUIDES_4 = [
  // ---- FR : thème Travail ----
  { id: "gerer-conflit-travail", lang: "fr", theme: "Travail",
    title: "Gérer un conflit au travail",
    blurb: "Désamorcer sans fuir ni exploser : comprendre tes réactions, apaiser l'émotion, résoudre avec des outils concrets. 4 approches + conseils & tips.",
    pdf: "gerer-conflit-travail-4-approches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Comprends ta réaction au conflit", "Désamorce les tensions", "Résous à froid, en « je »"] },
  { id: "prendre-la-parole-en-public", lang: "fr", theme: "Travail",
    title: "Prendre la parole en public",
    blurb: "Parler en réunion ou présenter sans paniquer : comprendre ta peur, apaiser le trac, t'exprimer avec présence. 4 approches + conseils & tips.",
    pdf: "prendre-la-parole-en-public-4-approches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Comprends ta peur du regard", "Apaise le trac", "Trouve ton message"] },
  { id: "trouver-mentors-sponsors", lang: "fr", theme: "Travail",
    title: "Trouver mentors & sponsors",
    blurb: "T'entourer pour avancer quand on part isolée : oser demander, distinguer mentor et sponsor, bâtir un réseau qui ouvre des portes. 4 approches + conseils & tips.",
    pdf: "trouver-mentors-sponsors-4-approches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Ose demander du soutien", "Mentor vs sponsor", "Bâtis ton réseau"] },
  { id: "creer-culture-inclusive", lang: "fr", theme: "Travail",
    title: "Créer une culture inclusive",
    blurb: "Faire de l'inclusion une réalité, pas un slogan : examiner la culture, dépasser l'inclusion cosmétique, poser des leviers mesurables. 4 approches + conseils & tips.",
    pdf: "creer-culture-inclusive-4-approches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Vois ta culture invisible", "Au-delà des chartes", "Des leviers mesurables"] },
  // ---- EN : theme Career ----
  { id: "handling-conflict-at-work", lang: "en", theme: "Career",
    title: "Handling Conflict at Work",
    blurb: "Defuse without fleeing or exploding: understand your reactions, ease the emotion, resolve with concrete tools. 4 approaches + tips.",
    pdf: "handling-conflict-at-work-4-approaches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Understand your conflict reflex", "Defuse tensions", "Resolve when calm, in 'I'"] },
  { id: "public-speaking-at-work", lang: "en", theme: "Career",
    title: "Public Speaking at Work",
    blurb: "Speak up in meetings or present without panicking: understand your fear, ease the nerves, express yourself with presence. 4 approaches + tips.",
    pdf: "public-speaking-at-work-4-approaches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Understand your fear of the gaze", "Ease the nerves", "Find your message"] },
  { id: "finding-mentors-and-sponsors", lang: "en", theme: "Career",
    title: "Finding Mentors & Sponsors",
    blurb: "Build support to move forward when you start out isolated: dare to ask, tell mentor from sponsor, build a network that opens doors. 4 approaches + tips.",
    pdf: "finding-mentors-and-sponsors-4-approaches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Dare to ask for support", "Mentor vs sponsor", "Build your network"] },
  { id: "building-an-inclusive-culture", lang: "en", theme: "Career",
    title: "Building an Inclusive Culture",
    blurb: "Make inclusion real, not a slogan: examine the culture, move past cosmetic inclusion, put measurable levers in place. 4 approaches + tips.",
    pdf: "building-an-inclusive-culture-4-approaches.pdf", priceCents: 999, currency: "eur",
    bullets: ["See your invisible culture", "Beyond charters", "Measurable levers"] },
] as const;
