// Lot "Bien-être sexuel" (Intimité & Sexualité, 18+). Upload dans lib/proGuides25.ts. PDF dans public/guides/.
export const PRO_GUIDES_25 = [
  // ---- FR ----
  { id: "communiquer-desirs-limites", lang: "fr", theme: "Intimité & Sexualité", adult: true,
    title: "Communiquer ses désirs et ses limites",
    blurb: "Oser dire ce que tu veux — et ce que tu ne veux pas : sortir du silence, recadrer la gêne, légitimer tes désirs et tes limites, parler en « je » et poser le consentement. 4 approches. 18+",
    pdf: "communiquer-desirs-limites-4-approches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Le silence coûte cher", "Tes désirs ET tes limites", "Consentement & communication"] },
  { id: "raviver-le-desir", lang: "fr", theme: "Intimité & Sexualité", adult: true,
    title: "Raviver le désir dans le couple",
    blurb: "Quand la routine éteint la flamme : comprendre désir spontané vs répondant, lever la pression, te reconnecter à ta sensualité, cultiver complicité, nouveauté et temps. 4 approches. 18+",
    pdf: "raviver-le-desir-4-approches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Désir spontané vs répondant", "Sans pression", "Complicité & nouveauté"] },
  { id: "explorer-ses-fantasmes", lang: "fr", theme: "Intimité & Sexualité", adult: true,
    title: "Explorer ses fantasmes sans culpabilité",
    blurb: "Accueillir ton imaginaire et le partager si tu veux : fantasmer est sain, imaginer n'est pas vouloir, lever la honte, partager avec consentement (ou garder pour toi). 4 approches. 18+",
    pdf: "explorer-ses-fantasmes-4-approches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Fantasmer est sain", "Imaginer ≠ vouloir", "Partager (si tu veux)"] },
  { id: "echangisme-a-deux", lang: "fr", theme: "Intimité & Sexualité", adult: true,
    title: "L'échangisme à deux",
    blurb: "Explorer sans abîmer ton couple : un choix à deux jamais une obligation, écouter la jalousie comme un signal, protéger ton lien, poser règles, consentement, sécurité et debrief. 4 approches. 18+",
    pdf: "echangisme-a-deux-4-approches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Un vrai choix, à deux", "La jalousie, un signal", "Règles, consentement, debrief"] },
  { id: "plaisir-anal-en-confiance", lang: "fr", theme: "Intimité & Sexualité", adult: true,
    title: "Le plaisir anal, en confiance",
    blurb: "À ton rythme, en sécurité et sans pression : démystifier, lever le tabou, remettre ton confort aux commandes, les essentiels faits avec soin (détente, lubrifiant, hygiène, arrêt si douleur). 4 approches. 18+",
    pdf: "plaisir-anal-en-confiance-4-approches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Une option, jamais une obligation", "La douleur = stop", "À ton rythme, en sécurité"] },
  { id: "fellation-sans-tabou", lang: "fr", theme: "Intimité & Sexualité", adult: true,
    title: "La fellation, sans tabou ni pression",
    blurb: "Plaisir partagé, jamais une obligation : un choix et pas un dû, recadrer pression et honte, ton consentement d'abord, communication, confort et réciprocité. 4 approches. 18+",
    pdf: "fellation-sans-tabou-4-approches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Un choix, jamais un dû", "Ton consentement d'abord", "Communication & réciprocité"] },
  // ---- EN ----
  { id: "communicating-desires-and-limits", lang: "en", theme: "Intimacy & Sexuality", adult: true,
    title: "Communicating Your Desires and Limits",
    blurb: "Dare to say what you want — and what you don't: leave silence, reframe awkwardness, legitimize your desires and limits, speak in 'I' and set consent. 4 approaches. 18+",
    pdf: "communicating-desires-and-limits-4-approaches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Silence is costly", "Your desires AND limits", "Consent & communication"] },
  { id: "reviving-desire-in-your-couple", lang: "en", theme: "Intimacy & Sexuality", adult: true,
    title: "Reviving Desire in Your Couple",
    blurb: "When routine dims the flame: understand spontaneous vs responsive desire, lift the pressure, reconnect to your sensuality, cultivate closeness, novelty and time. 4 approaches. 18+",
    pdf: "reviving-desire-in-your-couple-4-approaches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Spontaneous vs responsive", "Without pressure", "Closeness & novelty"] },
  { id: "exploring-your-fantasies", lang: "en", theme: "Intimacy & Sexuality", adult: true,
    title: "Exploring Your Fantasies Without Guilt",
    blurb: "Welcome your imagination and share it if you wish: fantasizing is healthy, imagining isn't wanting, lift the shame, share with consent (or keep to yourself). 4 approaches. 18+",
    pdf: "exploring-your-fantasies-4-approaches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Fantasizing is healthy", "Imagining ≠ wanting", "Share (if you want)"] },
  { id: "swinging-as-a-couple", lang: "en", theme: "Intimacy & Sexuality", adult: true,
    title: "Swinging as a Couple",
    blurb: "Explore without harming your bond: a choice for two never an obligation, hear jealousy as a signal, protect your bond, set rules, consent, safety and debrief. 4 approaches. 18+",
    pdf: "swinging-as-a-couple-4-approaches.pdf", priceCents: 999, currency: "eur",
    bullets: ["A true choice, for two", "Jealousy, a signal", "Rules, consent, debrief"] },
  { id: "anal-pleasure-with-confidence", lang: "en", theme: "Intimacy & Sexuality", adult: true,
    title: "Anal Pleasure, With Confidence",
    blurb: "At your pace, safely and without pressure: demystify, lift the taboo, put your comfort in control, the essentials done with care (relaxation, lubricant, hygiene, stop if pain). 4 approaches. 18+",
    pdf: "anal-pleasure-with-confidence-4-approaches.pdf", priceCents: 999, currency: "eur",
    bullets: ["An option, never an obligation", "Pain = stop", "At your pace, safely"] },
  { id: "fellatio-without-taboo", lang: "en", theme: "Intimacy & Sexuality", adult: true,
    title: "Oral Sex (Fellatio), Without Taboo or Pressure",
    blurb: "Shared pleasure, never an obligation: a choice not a duty, reframe pressure and shame, your consent first, communication, comfort and reciprocity. 4 approaches. 18+",
    pdf: "fellatio-without-taboo-4-approaches.pdf", priceCents: 999, currency: "eur",
    bullets: ["A choice, never a duty", "Your consent first", "Communication & reciprocity"] },
] as const;
