// Lot 3 "monde pro" (4 FR + 4 EN). Upload dans lib/proGuides3.ts. PDF dans public/guides/.
export const PRO_GUIDES_3 = [
  // ---- FR : thème Travail ----
  { id: "reussir-entretien-embauche", lang: "fr", theme: "Travail",
    title: "Réussir un entretien d'embauche",
    blurb: "Transformer le trac en atout : apaiser le stress, préparer des réponses solides, te présenter avec assurance. 4 approches + conseils & tips.",
    pdf: "reussir-entretien-embauche-4-approches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Apaise le trac", "Prépare tes réponses (STAR)", "Présente-toi sans te trahir"] },
  { id: "quitter-job-toxique", lang: "fr", theme: "Travail",
    title: "Quitter un job toxique",
    blurb: "Partir sans culpabilité ni précipitation : reconnaître la toxicité, apaiser la peur, préparer un départ serein. 4 approches + conseils & tips.",
    pdf: "quitter-job-toxique-4-approches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Reconnais la toxicité", "Apaise culpabilité & peur", "Prépare un départ stratégique"] },
  { id: "misogynoir-au-travail", lang: "fr", theme: "Travail",
    title: "Misogynoir au travail",
    blurb: "Quand racisme et sexisme se combinent au bureau : protéger ton estime et répondre avec stratégie. 4 approches + conseils & tips.",
    pdf: "misogynoir-au-travail-4-approches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Valide ce que tu vis", "Protège ton estime", "Réponds avec stratégie"] },
  { id: "recruter-sans-discriminer", lang: "fr", theme: "Travail",
    title: "Recruter sans discriminer",
    blurb: "Choisir les bonnes personnes sans biais : repérer tes automatismes et bâtir un process équitable. 4 approches + conseils & tips.",
    pdf: "recruter-sans-discriminer-4-approches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Repère tes biais", "Dépasse le « feeling »", "Un process équitable"] },
  // ---- EN : theme Career ----
  { id: "acing-your-job-interview", lang: "en", theme: "Career",
    title: "Acing Your Job Interview",
    blurb: "Turn the nerves into an asset: ease the stress, prepare solid answers, present yourself with confidence. 4 approaches + tips.",
    pdf: "acing-your-job-interview-4-approaches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Ease the nerves", "Prepare your answers (STAR)", "Present without betraying yourself"] },
  { id: "leaving-a-toxic-job", lang: "en", theme: "Career",
    title: "Leaving a Toxic Job",
    blurb: "Leave without guilt or rushing: recognize the toxicity, ease the fear, prepare a calm exit. 4 approaches + tips.",
    pdf: "leaving-a-toxic-job-4-approaches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Recognize the toxicity", "Ease guilt & fear", "Prepare a strategic exit"] },
  { id: "misogynoir-at-work", lang: "en", theme: "Career",
    title: "Misogynoir at Work",
    blurb: "When racism and sexism combine at the office: protect your self-esteem and respond strategically. 4 approaches + tips.",
    pdf: "misogynoir-at-work-4-approaches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Validates what you live", "Protect your self-esteem", "Respond strategically"] },
  { id: "hiring-without-bias", lang: "en", theme: "Career",
    title: "Hiring Without Bias",
    blurb: "Choose the right people without bias: spot your automatic reactions and build a fair process. 4 approaches + tips.",
    pdf: "hiring-without-bias-4-approaches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Spot your biases", "Move past gut feeling", "A fair process"] },
] as const;
