// Lot "Blessures intérieures" — un guide par blessure. Upload dans lib/proGuides20.ts. PDF dans public/guides/.
// CLÉ : relier chaque résultat du test des blessures à son guide dédié.
export const PRO_GUIDES_20 = [
  // ---- FR ----
  { id: "guerir-blessure-rejet", lang: "fr", theme: "Bien-être & soi", wound: "rejet",
    title: "Guérir la blessure de rejet",
    blurb: "Te donner le droit d'exister et de prendre ta place : comprendre le masque du fuyant, recadrer « je suis de trop », et oser rester dans le lien. 4 approches.",
    pdf: "guerir-blessure-rejet-4-approches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Le masque du fuyant", "« J'ai le droit d'exister »", "Oser rester"] },
  { id: "guerir-blessure-abandon", lang: "fr", theme: "Bien-être & soi", wound: "abandon",
    title: "Guérir la blessure d'abandon",
    blurb: "Apprendre à te sentir en sécurité de l'intérieur : comprendre le masque du dépendant, distinguer éloignement et abandon, et bâtir ta base de sécurité. 4 approches.",
    pdf: "guerir-blessure-abandon-4-approches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Le masque du dépendant", "Éloignement ≠ abandon", "Ta base de sécurité"] },
  { id: "guerir-blessure-humiliation", lang: "fr", theme: "Bien-être & soi", wound: "humiliation",
    title: "Guérir la blessure d'humiliation",
    blurb: "Reconnaître ta valeur et oser tes besoins : comprendre le masque du sacrifice, rendre la honte qui n'est pas la tienne, et t'autoriser à recevoir. 4 approches.",
    pdf: "guerir-blessure-humiliation-4-approches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Le masque du sacrifice", "Tes besoins sont légitimes", "Oser recevoir"] },
  { id: "guerir-blessure-trahison", lang: "fr", theme: "Bien-être & soi", wound: "trahison",
    title: "Guérir la blessure de trahison",
    blurb: "Réapprendre à faire confiance et lâcher le contrôle : comprendre le masque du contrôlant, distinguer peur et preuve, et reconstruire la confiance par petits paris. 4 approches.",
    pdf: "guerir-blessure-trahison-4-approches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Le masque du contrôlant", "Peur ≠ preuve", "La force inclut la vulnérabilité"] },
  { id: "guerir-blessure-injustice", lang: "fr", theme: "Bien-être & soi", wound: "injustice",
    title: "Guérir la blessure d'injustice",
    blurb: "T'autoriser l'imperfection et retrouver ta souplesse : comprendre le masque du rigide, recadrer le perfectionnisme, te réautoriser à ressentir. 4 approches.",
    pdf: "guerir-blessure-injustice-4-approches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Le masque du rigide", "« Suffisamment bien » suffit", "Te réautoriser à ressentir"] },
  // ---- EN ----
  { id: "healing-the-rejection-wound", lang: "en", theme: "Wellbeing & Self", wound: "rejet",
    title: "Healing the Rejection Wound",
    blurb: "Give yourself the right to exist and take your place: understand the avoidant mask, reframe 'I'm too much', and dare to stay in connection. 4 approaches.",
    pdf: "healing-the-rejection-wound-4-approaches.pdf", priceCents: 999, currency: "eur",
    bullets: ["The avoidant mask", "'I have the right to exist'", "Dare to stay"] },
  { id: "healing-the-abandonment-wound", lang: "en", theme: "Wellbeing & Self", wound: "abandon",
    title: "Healing the Abandonment Wound",
    blurb: "Learn to feel safe from within: understand the dependent mask, tell distance from abandonment, and build your secure base. 4 approaches.",
    pdf: "healing-the-abandonment-wound-4-approaches.pdf", priceCents: 999, currency: "eur",
    bullets: ["The dependent mask", "Distance ≠ abandonment", "Your secure base"] },
  { id: "healing-the-humiliation-wound", lang: "en", theme: "Wellbeing & Self", wound: "humiliation",
    title: "Healing the Humiliation Wound",
    blurb: "Recognize your worth and dare your needs: understand the sacrifice mask, return shame that isn't yours, and allow yourself to receive. 4 approaches.",
    pdf: "healing-the-humiliation-wound-4-approaches.pdf", priceCents: 999, currency: "eur",
    bullets: ["The sacrifice mask", "Your needs are legitimate", "Dare to receive"] },
  { id: "healing-the-betrayal-wound", lang: "en", theme: "Wellbeing & Self", wound: "trahison",
    title: "Healing the Betrayal Wound",
    blurb: "Relearn to trust and let go of control: understand the controlling mask, tell fear from proof, and rebuild trust through small bets. 4 approaches.",
    pdf: "healing-the-betrayal-wound-4-approaches.pdf", priceCents: 999, currency: "eur",
    bullets: ["The controlling mask", "Fear ≠ proof", "Strength includes vulnerability"] },
  { id: "healing-the-injustice-wound", lang: "en", theme: "Wellbeing & Self", wound: "injustice",
    title: "Healing the Injustice Wound",
    blurb: "Allow imperfection and recover your flexibility: understand the rigid mask, reframe perfectionism, and let yourself feel again. 4 approaches.",
    pdf: "healing-the-injustice-wound-4-approaches.pdf", priceCents: 999, currency: "eur",
    bullets: ["The rigid mask", "'Good enough' is enough", "Let yourself feel"] },
] as const;
