// Lot "Santé sexuelle" (Intimité & Sexualité, 18+). Upload dans lib/proGuides27.ts. PDF dans public/guides/.
export const PRO_GUIDES_27 = [
  // ---- FR ----
  { id: "comprendre-le-vaginisme", lang: "fr", theme: "Intimité & Sexualité", adult: true,
    title: "Comprendre le vaginisme",
    blurb: "Une réaction involontaire, réelle — et qui se soigne : sortir de la culpabilité, apaiser le cercle peur-douleur, ta valeur n'est pas la pénétration, aller chercher l'aide qui marche. 4 approches. 18+",
    pdf: "comprendre-le-vaginisme-4-approches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Involontaire, pas ta faute", "Le cercle peur-douleur", "Ça se soigne (les bons pros)"] },
  { id: "sexualite-apres-menopause", lang: "fr", theme: "Intimité & Sexualité", adult: true,
    title: "La sexualité après la ménopause",
    blurb: "Ton désir évolue, il ne s'éteint pas : démystifier, sortir des pensées qui te mettent « hors-jeu », ta sensualité continue, des solutions concrètes avec ton médecin. 4 approches. 18+",
    pdf: "sexualite-apres-menopause-4-approches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Évoluer, pas s'éteindre", "Pas de date de péremption", "Solutions concrètes"] },
  { id: "troubles-erection-partenaire", lang: "fr", theme: "Intimité & Sexualité", adult: true,
    title: "Quand ton partenaire a des troubles de l'érection",
    blurb: "Ce n'est pas un rejet de toi : comprendre les causes, reposer un fardeau qui n'est pas le tien, alléger la pression, soutenir et l'encourager à consulter. 4 approches. 18+",
    pdf: "troubles-erection-partenaire-4-approches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Pas un rejet de toi", "Reposer le fardeau", "Soutien + avis médical"] },
  { id: "ejaculation-precoce-a-deux", lang: "fr", theme: "Intimité & Sexualité", adult: true,
    title: "L'éjaculation précoce : en parler et la gérer à deux",
    blurb: "Un problème courant qui se gère sans honte : démystifier, casser le cercle anxiété-performance, ton plaisir compte aussi, en faire un sujet d'équipe et chercher des solutions. 4 approches. 18+",
    pdf: "ejaculation-precoce-a-deux-4-approches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Courant et gérable", "Anxiété de performance", "Sujet d'équipe, sans blâme"] },
  { id: "decouvrir-le-tantrisme", lang: "fr", theme: "Intimité & Sexualité", adult: true,
    title: "Découvrir le tantrisme",
    blurb: "Une sexualité lente, consciente et connectée : présence plutôt que performance, lever les freins, habiter ton corps et ralentir, des pratiques simples pour commencer (respiration, regard, toucher lent). 4 approches. 18+",
    pdf: "decouvrir-le-tantrisme-4-approches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Présence, pas performance", "Le plaisir est un chemin", "Pratiques simples"] },
  { id: "sexualite-apres-accouchement", lang: "fr", theme: "Intimité & Sexualité", adult: true,
    title: "La sexualité après l'accouchement",
    blurb: "Retrouver ton corps et ton désir à ton rythme : une baisse normale et temporaire, lever la pression du calendrier, compassion pour ton corps qui change, douceur, communication et soutien. 4 approches. 18+",
    pdf: "sexualite-apres-accouchement-4-approches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Baisse normale & temporaire", "Aucun calendrier", "Compassion & douceur"] },
  // ---- EN ----
  { id: "understanding-vaginismus", lang: "en", theme: "Intimacy & Sexuality", adult: true,
    title: "Understanding Vaginismus",
    blurb: "An involuntary, real reaction — and a treatable one: leave the guilt, ease the fear-pain cycle, your worth isn't penetration, seek the help that works. 4 approaches. 18+",
    pdf: "understanding-vaginismus-4-approaches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Involuntary, not your fault", "The fear-pain cycle", "It's treatable (the right pros)"] },
  { id: "sexuality-after-menopause", lang: "en", theme: "Intimacy & Sexuality", adult: true,
    title: "Sexuality After Menopause",
    blurb: "Your desire evolves, it doesn't go out: demystify, leave the thoughts that sideline you, your sensuality continues, concrete solutions with your doctor. 4 approaches. 18+",
    pdf: "sexuality-after-menopause-4-approaches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Evolving, not going out", "No expiry date", "Concrete solutions"] },
  { id: "partners-erection-difficulties", lang: "en", theme: "Intimacy & Sexuality", adult: true,
    title: "When Your Partner Has Erection Difficulties",
    blurb: "It's not a rejection of you: understand the causes, set down a burden that isn't yours, lift the pressure, support and encourage him to consult. 4 approaches. 18+",
    pdf: "partners-erection-difficulties-4-approaches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Not a rejection of you", "Set down the burden", "Support + medical opinion"] },
  { id: "premature-ejaculation-together", lang: "en", theme: "Intimacy & Sexuality", adult: true,
    title: "Premature Ejaculation: Talking About It Together",
    blurb: "A common issue, manageable without shame: demystify, break the anxiety-performance cycle, your pleasure matters too, make it a team topic and find solutions. 4 approaches. 18+",
    pdf: "premature-ejaculation-together-4-approaches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Common and manageable", "Performance anxiety", "A team topic, no blame"] },
  { id: "discovering-tantra", lang: "en", theme: "Intimacy & Sexuality", adult: true,
    title: "Discovering Tantra",
    blurb: "A slow, conscious and connected sexuality: presence over performance, lift the brakes, inhabit your body and slow down, simple practices to begin (breath, gaze, slow touch). 4 approaches. 18+",
    pdf: "discovering-tantra-4-approaches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Presence, not performance", "Pleasure is a path", "Simple practices"] },
  { id: "sexuality-after-childbirth", lang: "en", theme: "Intimacy & Sexuality", adult: true,
    title: "Sexuality After Childbirth",
    blurb: "Reconnect with your body and desire at your pace: a normal, temporary drop, lift the timeline pressure, compassion for your changing body, gentleness, communication and support. 4 approaches. 18+",
    pdf: "sexuality-after-childbirth-4-approaches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Normal & temporary drop", "No timeline", "Compassion & gentleness"] },
] as const;
