// Lot "Intimité & Sexualité" (4 FR + 4 EN), NOUVEAU thème/section dédié, 18+.
// Upload dans lib/proGuides12.ts. PDF dans public/guides/.
// AFFICHAGE FR : créer une NOUVELLE section SECTIONS -> clé "intimite-sexualite" (label "Intimité & Sexualité").
// AFFICHAGE EN : nouveau thème "Intimacy & Sexuality" à ajouter à EN_THEME_ORDER.
export const PRO_GUIDES_12 = [
  // ---- FR : thème Intimité & Sexualité ----
  { id: "raviver-le-desir", lang: "fr", theme: "Intimité & Sexualité",
    title: "Raviver le désir dans le couple",
    blurb: "Retrouver l'envie, à deux, dans la durée : comprendre ce qui endort le désir, te reconnecter au tien, le raviver sans pression. 4 approches + conseils. (18+)",
    pdf: "raviver-le-desir-4-approches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Comprends ce qui endort le désir", "Reconnecte-toi au tien", "Ravive sans pression"] },
  { id: "parler-de-sexe-sans-tabou", lang: "fr", theme: "Intimité & Sexualité",
    title: "Parler de sexe sans tabou",
    blurb: "Oser dire ses envies, ses limites, ses ressentis : dépasser le tabou, t'autoriser, des outils concrets pour en parler. 4 approches + conseils. (18+)",
    pdf: "parler-de-sexe-sans-tabou-4-approches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Dépasse le tabou", "Tes envies & tes limites", "Des outils pour en parler"] },
  { id: "depasser-honte-blocages-sexuels", lang: "fr", theme: "Intimité & Sexualité",
    title: "Dépasser la honte et les blocages",
    blurb: "Te réconcilier avec ton corps et ton plaisir : comprendre tes blocages, te réconcilier avec ton corps, te déconditionner en douceur. 4 approches + ressources. (18+)",
    pdf: "depasser-honte-blocages-sexuels-4-approches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Comprends tes blocages", "Réconcilie-toi avec ton corps", "En douceur, à ton rythme"] },
  { id: "desirs-desaccordes", lang: "fr", theme: "Intimité & Sexualité",
    title: "Quand les désirs sont désaccordés",
    blurb: "L'un veut plus que l'autre : sortir du conflit, accueillir deux désirs différents, trouver un terrain commun. 4 approches + conseils. (18+)",
    pdf: "desirs-desaccordes-4-approches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Ce que le décalage révèle", "Aucun n'a tort", "Trouver un terrain commun"] },
  // ---- EN : theme Intimacy & Sexuality ----
  { id: "rekindling-desire-in-your-relationship", lang: "en", theme: "Intimacy & Sexuality",
    title: "Rekindling Desire in Your Relationship",
    blurb: "Find the wanting again, together, over time: understand what dulls desire, reconnect with your own, rekindle without pressure. 4 approaches + tips. (18+)",
    pdf: "rekindling-desire-in-your-relationship-4-approaches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Understand what dulls desire", "Reconnect with your own", "Rekindle without pressure"] },
  { id: "talking-about-sex-without-taboo", lang: "en", theme: "Intimacy & Sexuality",
    title: "Talking About Sex Without Taboo",
    blurb: "Dare to voice your wants, limits and feelings: move past the taboo, allow yourself, concrete tools to talk about it. 4 approaches + tips. (18+)",
    pdf: "talking-about-sex-without-taboo-4-approaches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Move past the taboo", "Your wants & limits", "Tools to talk about it"] },
  { id: "overcoming-shame-and-sexual-blocks", lang: "en", theme: "Intimacy & Sexuality",
    title: "Overcoming Shame and Sexual Blocks",
    blurb: "Reconcile with your body and your pleasure: understand your blocks, reconcile with your body, gently uncondition yourself. 4 approaches + resources. (18+)",
    pdf: "overcoming-shame-and-sexual-blocks-4-approaches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["Understand your blocks", "Reconcile with your body", "Gently, at your pace"] },
  { id: "mismatched-desire-in-couples", lang: "en", theme: "Intimacy & Sexuality",
    title: "Mismatched Desire in Couples",
    blurb: "One wants more than the other: leave the conflict, welcome two different desires, find common ground. 4 approaches + tips. (18+)",
    pdf: "mismatched-desire-in-couples-4-approaches.pdf", priceCents: 1900, currency: "eur",
    bullets: ["What the gap reveals", "Neither is wrong", "Find common ground"] },
] as const;
