// Collection "Créateur·rice & Influence" — LOT 3/5 (Présence & identité). Upload dans lib/proGuides34.ts. PDF dans public/guides/.
export const PRO_GUIDES_34 = [
  // ---- FR ----
  { id: "charisme-face-camera", lang: "fr", theme: "Créateur·rice & Influence", collection: "creator",
    title: "Développer ta personnalité et ton charisme face caméra",
    blurb: "Devenir captivant·e : le charisme s'apprend (présence + authenticité + énergie), recadrer « je suis trop fade », ta singularité EST ton charisme, leviers concrets (voix, regard, énergie, récit). 4 approches.",
    pdf: "charisme-face-camera-4-approches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Le charisme s'apprend", "Ta singularité = ton atout", "Voix, regard, énergie, récit"] },
  { id: "trouver-ton-personnage", lang: "fr", theme: "Créateur·rice & Influence", collection: "creator",
    title: "Trouver ton « personnage » sans porter de masque",
    blurb: "Un persona authentique : persona vs masque, recadrer « je dois jouer un autre », amplifier qui tu es déjà, définir ton ton et tes codes. 4 approches.",
    pdf: "trouver-ton-personnage-4-approches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Persona, pas masque", "Ta vérité amplifiée", "Ton ton & tes codes"] },
  { id: "raconter-ta-vie-sans-te-mettre-a-nu", lang: "fr", theme: "Créateur·rice & Influence", collection: "creator",
    title: "Raconter ta vie sans te mettre à nu",
    blurb: "Le storytelling personnel avec limites : la leçon pas le déballage, recadrer « il faut tout montrer », la cicatrice pas la plaie ouverte, structurer et choisir. 4 approches.",
    pdf: "raconter-ta-vie-sans-te-mettre-a-nu-4-approches.pdf", priceCents: 999, currency: "eur",
    bullets: ["La leçon, pas le déballage", "La cicatrice, pas la plaie", "Structurer & choisir"] },
  { id: "couple-d-influenceurs", lang: "fr", theme: "Créateur·rice & Influence", collection: "creator",
    title: "Devenir un couple d'influenceurs",
    blurb: "Créer à deux sans abîmer le couple : votre couple n'est pas un produit, recadrer « on doit montrer un couple parfait », protéger votre intimité, rôles/limites et l'accord « si ça s'arrête ». 4 approches.",
    pdf: "couple-d-influenceurs-4-approches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Le couple avant le contenu", "Vrais, pas parfaits", "Un cadre clair à deux"] },
  { id: "creer-en-famille-proteger-enfants", lang: "fr", theme: "Créateur·rice & Influence", collection: "creator",
    title: "Créer du contenu en famille — en protégeant tes enfants",
    blurb: "L'angle responsable : exposer un·e mineur·e est sérieux, recadrer « c'est mignon ça marche », le droit de ton enfant à son intimité, des règles strictes (dans le doute, ne publie pas). 4 approches.",
    pdf: "creer-en-famille-proteger-enfants-4-approches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Protection avant les vues", "Son droit à l'intimité", "Dans le doute, non"] },
  { id: "dire-non-sans-culpabiliser", lang: "fr", theme: "Créateur·rice & Influence", collection: "creator",
    title: "Dire non sans culpabiliser",
    blurb: "Sponsos pas alignées, collabs, demandes : le « non » qui protège, recadrer « si je refuse je perds tout », tes valeurs avant l'opportunité, des critères clairs pour trier. 4 approches.",
    pdf: "dire-non-sans-culpabiliser-4-approches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Le non qui protège", "Tes valeurs d'abord", "Des critères clairs"] },
  // ---- EN ----
  { id: "charisma-on-camera", lang: "en", theme: "Creator & Influence", collection: "creator",
    title: "Developing Your Personality and Charisma on Camera",
    blurb: "Becoming captivating: charisma is learnable (presence + authenticity + energy), reframe 'I'm too bland', your uniqueness IS your charisma, concrete levers (voice, gaze, energy, story). 4 approaches.",
    pdf: "charisma-on-camera-4-approaches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Charisma is learnable", "Your uniqueness = your asset", "Voice, gaze, energy, story"] },
  { id: "finding-your-persona", lang: "en", theme: "Creator & Influence", collection: "creator",
    title: "Finding Your Persona Without Wearing a Mask",
    blurb: "An authentic persona: persona vs mask, reframe 'I must play someone else', amplify who you already are, define your tone and codes. 4 approaches.",
    pdf: "finding-your-persona-4-approaches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Persona, not mask", "Your amplified truth", "Your tone & codes"] },
  { id: "personal-storytelling-with-limits", lang: "en", theme: "Creator & Influence", collection: "creator",
    title: "Telling Your Story Without Baring It All",
    blurb: "Personal storytelling with boundaries: the lesson not the dump, reframe 'show everything', the scar not the open wound, structure and choose. 4 approaches.",
    pdf: "personal-storytelling-with-limits-4-approaches.pdf", priceCents: 999, currency: "eur",
    bullets: ["The lesson, not the dump", "The scar, not the wound", "Structure & choose"] },
  { id: "influencer-couple", lang: "en", theme: "Creator & Influence", collection: "creator",
    title: "Becoming an Influencer Couple",
    blurb: "Creating together without harming the relationship: your couple isn't a product, reframe 'we must show a perfect couple', protect your intimacy, roles/limits and the 'if it ends' agreement. 4 approaches.",
    pdf: "influencer-couple-4-approaches.pdf", priceCents: 999, currency: "eur",
    bullets: ["The couple before content", "Real, not perfect", "A clear frame together"] },
  { id: "family-content-protecting-your-kids", lang: "en", theme: "Creator & Influence", collection: "creator",
    title: "Creating Family Content — While Protecting Your Kids",
    blurb: "The responsible angle: exposing a minor is serious, reframe 'it's cute it performs', your child's right to privacy, strict rules (when in doubt, don't post). 4 approaches.",
    pdf: "family-content-protecting-your-kids-4-approaches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Protection before views", "Their right to privacy", "When in doubt, no"] },
  { id: "saying-no-without-guilt", lang: "en", theme: "Creator & Influence", collection: "creator",
    title: "Saying No Without Guilt",
    blurb: "Misaligned sponsorships, collabs, requests: the 'no' that protects, reframe 'if I refuse I lose everything', your values before the opportunity, clear criteria to sort. 4 approaches.",
    pdf: "saying-no-without-guilt-4-approaches.pdf", priceCents: 999, currency: "eur",
    bullets: ["The no that protects", "Your values first", "Clear criteria"] },
] as const;
