// Collection "Émotions & Régulation". Upload dans lib/proGuides40.ts. PDF dans public/guides/.
export const PRO_GUIDES_40 = [
  // ---- FR ----
  { id: "accueillir-tes-emotions", lang: "fr", theme: "Émotions & Régulation", collection: "regulation",
    title: "Comprendre et accueillir tes émotions",
    blurb: "Tes émotions ne sont pas l'ennemi : des messagères pas des ennemies, recadrer « je ne devrais pas ressentir ça », toutes tes émotions sont légitimes, nommer/situer/écouter le besoin. 4 approches.",
    pdf: "accueillir-tes-emotions-4-approches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Des messagères", "Ni bien ni mal", "Nommer pour apaiser"] },
  { id: "boite-a-outils-regulation", lang: "fr", theme: "Émotions & Régulation", collection: "regulation",
    title: "Réguler tes émotions : ta boîte à outils",
    blurb: "La fenêtre de tolérance et les techniques qui apaisent : revenir dans ta fenêtre, recadrer « je suis incapable de me calmer », la compassion régule, ton kit (respiration, ancrage, recadrage, mouvement, pause). 4 approches.",
    pdf: "boite-a-outils-regulation-4-approches.pdf", priceCents: 999, currency: "eur",
    bullets: ["La fenêtre de tolérance", "Une compétence qui s'apprend", "Ton kit perso"] },
  { id: "gerer-la-frustration", lang: "fr", theme: "Émotions & Régulation", collection: "regulation",
    title: "Gérer la frustration",
    blurb: "L'écart entre ce que tu attends et ce qui est : comprendre l'écart, recadrer les exigences rigides (« c'est insupportable »), la frustration est humaine, pause/assouplir/résoudre. 4 approches.",
    pdf: "gerer-la-frustration-4-approches.pdf", priceCents: 999, currency: "eur",
    bullets: ["L'écart attente/réalité", "Assouplir les exigences", "Muscler ta tolérance"] },
  { id: "apaiser-la-colere", lang: "fr", theme: "Émotions & Régulation", collection: "regulation",
    title: "Apaiser la colère sans la refouler",
    blurb: "Une émotion valide à exprimer sans exploser ni imploser : un signal qui protège, recadrer refouler/exploser, ta colère est légitime, ressentir/pauser/exprimer le besoin de façon affirmée. 4 approches.",
    pdf: "apaiser-la-colere-4-approches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Un signal qui protège", "Ressentir ≠ agir", "Pause puis exprimer"] },
  { id: "calmer-anxiete-submersion", lang: "fr", theme: "Émotions & Régulation", collection: "regulation",
    title: "Calmer l'anxiété et la submersion",
    blurb: "Quand la vague monte : l'émotion est une vague, recadrer « je vais perdre le contrôle » (inconfortable ≠ dangereux), ne pas lutter contre toi-même, ancrage 5 sens et respiration. 4 approches.",
    pdf: "calmer-anxiete-submersion-4-approches.pdf", priceCents: 999, currency: "eur",
    bullets: ["L'émotion est une vague", "Inconfortable ≠ dangereux", "Ancrage & respiration"] },
  { id: "tolerer-l-inconfort", lang: "fr", theme: "Émotions & Régulation", collection: "regulation",
    title: "Tolérer l'inconfort et différer",
    blurb: "Résister à l'urgence de réagir : l'envie est une vague, recadrer « je dois agir maintenant », tu peux tenir l'inconfort, différer et surfer l'envie selon tes valeurs. 4 approches.",
    pdf: "tolerer-l-inconfort-4-approches.pdf", priceCents: 999, currency: "eur",
    bullets: ["L'envie retombe", "Tu peux tenir", "Différer & choisir"] },
  // ---- EN ----
  { id: "understanding-your-emotions", lang: "en", theme: "Emotions & Regulation", collection: "regulation",
    title: "Understanding and Welcoming Your Emotions",
    blurb: "Your emotions aren't the enemy: messengers not enemies, reframe 'I shouldn't feel this', all your emotions are legitimate, name/locate/listen to the need. 4 approaches.",
    pdf: "understanding-your-emotions-4-approaches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Messengers", "Neither good nor bad", "Name to soothe"] },
  { id: "your-emotion-regulation-toolkit", lang: "en", theme: "Emotions & Regulation", collection: "regulation",
    title: "Regulating Your Emotions: Your Toolkit",
    blurb: "The window of tolerance and the techniques that soothe: return to your window, reframe 'I can't calm down', compassion regulates, your kit (breathing, grounding, reappraisal, movement, pause). 4 approaches.",
    pdf: "your-emotion-regulation-toolkit-4-approaches.pdf", priceCents: 999, currency: "eur",
    bullets: ["The window of tolerance", "A learnable skill", "Your personal kit"] },
  { id: "managing-frustration", lang: "en", theme: "Emotions & Regulation", collection: "regulation",
    title: "Managing Frustration",
    blurb: "The gap between what you expect and what is: understand the gap, reframe rigid demands ('it's unbearable'), frustration is human, pause/soften/solve. 4 approaches.",
    pdf: "managing-frustration-4-approaches.pdf", priceCents: 999, currency: "eur",
    bullets: ["The expectation/reality gap", "Soften the demands", "Build your tolerance"] },
  { id: "soothing-anger", lang: "en", theme: "Emotions & Regulation", collection: "regulation",
    title: "Soothing Anger Without Suppressing It",
    blurb: "A valid emotion to express without exploding or imploding: a signal that protects, reframe suppress/explode, your anger is legitimate, feel/pause/express the need assertively. 4 approaches.",
    pdf: "soothing-anger-4-approaches.pdf", priceCents: 999, currency: "eur",
    bullets: ["A signal that protects", "Feel ≠ act", "Pause then express"] },
  { id: "calming-anxiety-and-overwhelm", lang: "en", theme: "Emotions & Regulation", collection: "regulation",
    title: "Calming Anxiety and Overwhelm",
    blurb: "When the wave rises: emotion is a wave, reframe 'I'll lose control' (uncomfortable ≠ dangerous), don't fight yourself, 5-sense grounding and breathing. 4 approaches.",
    pdf: "calming-anxiety-and-overwhelm-4-approaches.pdf", priceCents: 999, currency: "eur",
    bullets: ["Emotion is a wave", "Uncomfortable ≠ dangerous", "Grounding & breathing"] },
  { id: "tolerating-discomfort", lang: "en", theme: "Emotions & Regulation", collection: "regulation",
    title: "Tolerating Discomfort and Delaying",
    blurb: "Resisting the urge to react: the urge is a wave, reframe 'I must act now', you can hold discomfort, delay and surf the urge by your values. 4 approaches.",
    pdf: "tolerating-discomfort-4-approaches.pdf", priceCents: 999, currency: "eur",
    bullets: ["The urge subsides", "You can hold", "Delay & choose"] },
] as const;
